#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginFailure.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B66C77D0097D37333EA72E64089D5AA041076847"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Account_ExternalLoginFailure_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Account_ExternalLoginFailure_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginFailure.cshtml"
  
    ViewBag.Title = "Login Failure";

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ExternalLoginFailure.cshtml", 41, 19, true);

WriteLiteral("\n\n<hgroup>\n    <h2>");

EndContext("~/Views/Account/ExternalLoginFailure.cshtml", 41, 19, true);

BeginContext("~/Views/Account/ExternalLoginFailure.cshtml", 61, 13, false);

            
            #line 6 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginFailure.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ExternalLoginFailure.cshtml", 61, 13, false);

BeginContext("~/Views/Account/ExternalLoginFailure.cshtml", 74, 14, true);

WriteLiteral(".</h2>\n    <h3");

EndContext("~/Views/Account/ExternalLoginFailure.cshtml", 74, 14, true);

BeginContext("~/Views/Account/ExternalLoginFailure.cshtml", 88, 20, true);

WriteLiteral(" class=\"text-danger\"");

EndContext("~/Views/Account/ExternalLoginFailure.cshtml", 88, 20, true);

BeginContext("~/Views/Account/ExternalLoginFailure.cshtml", 108, 49, true);

WriteLiteral(">Unsuccessful login with service.</h3>\n</hgroup>\n");

EndContext("~/Views/Account/ExternalLoginFailure.cshtml", 108, 49, true);

        }
    }
}
