#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "80B12DEE68594062CEE1161645E8CBF4C2CB4737"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_ServiceCostSlabs_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<SOEEApp.Models.ServiceCostSlab>> {
        
#line hidden
        
        public _Page_Views_ServiceCostSlabs_Index_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Index.cshtml"
  
    ViewBag.Title = "Slab List";

            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 89, 6, true);

WriteLiteral("\n\n<div");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 89, 6, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 95, 36, true);

WriteLiteral(" class=\"row mb-4 align-items-center\"");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 95, 36, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 131, 10, true);

WriteLiteral(">\n    <div");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 131, 10, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 141, 12, true);

WriteLiteral(" class=\"col\"");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 141, 12, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 153, 13, true);

WriteLiteral(">\n        <h2");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 153, 13, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 166, 13, true);

WriteLiteral(" class=\"mb-0\"");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 166, 13, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 179, 44, true);

WriteLiteral(">Service Cost Slabs</h2>\n    </div>\n    <div");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 179, 44, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 223, 17, true);

WriteLiteral(" class=\"col-auto\"");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 223, 17, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 240, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 240, 2, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 242, 8, true);

WriteLiteral("        ");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 242, 8, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 251, 86, false);

            
            #line 12 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Index.cshtml"
   Write(Html.ActionLink("Create New Slab", "Create", null, new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 251, 86, false);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 337, 24, true);

WriteLiteral("\n    </div>\n</div>\n\n<div");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 337, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 361, 23, true);

WriteLiteral(" class=\"card shadow-sm\"");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 361, 23, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 384, 10, true);

WriteLiteral(">\n    <div");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 384, 10, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 394, 22, true);

WriteLiteral(" class=\"card-body p-0\"");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 394, 22, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 416, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 416, 14, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 430, 25, true);

WriteLiteral(" class=\"table-responsive\"");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 430, 25, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 455, 20, true);

WriteLiteral(">\n            <table");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 455, 20, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 475, 39, true);

WriteLiteral(" class=\"table table-hover align-middle\"");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 475, 39, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 514, 24, true);

WriteLiteral(">\n                <thead");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 514, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 538, 17, true);

WriteLiteral(" class=\"bg-light\"");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 538, 17, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 555, 54, true);

WriteLiteral(">\n                    <tr>\n                        <th");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 555, 54, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 609, 13, true);

WriteLiteral(" class=\"ps-4\"");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 609, 13, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 622, 88, true);

WriteLiteral(">Amount From</th>\n                        <th>Amount To</th>\n                    " +
"    <th");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 622, 88, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 710, 22, true);

WriteLiteral(" class=\"text-end pe-4\"");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 710, 22, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 732, 89, true);

WriteLiteral(">Actions</th>\n                    </tr>\n                </thead>\n                " +
"<tbody>\n");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 732, 89, true);

            
            #line 28 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 28 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Index.cshtml"
                     foreach (var item in Model)
                    {

            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 892, 60, true);

WriteLiteral("                        <tr>\n                            <td");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 892, 60, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 952, 13, true);

WriteLiteral(" class=\"ps-4\"");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 952, 13, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 965, 1, true);

WriteLiteral(">");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 965, 1, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 967, 39, false);

            
            #line 31 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Index.cshtml"
                                        Write(String.Format("{0:N2}", item.MinAmount));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 967, 39, false);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1006, 39, true);

WriteLiteral("</td>\n                            <td>\n");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1006, 39, true);

            
            #line 33 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Index.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 33 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Index.cshtml"
                                 if (item.MaxAmount.HasValue)
                                {
                                    
            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1178, 39, false);

            
            #line 35 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Index.cshtml"
                               Write(String.Format("{0:N2}", item.MaxAmount));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1178, 39, false);

            
            #line 35 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Index.cshtml"
                                                                            
                                }
                                else
                                {

            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1323, 41, true);

WriteLiteral("                                    <span");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1323, 41, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1364, 27, true);

WriteLiteral(" class=\"badge bg-secondary\"");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1364, 27, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1391, 18, true);

WriteLiteral(">Unlimited</span>\n");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1391, 18, true);

            
            #line 40 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Index.cshtml"
                                }

            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1443, 65, true);

WriteLiteral("                            </td>\n                            <td");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1443, 65, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1508, 22, true);

WriteLiteral(" class=\"text-end pe-4\"");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1508, 22, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1530, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1530, 2, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1532, 32, true);

WriteLiteral("                                ");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1532, 32, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1565, 109, false);

            
            #line 43 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Index.cshtml"
                           Write(Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-sm btn-outline-primary me-1" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1565, 109, false);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1674, 1, true);

WriteLiteral("\n");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1674, 1, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1675, 32, true);

WriteLiteral("                                ");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1675, 32, true);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1708, 107, false);

            
            #line 44 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Index.cshtml"
                           Write(Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-sm btn-outline-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1708, 107, false);

BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1815, 65, true);

WriteLiteral("\n                            </td>\n                        </tr>\n");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1815, 65, true);

            
            #line 47 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Index.cshtml"
                    }

            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Index.cshtml", 1902, 79, true);

WriteLiteral("                </tbody>\n            </table>\n        </div>\n    </div>\n</div>\n");

EndContext("~/Views/ServiceCostSlabs/Index.cshtml", 1902, 79, true);

        }
    }
}
