#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "FA5645AED354F06789271B82CA8750085774DB81"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Projects_Delete_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.Project> {
        
#line hidden
        
        public _Page_Views_Projects_Delete_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml"
  
    ViewBag.Title = "Delete Project";

            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Delete.cshtml", 77, 8, true);

WriteLiteral("\r\n\r\n<div");

EndContext("~/Views/Projects/Delete.cshtml", 77, 8, true);

BeginContext("~/Views/Projects/Delete.cshtml", 85, 40, true);

WriteLiteral(" class=\"row justify-content-center mt-5\"");

EndContext("~/Views/Projects/Delete.cshtml", 85, 40, true);

BeginContext("~/Views/Projects/Delete.cshtml", 125, 11, true);

WriteLiteral(">\r\n    <div");

EndContext("~/Views/Projects/Delete.cshtml", 125, 11, true);

BeginContext("~/Views/Projects/Delete.cshtml", 136, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Projects/Delete.cshtml", 136, 17, true);

BeginContext("~/Views/Projects/Delete.cshtml", 153, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/Projects/Delete.cshtml", 153, 15, true);

BeginContext("~/Views/Projects/Delete.cshtml", 168, 32, true);

WriteLiteral(" class=\"card shadow-sm border-0\"");

EndContext("~/Views/Projects/Delete.cshtml", 168, 32, true);

BeginContext("~/Views/Projects/Delete.cshtml", 200, 19, true);

WriteLiteral(">\r\n            <div");

EndContext("~/Views/Projects/Delete.cshtml", 200, 19, true);

BeginContext("~/Views/Projects/Delete.cshtml", 219, 41, true);

WriteLiteral(" class=\"card-header bg-danger text-white\"");

EndContext("~/Views/Projects/Delete.cshtml", 219, 41, true);

BeginContext("~/Views/Projects/Delete.cshtml", 260, 22, true);

WriteLiteral(">\r\n                <h4");

EndContext("~/Views/Projects/Delete.cshtml", 260, 22, true);

BeginContext("~/Views/Projects/Delete.cshtml", 282, 13, true);

WriteLiteral(" class=\"mb-0\"");

EndContext("~/Views/Projects/Delete.cshtml", 282, 13, true);

BeginContext("~/Views/Projects/Delete.cshtml", 295, 58, true);

WriteLiteral(">Delete Project</h4>\r\n            </div>\r\n            <div");

EndContext("~/Views/Projects/Delete.cshtml", 295, 58, true);

BeginContext("~/Views/Projects/Delete.cshtml", 353, 18, true);

WriteLiteral(" class=\"card-body\"");

EndContext("~/Views/Projects/Delete.cshtml", 353, 18, true);

BeginContext("~/Views/Projects/Delete.cshtml", 371, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Projects/Delete.cshtml", 371, 3, true);

            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml"
                
            
            #line default
            #line hidden
            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml"
                 if (!ViewData.ModelState.IsValid)
                {

            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Delete.cshtml", 445, 24, true);

WriteLiteral("                    <div");

EndContext("~/Views/Projects/Delete.cshtml", 445, 24, true);

BeginContext("~/Views/Projects/Delete.cshtml", 469, 27, true);

WriteLiteral(" class=\"alert alert-danger\"");

EndContext("~/Views/Projects/Delete.cshtml", 469, 27, true);

BeginContext("~/Views/Projects/Delete.cshtml", 496, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Projects/Delete.cshtml", 496, 3, true);

BeginContext("~/Views/Projects/Delete.cshtml", 499, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Delete.cshtml", 499, 24, true);

BeginContext("~/Views/Projects/Delete.cshtml", 524, 33, false);

            
            #line 17 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml"
                   Write(Html.ValidationSummary(false, ""));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Delete.cshtml", 524, 33, false);

BeginContext("~/Views/Projects/Delete.cshtml", 557, 30, true);

WriteLiteral("\r\n                    </div>\r\n");

EndContext("~/Views/Projects/Delete.cshtml", 557, 30, true);

            
            #line 19 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml"
                }

            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Delete.cshtml", 606, 37, true);

WriteLiteral("                \r\n                <h5");

EndContext("~/Views/Projects/Delete.cshtml", 606, 37, true);

BeginContext("~/Views/Projects/Delete.cshtml", 643, 36, true);

WriteLiteral(" class=\"card-title text-center mb-4\"");

EndContext("~/Views/Projects/Delete.cshtml", 643, 36, true);

BeginContext("~/Views/Projects/Delete.cshtml", 679, 90, true);

WriteLiteral(">Are you sure you want to delete this project?</h5>\r\n                \r\n          " +
"      <dl");

EndContext("~/Views/Projects/Delete.cshtml", 679, 90, true);

BeginContext("~/Views/Projects/Delete.cshtml", 769, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/Projects/Delete.cshtml", 769, 12, true);

BeginContext("~/Views/Projects/Delete.cshtml", 781, 26, true);

WriteLiteral(">\r\n                    <dt");

EndContext("~/Views/Projects/Delete.cshtml", 781, 26, true);

BeginContext("~/Views/Projects/Delete.cshtml", 807, 17, true);

WriteLiteral(" class=\"col-sm-4\"");

EndContext("~/Views/Projects/Delete.cshtml", 807, 17, true);

BeginContext("~/Views/Projects/Delete.cshtml", 824, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Projects/Delete.cshtml", 824, 3, true);

BeginContext("~/Views/Projects/Delete.cshtml", 827, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Delete.cshtml", 827, 24, true);

BeginContext("~/Views/Projects/Delete.cshtml", 852, 40, false);

            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml"
                   Write(Html.DisplayNameFor(model => model.Name));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Delete.cshtml", 852, 40, false);

BeginContext("~/Views/Projects/Delete.cshtml", 892, 52, true);

WriteLiteral("\r\n                    </dt>\r\n                    <dd");

EndContext("~/Views/Projects/Delete.cshtml", 892, 52, true);

BeginContext("~/Views/Projects/Delete.cshtml", 944, 17, true);

WriteLiteral(" class=\"col-sm-8\"");

EndContext("~/Views/Projects/Delete.cshtml", 944, 17, true);

BeginContext("~/Views/Projects/Delete.cshtml", 961, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Projects/Delete.cshtml", 961, 3, true);

BeginContext("~/Views/Projects/Delete.cshtml", 964, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Delete.cshtml", 964, 24, true);

BeginContext("~/Views/Projects/Delete.cshtml", 989, 36, false);

            
            #line 28 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml"
                   Write(Html.DisplayFor(model => model.Name));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Delete.cshtml", 989, 36, false);

BeginContext("~/Views/Projects/Delete.cshtml", 1025, 54, true);

WriteLiteral("\r\n                    </dd>\r\n\r\n                    <dt");

EndContext("~/Views/Projects/Delete.cshtml", 1025, 54, true);

BeginContext("~/Views/Projects/Delete.cshtml", 1079, 17, true);

WriteLiteral(" class=\"col-sm-4\"");

EndContext("~/Views/Projects/Delete.cshtml", 1079, 17, true);

BeginContext("~/Views/Projects/Delete.cshtml", 1096, 85, true);

WriteLiteral(">\r\n                        Status\r\n                    </dt>\r\n                   " +
" <dd");

EndContext("~/Views/Projects/Delete.cshtml", 1096, 85, true);

BeginContext("~/Views/Projects/Delete.cshtml", 1181, 17, true);

WriteLiteral(" class=\"col-sm-8\"");

EndContext("~/Views/Projects/Delete.cshtml", 1181, 17, true);

BeginContext("~/Views/Projects/Delete.cshtml", 1198, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Projects/Delete.cshtml", 1198, 3, true);

BeginContext("~/Views/Projects/Delete.cshtml", 1201, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Delete.cshtml", 1201, 24, true);

BeginContext("~/Views/Projects/Delete.cshtml", 1226, 38, false);

            
            #line 35 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml"
                   Write(Html.DisplayFor(model => model.Status));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Delete.cshtml", 1226, 38, false);

BeginContext("~/Views/Projects/Delete.cshtml", 1264, 54, true);

WriteLiteral("\r\n                    </dd>\r\n                </dl>\r\n\r\n");

EndContext("~/Views/Projects/Delete.cshtml", 1264, 54, true);

            
            #line 39 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml"
                
            
            #line default
            #line hidden
            
            #line 39 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml"
                 using (Html.BeginForm()) {
                    
            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Delete.cshtml", 1384, 23, false);

            
            #line 40 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml"
               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Delete.cshtml", 1384, 23, false);

            
            #line 40 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml"
                                            

            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Delete.cshtml", 1409, 24, true);

WriteLiteral("                    <div");

EndContext("~/Views/Projects/Delete.cshtml", 1409, 24, true);

BeginContext("~/Views/Projects/Delete.cshtml", 1433, 62, true);

WriteLiteral(" class=\"d-grid gap-2 d-md-flex justify-content-md-center mt-4\"");

EndContext("~/Views/Projects/Delete.cshtml", 1433, 62, true);

BeginContext("~/Views/Projects/Delete.cshtml", 1495, 33, true);

WriteLiteral(">\r\n                        <input");

EndContext("~/Views/Projects/Delete.cshtml", 1495, 33, true);

BeginContext("~/Views/Projects/Delete.cshtml", 1528, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Projects/Delete.cshtml", 1528, 14, true);

BeginContext("~/Views/Projects/Delete.cshtml", 1542, 15, true);

WriteLiteral(" value=\"Delete\"");

EndContext("~/Views/Projects/Delete.cshtml", 1542, 15, true);

BeginContext("~/Views/Projects/Delete.cshtml", 1557, 28, true);

WriteLiteral(" class=\"btn btn-danger px-4\"");

EndContext("~/Views/Projects/Delete.cshtml", 1557, 28, true);

BeginContext("~/Views/Projects/Delete.cshtml", 1585, 5, true);

WriteLiteral(" />\r\n");

EndContext("~/Views/Projects/Delete.cshtml", 1585, 5, true);

BeginContext("~/Views/Projects/Delete.cshtml", 1590, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Delete.cshtml", 1590, 24, true);

BeginContext("~/Views/Projects/Delete.cshtml", 1615, 83, false);

            
            #line 43 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml"
                   Write(Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary px-4" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Delete.cshtml", 1615, 83, false);

BeginContext("~/Views/Projects/Delete.cshtml", 1698, 30, true);

WriteLiteral("\r\n                    </div>\r\n");

EndContext("~/Views/Projects/Delete.cshtml", 1698, 30, true);

            
            #line 45 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Delete.cshtml"
                }

            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Delete.cshtml", 1747, 56, true);

WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

EndContext("~/Views/Projects/Delete.cshtml", 1747, 56, true);

        }
    }
}
