//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.5.2")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_rdixwxcm {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_rdixwxcm() {
        }
        
        static object Create_ASP__Page_Views_Account_ForgotPassword_cshtml() {
            return new ASP._Page_Views_Account_ForgotPassword_cshtml();
        }
        
        static object Create_ASP__Page_Views_Account_ExternalLoginConfirmation_cshtml() {
            return new ASP._Page_Views_Account_ExternalLoginConfirmation_cshtml();
        }
        
        static object Create_ASP__Page_Views_Account_ExternalLoginFailure_cshtml() {
            return new ASP._Page_Views_Account_ExternalLoginFailure_cshtml();
        }
        
        static object Create_ASP__Page_Views_Account_VerifyCode_cshtml() {
            return new ASP._Page_Views_Account_VerifyCode_cshtml();
        }
        
        static object Create_ASP__Page_Views_Account_ResetPasswordConfirmation_cshtml() {
            return new ASP._Page_Views_Account_ResetPasswordConfirmation_cshtml();
        }
        
        static object Create_ASP__Page_Views_Account_Login_cshtml() {
            return new ASP._Page_Views_Account_Login_cshtml();
        }
        
        static object Create_ASP__Page_Views_Account_ConfirmEmail_cshtml() {
            return new ASP._Page_Views_Account_ConfirmEmail_cshtml();
        }
        
        static object Create_ASP__Page_Views_Account_SendCode_cshtml() {
            return new ASP._Page_Views_Account_SendCode_cshtml();
        }
        
        static object Create_ASP__Page_Views_Account_ForgotPasswordConfirmation_cshtml() {
            return new ASP._Page_Views_Account_ForgotPasswordConfirmation_cshtml();
        }
        
        static object Create_ASP__Page_Views_Account_ResetPassword_cshtml() {
            return new ASP._Page_Views_Account_ResetPassword_cshtml();
        }
        
        static object Create_ASP__Page_Views_Account_Register_cshtml() {
            return new ASP._Page_Views_Account_Register_cshtml();
        }
        
        static object Create_ASP__Page_Views_Account__ExternalLoginsListPartial_cshtml() {
            return new ASP._Page_Views_Account__ExternalLoginsListPartial_cshtml();
        }
    }
}
