#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1EA276CD960B3413125EB95F1715FB033258E5A7"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Account_VerifyCode_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.VerifyCodeViewModel> {
        
#line hidden
        
        public _Page_Views_Account_VerifyCode_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 2 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
  
    ViewBag.Title = "Verify";

            
            #line default
            #line hidden
BeginContext("~/Views/Account/VerifyCode.cshtml", 76, 6, true);

WriteLiteral("\n\n<h2>");

EndContext("~/Views/Account/VerifyCode.cshtml", 76, 6, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 83, 13, false);

            
            #line 6 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Account/VerifyCode.cshtml", 83, 13, false);

BeginContext("~/Views/Account/VerifyCode.cshtml", 96, 8, true);

WriteLiteral(".</h2>\n\n");

EndContext("~/Views/Account/VerifyCode.cshtml", 96, 8, true);

            
            #line 8 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
 using (Html.BeginForm("VerifyCode", "Account", new { ReturnUrl = Model.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" })) {
    
            
            #line default
            #line hidden
BeginContext("~/Views/Account/VerifyCode.cshtml", 265, 23, false);

            
            #line 9 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Account/VerifyCode.cshtml", 265, 23, false);

            
            #line 9 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
                            
    
            
            #line default
            #line hidden
BeginContext("~/Views/Account/VerifyCode.cshtml", 294, 40, false);

            
            #line 10 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
Write(Html.Hidden("provider", @Model.Provider));

            
            #line default
            #line hidden
EndContext("~/Views/Account/VerifyCode.cshtml", 294, 40, false);

            
            #line 10 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
                                             
    
            
            #line default
            #line hidden
BeginContext("~/Views/Account/VerifyCode.cshtml", 340, 44, false);

            
            #line 11 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
Write(Html.Hidden("rememberMe", @Model.RememberMe));

            
            #line default
            #line hidden
EndContext("~/Views/Account/VerifyCode.cshtml", 340, 44, false);

            
            #line 11 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
                                                 

            
            #line default
            #line hidden
BeginContext("~/Views/Account/VerifyCode.cshtml", 385, 37, true);

WriteLiteral("    <h4>Enter verification code</h4>\n");

EndContext("~/Views/Account/VerifyCode.cshtml", 385, 37, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 422, 11, true);

WriteLiteral("    <hr />\n");

EndContext("~/Views/Account/VerifyCode.cshtml", 422, 11, true);

            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
    
            
            #line default
            #line hidden
BeginContext("~/Views/Account/VerifyCode.cshtml", 438, 58, false);

            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
Write(Html.ValidationSummary("", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/VerifyCode.cshtml", 438, 58, false);

            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
                                                               

            
            #line default
            #line hidden
BeginContext("~/Views/Account/VerifyCode.cshtml", 497, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/VerifyCode.cshtml", 497, 8, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 505, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/VerifyCode.cshtml", 505, 19, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 524, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Account/VerifyCode.cshtml", 524, 2, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 526, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/VerifyCode.cshtml", 526, 8, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 535, 69, false);

            
            #line 16 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
   Write(Html.LabelFor(m => m.Code, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/VerifyCode.cshtml", 535, 69, false);

BeginContext("~/Views/Account/VerifyCode.cshtml", 604, 13, true);

WriteLiteral("\n        <div");

EndContext("~/Views/Account/VerifyCode.cshtml", 604, 13, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 617, 18, true);

WriteLiteral(" class=\"col-md-10\"");

EndContext("~/Views/Account/VerifyCode.cshtml", 617, 18, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 635, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Account/VerifyCode.cshtml", 635, 2, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 637, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/VerifyCode.cshtml", 637, 12, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 650, 61, false);

            
            #line 18 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
       Write(Html.TextBoxFor(m => m.Code, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/VerifyCode.cshtml", 650, 61, false);

BeginContext("~/Views/Account/VerifyCode.cshtml", 711, 27, true);

WriteLiteral("\n        </div>\n    </div>\n");

EndContext("~/Views/Account/VerifyCode.cshtml", 711, 27, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 738, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/VerifyCode.cshtml", 738, 8, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 746, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/VerifyCode.cshtml", 746, 19, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 765, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Account/VerifyCode.cshtml", 765, 14, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 779, 34, true);

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

EndContext("~/Views/Account/VerifyCode.cshtml", 779, 34, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 813, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Account/VerifyCode.cshtml", 813, 18, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 831, 17, true);

WriteLiteral(" class=\"checkbox\"");

EndContext("~/Views/Account/VerifyCode.cshtml", 831, 17, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 848, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Account/VerifyCode.cshtml", 848, 2, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 850, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Account/VerifyCode.cshtml", 850, 16, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 867, 40, false);

            
            #line 24 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
           Write(Html.CheckBoxFor(m => m.RememberBrowser));

            
            #line default
            #line hidden
EndContext("~/Views/Account/VerifyCode.cshtml", 867, 40, false);

BeginContext("~/Views/Account/VerifyCode.cshtml", 907, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/VerifyCode.cshtml", 907, 1, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 908, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Account/VerifyCode.cshtml", 908, 16, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 925, 37, false);

            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
           Write(Html.LabelFor(m => m.RememberBrowser));

            
            #line default
            #line hidden
EndContext("~/Views/Account/VerifyCode.cshtml", 925, 37, false);

BeginContext("~/Views/Account/VerifyCode.cshtml", 962, 46, true);

WriteLiteral("\n            </div>\n        </div>\n    </div>\n");

EndContext("~/Views/Account/VerifyCode.cshtml", 962, 46, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 1008, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/VerifyCode.cshtml", 1008, 8, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 1016, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/VerifyCode.cshtml", 1016, 19, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 1035, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Account/VerifyCode.cshtml", 1035, 14, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 1049, 34, true);

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

EndContext("~/Views/Account/VerifyCode.cshtml", 1049, 34, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 1083, 20, true);

WriteLiteral(">\n            <input");

EndContext("~/Views/Account/VerifyCode.cshtml", 1083, 20, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 1103, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Account/VerifyCode.cshtml", 1103, 14, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 1117, 24, true);

WriteLiteral(" class=\"btn btn-default\"");

EndContext("~/Views/Account/VerifyCode.cshtml", 1117, 24, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 1141, 15, true);

WriteLiteral(" value=\"Submit\"");

EndContext("~/Views/Account/VerifyCode.cshtml", 1141, 15, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 1156, 30, true);

WriteLiteral(" />\n        </div>\n    </div>\n");

EndContext("~/Views/Account/VerifyCode.cshtml", 1156, 30, true);

            
            #line 34 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/Account/VerifyCode.cshtml", 1188, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/VerifyCode.cshtml", 1188, 1, true);

DefineSection("Scripts", () => {

BeginContext("~/Views/Account/VerifyCode.cshtml", 1207, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/VerifyCode.cshtml", 1207, 1, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 1208, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Account/VerifyCode.cshtml", 1208, 4, true);

BeginContext("~/Views/Account/VerifyCode.cshtml", 1213, 37, false);

            
            #line 37 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\VerifyCode.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
EndContext("~/Views/Account/VerifyCode.cshtml", 1213, 37, false);

BeginContext("~/Views/Account/VerifyCode.cshtml", 1250, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/VerifyCode.cshtml", 1250, 1, true);

});

        }
    }
}
