#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "C6E702B1D625A0EB8D4606E7B1F15810280AA399"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Projects_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<SOEEApp.Models.Project>> {
        
#line hidden
        
        public _Page_Views_Projects_Index_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Projects/Index.cshtml", 44, 4, true);

WriteLiteral("<div");

EndContext("~/Views/Projects/Index.cshtml", 44, 4, true);

BeginContext("~/Views/Projects/Index.cshtml", 48, 36, true);

WriteLiteral(" class=\"row mb-4 align-items-center\"");

EndContext("~/Views/Projects/Index.cshtml", 48, 36, true);

BeginContext("~/Views/Projects/Index.cshtml", 84, 10, true);

WriteLiteral(">\n    <div");

EndContext("~/Views/Projects/Index.cshtml", 84, 10, true);

BeginContext("~/Views/Projects/Index.cshtml", 94, 12, true);

WriteLiteral(" class=\"col\"");

EndContext("~/Views/Projects/Index.cshtml", 94, 12, true);

BeginContext("~/Views/Projects/Index.cshtml", 106, 13, true);

WriteLiteral(">\n        <h2");

EndContext("~/Views/Projects/Index.cshtml", 106, 13, true);

BeginContext("~/Views/Projects/Index.cshtml", 119, 13, true);

WriteLiteral(" class=\"mb-0\"");

EndContext("~/Views/Projects/Index.cshtml", 119, 13, true);

BeginContext("~/Views/Projects/Index.cshtml", 132, 34, true);

WriteLiteral(">Projects</h2>\n    </div>\n    <div");

EndContext("~/Views/Projects/Index.cshtml", 132, 34, true);

BeginContext("~/Views/Projects/Index.cshtml", 166, 17, true);

WriteLiteral(" class=\"col-auto\"");

EndContext("~/Views/Projects/Index.cshtml", 166, 17, true);

BeginContext("~/Views/Projects/Index.cshtml", 183, 12, true);

WriteLiteral(">\n        <a");

EndContext("~/Views/Projects/Index.cshtml", 183, 12, true);

BeginContext("~/Views/Projects/Index.cshtml", 195, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/Projects/Index.cshtml", 195, 24, true);

WriteAttribute("href", Tuple.Create(" href=\"", 219), Tuple.Create("\"", 247)
            
            #line 8 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Index.cshtml"
, Tuple.Create(Tuple.Create("", 226), Tuple.Create<System.Object, System.Int32>(Url.Action("Create")
            
            #line default
            #line hidden
, 226), false)
);

BeginContext("~/Views/Projects/Index.cshtml", 248, 40, true);

WriteLiteral(">Add Project</a>\n    </div>\n</div>\n\n<div");

EndContext("~/Views/Projects/Index.cshtml", 248, 40, true);

BeginContext("~/Views/Projects/Index.cshtml", 288, 23, true);

WriteLiteral(" class=\"card shadow-sm\"");

EndContext("~/Views/Projects/Index.cshtml", 288, 23, true);

BeginContext("~/Views/Projects/Index.cshtml", 311, 10, true);

WriteLiteral(">\n    <div");

EndContext("~/Views/Projects/Index.cshtml", 311, 10, true);

BeginContext("~/Views/Projects/Index.cshtml", 321, 22, true);

WriteLiteral(" class=\"card-body p-0\"");

EndContext("~/Views/Projects/Index.cshtml", 321, 22, true);

BeginContext("~/Views/Projects/Index.cshtml", 343, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Projects/Index.cshtml", 343, 14, true);

BeginContext("~/Views/Projects/Index.cshtml", 357, 25, true);

WriteLiteral(" class=\"table-responsive\"");

EndContext("~/Views/Projects/Index.cshtml", 357, 25, true);

BeginContext("~/Views/Projects/Index.cshtml", 382, 20, true);

WriteLiteral(">\n            <table");

EndContext("~/Views/Projects/Index.cshtml", 382, 20, true);

BeginContext("~/Views/Projects/Index.cshtml", 402, 44, true);

WriteLiteral(" class=\"table table-hover align-middle mb-0\"");

EndContext("~/Views/Projects/Index.cshtml", 402, 44, true);

BeginContext("~/Views/Projects/Index.cshtml", 446, 24, true);

WriteLiteral(">\n                <thead");

EndContext("~/Views/Projects/Index.cshtml", 446, 24, true);

BeginContext("~/Views/Projects/Index.cshtml", 470, 17, true);

WriteLiteral(" class=\"bg-light\"");

EndContext("~/Views/Projects/Index.cshtml", 470, 17, true);

BeginContext("~/Views/Projects/Index.cshtml", 487, 54, true);

WriteLiteral(">\n                    <tr>\n                        <th");

EndContext("~/Views/Projects/Index.cshtml", 487, 54, true);

BeginContext("~/Views/Projects/Index.cshtml", 541, 13, true);

WriteLiteral(" class=\"ps-4\"");

EndContext("~/Views/Projects/Index.cshtml", 541, 13, true);

BeginContext("~/Views/Projects/Index.cshtml", 554, 169, true);

WriteLiteral(">Project Name</th>\n                        <th>Project Cost</th>\n                " +
"        <th>OIC</th>\n                        <th>Status</th>\n                   " +
"     <th");

EndContext("~/Views/Projects/Index.cshtml", 554, 169, true);

BeginContext("~/Views/Projects/Index.cshtml", 723, 22, true);

WriteLiteral(" class=\"text-end pe-4\"");

EndContext("~/Views/Projects/Index.cshtml", 723, 22, true);

BeginContext("~/Views/Projects/Index.cshtml", 745, 89, true);

WriteLiteral(">Actions</th>\n                    </tr>\n                </thead>\n                " +
"<tbody>\n");

EndContext("~/Views/Projects/Index.cshtml", 745, 89, true);

            
            #line 26 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 26 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Index.cshtml"
                     foreach (var p in Model)
                    {

            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Index.cshtml", 902, 60, true);

WriteLiteral("                        <tr>\n                            <td");

EndContext("~/Views/Projects/Index.cshtml", 902, 60, true);

BeginContext("~/Views/Projects/Index.cshtml", 962, 13, true);

WriteLiteral(" class=\"ps-4\"");

EndContext("~/Views/Projects/Index.cshtml", 962, 13, true);

BeginContext("~/Views/Projects/Index.cshtml", 975, 1, true);

WriteLiteral(">");

EndContext("~/Views/Projects/Index.cshtml", 975, 1, true);

BeginContext("~/Views/Projects/Index.cshtml", 977, 6, false);

            
            #line 29 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Index.cshtml"
                                        Write(p.Name);

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Index.cshtml", 977, 6, false);

BeginContext("~/Views/Projects/Index.cshtml", 983, 38, true);

WriteLiteral("</td>\n                            <td>");

EndContext("~/Views/Projects/Index.cshtml", 983, 38, true);

BeginContext("~/Views/Projects/Index.cshtml", 1022, 28, false);

            
            #line 30 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Index.cshtml"
                           Write(p.ProjectCost.ToString("N2"));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Index.cshtml", 1022, 28, false);

BeginContext("~/Views/Projects/Index.cshtml", 1050, 38, true);

WriteLiteral("</td>\n                            <td>");

EndContext("~/Views/Projects/Index.cshtml", 1050, 38, true);

BeginContext("~/Views/Projects/Index.cshtml", 1090, 61, false);

            
            #line 31 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Index.cshtml"
                            Write(p.OICUser != null ? p.OICUser.Name ?? p.OICUser.UserName : "");

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Index.cshtml", 1090, 61, false);

BeginContext("~/Views/Projects/Index.cshtml", 1152, 76, true);

WriteLiteral("</td>\n                            <td>\n                                <span");

EndContext("~/Views/Projects/Index.cshtml", 1152, 76, true);

BeginContext("~/Views/Projects/Index.cshtml", 1228, 40, true);

WriteLiteral(" class=\"badge bg-light text-dark border\"");

EndContext("~/Views/Projects/Index.cshtml", 1228, 40, true);

BeginContext("~/Views/Projects/Index.cshtml", 1268, 1, true);

WriteLiteral(">");

EndContext("~/Views/Projects/Index.cshtml", 1268, 1, true);

BeginContext("~/Views/Projects/Index.cshtml", 1270, 8, false);

            
            #line 33 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Index.cshtml"
                                                                         Write(p.Status);

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Index.cshtml", 1270, 8, false);

BeginContext("~/Views/Projects/Index.cshtml", 1278, 73, true);

WriteLiteral("</span>\n                            </td>\n                            <td");

EndContext("~/Views/Projects/Index.cshtml", 1278, 73, true);

BeginContext("~/Views/Projects/Index.cshtml", 1351, 22, true);

WriteLiteral(" class=\"text-end pe-4\"");

EndContext("~/Views/Projects/Index.cshtml", 1351, 22, true);

BeginContext("~/Views/Projects/Index.cshtml", 1373, 36, true);

WriteLiteral(">\n                                <a");

EndContext("~/Views/Projects/Index.cshtml", 1373, 36, true);

BeginContext("~/Views/Projects/Index.cshtml", 1409, 44, true);

WriteLiteral(" class=\"btn btn-sm btn-outline-primary me-1\"");

EndContext("~/Views/Projects/Index.cshtml", 1409, 44, true);

WriteAttribute("href", Tuple.Create(" href=\"", 1453), Tuple.Create("\"", 1505)
            
            #line 36 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Index.cshtml"
     , Tuple.Create(Tuple.Create("", 1460), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", new { id = p.ProjectID })
            
            #line default
            #line hidden
, 1460), false)
);

BeginContext("~/Views/Projects/Index.cshtml", 1506, 44, true);

WriteLiteral(">Edit</a>\n                                <a");

EndContext("~/Views/Projects/Index.cshtml", 1506, 44, true);

BeginContext("~/Views/Projects/Index.cshtml", 1550, 46, true);

WriteLiteral(" class=\"btn btn-sm btn-outline-secondary me-1\"");

EndContext("~/Views/Projects/Index.cshtml", 1550, 46, true);

WriteAttribute("href", Tuple.Create(" href=\"", 1596), Tuple.Create("\"", 1687)
            
            #line 37 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Index.cshtml"
       , Tuple.Create(Tuple.Create("", 1603), Tuple.Create<System.Object, System.Int32>(Url.Action("ManageServices", "ProjectServiceMapS", new { projectId = p.ProjectID })
            
            #line default
            #line hidden
, 1603), false)
);

BeginContext("~/Views/Projects/Index.cshtml", 1688, 48, true);

WriteLiteral(">Services</a>\n                                <a");

EndContext("~/Views/Projects/Index.cshtml", 1688, 48, true);

BeginContext("~/Views/Projects/Index.cshtml", 1736, 38, true);

WriteLiteral(" class=\"btn btn-sm btn-outline-danger\"");

EndContext("~/Views/Projects/Index.cshtml", 1736, 38, true);

WriteAttribute("href", Tuple.Create(" href=\"", 1774), Tuple.Create("\"", 1828)
            
            #line 38 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1781), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", new { id = p.ProjectID })
            
            #line default
            #line hidden
, 1781), false)
);

BeginContext("~/Views/Projects/Index.cshtml", 1829, 76, true);

WriteLiteral(">Delete</a>\n                            </td>\n                        </tr>\n");

EndContext("~/Views/Projects/Index.cshtml", 1829, 76, true);

            
            #line 41 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Index.cshtml"
                    }

            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Index.cshtml", 1927, 79, true);

WriteLiteral("                </tbody>\n            </table>\n        </div>\n    </div>\n</div>\n");

EndContext("~/Views/Projects/Index.cshtml", 1927, 79, true);

        }
    }
}
