#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Delete.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "00C44625750374A45EFDB3CCCAC33382104A6558"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_ServiceCostSlabs_Delete_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.ServiceCostSlab> {
        
#line hidden
        
        public _Page_Views_ServiceCostSlabs_Delete_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Delete.cshtml"
  
    ViewBag.Title = "Delete Slab";

            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 82, 8, true);

WriteLiteral("\r\n\r\n<div");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 82, 8, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 90, 40, true);

WriteLiteral(" class=\"row justify-content-center mt-5\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 90, 40, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 130, 11, true);

WriteLiteral(">\r\n    <div");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 130, 11, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 141, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 141, 17, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 158, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 158, 15, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 173, 32, true);

WriteLiteral(" class=\"card shadow-sm border-0\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 173, 32, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 205, 19, true);

WriteLiteral(">\r\n            <div");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 205, 19, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 224, 41, true);

WriteLiteral(" class=\"card-header bg-danger text-white\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 224, 41, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 265, 22, true);

WriteLiteral(">\r\n                <h4");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 265, 22, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 287, 13, true);

WriteLiteral(" class=\"mb-0\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 287, 13, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 300, 55, true);

WriteLiteral(">Delete Slab</h4>\r\n            </div>\r\n            <div");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 300, 55, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 355, 18, true);

WriteLiteral(" class=\"card-body\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 355, 18, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 373, 22, true);

WriteLiteral(">\r\n                <h5");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 373, 22, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 395, 36, true);

WriteLiteral(" class=\"card-title text-center mb-4\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 395, 36, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 431, 87, true);

WriteLiteral(">Are you sure you want to delete this slab?</h5>\r\n                \r\n             " +
"   <dl");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 431, 87, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 518, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 518, 12, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 530, 26, true);

WriteLiteral(">\r\n                    <dt");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 530, 26, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 556, 17, true);

WriteLiteral(" class=\"col-sm-4\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 556, 17, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 573, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 573, 3, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 576, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 576, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 601, 45, false);

            
            #line 18 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Delete.cshtml"
                   Write(Html.DisplayNameFor(model => model.MinAmount));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 601, 45, false);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 646, 52, true);

WriteLiteral("\r\n                    </dt>\r\n                    <dd");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 646, 52, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 698, 17, true);

WriteLiteral(" class=\"col-sm-8\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 698, 17, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 715, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 715, 3, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 718, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 718, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 743, 41, false);

            
            #line 21 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Delete.cshtml"
                   Write(Html.DisplayFor(model => model.MinAmount));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 743, 41, false);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 784, 54, true);

WriteLiteral("\r\n                    </dd>\r\n\r\n                    <dt");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 784, 54, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 838, 17, true);

WriteLiteral(" class=\"col-sm-4\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 838, 17, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 855, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 855, 3, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 858, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 858, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 883, 45, false);

            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Delete.cshtml"
                   Write(Html.DisplayNameFor(model => model.MaxAmount));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 883, 45, false);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 928, 52, true);

WriteLiteral("\r\n                    </dt>\r\n                    <dd");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 928, 52, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 980, 17, true);

WriteLiteral(" class=\"col-sm-8\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 980, 17, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 997, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 997, 3, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1000, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1000, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1025, 41, false);

            
            #line 28 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Delete.cshtml"
                   Write(Html.DisplayFor(model => model.MaxAmount));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1025, 41, false);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1066, 54, true);

WriteLiteral("\r\n                    </dd>\r\n                </dl>\r\n\r\n");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1066, 54, true);

            
            #line 32 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Delete.cshtml"
                
            
            #line default
            #line hidden
            
            #line 32 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Delete.cshtml"
                 using (Html.BeginForm()) {
                    
            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1186, 23, false);

            
            #line 33 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Delete.cshtml"
               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1186, 23, false);

            
            #line 33 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Delete.cshtml"
                                            

            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1211, 24, true);

WriteLiteral("                    <div");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1211, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1235, 62, true);

WriteLiteral(" class=\"d-grid gap-2 d-md-flex justify-content-md-center mt-4\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1235, 62, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1297, 33, true);

WriteLiteral(">\r\n                        <input");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1297, 33, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1330, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1330, 14, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1344, 15, true);

WriteLiteral(" value=\"Delete\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1344, 15, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1359, 28, true);

WriteLiteral(" class=\"btn btn-danger px-4\"");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1359, 28, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1387, 5, true);

WriteLiteral(" />\r\n");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1387, 5, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1392, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1392, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1417, 83, false);

            
            #line 36 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Delete.cshtml"
                   Write(Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary px-4" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1417, 83, false);

BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1500, 30, true);

WriteLiteral("\r\n                    </div>\r\n");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1500, 30, true);

            
            #line 38 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Delete.cshtml"
                }

            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1549, 56, true);

WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

EndContext("~/Views/ServiceCostSlabs/Delete.cshtml", 1549, 56, true);

        }
    }
}
