#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Home\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8722FBDC21CFA9B8C3600E85FB587082A0B2F503"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home_Index_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "C:\projects\SOEEApp-main\SOEEApp\Views\Home\Index.cshtml"
  
    ViewBag.Title = "SOEE Portal";

            
            #line default
            #line hidden
BeginContext("~/Views/Home/Index.cshtml", 39, 5, true);

WriteLiteral("\n<div");

EndContext("~/Views/Home/Index.cshtml", 39, 5, true);

BeginContext("~/Views/Home/Index.cshtml", 44, 23, true);

WriteLiteral(" class=\"container mt-5\"");

EndContext("~/Views/Home/Index.cshtml", 44, 23, true);

BeginContext("~/Views/Home/Index.cshtml", 67, 10, true);

WriteLiteral(">\n    <div");

EndContext("~/Views/Home/Index.cshtml", 67, 10, true);

BeginContext("~/Views/Home/Index.cshtml", 77, 54, true);

WriteLiteral(" class=\"row justify-content-center align-items-center\"");

EndContext("~/Views/Home/Index.cshtml", 77, 54, true);

BeginContext("~/Views/Home/Index.cshtml", 131, 25, true);

WriteLiteral(" style=\"min-height:70vh;\"");

EndContext("~/Views/Home/Index.cshtml", 131, 25, true);

BeginContext("~/Views/Home/Index.cshtml", 156, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Home/Index.cshtml", 156, 14, true);

BeginContext("~/Views/Home/Index.cshtml", 170, 17, true);

WriteLiteral(" class=\"col-lg-6\"");

EndContext("~/Views/Home/Index.cshtml", 170, 17, true);

BeginContext("~/Views/Home/Index.cshtml", 187, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Home/Index.cshtml", 187, 18, true);

BeginContext("~/Views/Home/Index.cshtml", 205, 36, true);

WriteLiteral(" class=\"card shadow-sm border-0 p-4\"");

EndContext("~/Views/Home/Index.cshtml", 205, 36, true);

BeginContext("~/Views/Home/Index.cshtml", 241, 22, true);

WriteLiteral(">\n                <div");

EndContext("~/Views/Home/Index.cshtml", 241, 22, true);

BeginContext("~/Views/Home/Index.cshtml", 263, 30, true);

WriteLiteral(" class=\"card-body text-center\"");

EndContext("~/Views/Home/Index.cshtml", 263, 30, true);

BeginContext("~/Views/Home/Index.cshtml", 293, 25, true);

WriteLiteral(">\n                    <h1");

EndContext("~/Views/Home/Index.cshtml", 293, 25, true);

BeginContext("~/Views/Home/Index.cshtml", 318, 33, true);

WriteLiteral(" class=\"display-4 mb-2 text-dark\"");

EndContext("~/Views/Home/Index.cshtml", 318, 33, true);

BeginContext("~/Views/Home/Index.cshtml", 351, 37, true);

WriteLiteral(">FinTrack</h1>\n                    <p");

EndContext("~/Views/Home/Index.cshtml", 351, 37, true);

BeginContext("~/Views/Home/Index.cshtml", 388, 29, true);

WriteLiteral(" class=\"fs-5 text-muted mb-3\"");

EndContext("~/Views/Home/Index.cshtml", 388, 29, true);

BeginContext("~/Views/Home/Index.cshtml", 417, 83, true);

WriteLiteral(">Your modern government finance service workflow portal.</p>\n                    " +
"<p");

EndContext("~/Views/Home/Index.cshtml", 417, 83, true);

BeginContext("~/Views/Home/Index.cshtml", 500, 40, true);

WriteLiteral(" class=\"fw-semibold mb-4 text-secondary\"");

EndContext("~/Views/Home/Index.cshtml", 500, 40, true);

BeginContext("~/Views/Home/Index.cshtml", 540, 76, true);

WriteLiteral(">Sign in to continue or register a new account.</p>\n                    <div");

EndContext("~/Views/Home/Index.cshtml", 540, 76, true);

BeginContext("~/Views/Home/Index.cshtml", 616, 21, true);

WriteLiteral(" class=\"d-grid gap-2\"");

EndContext("~/Views/Home/Index.cshtml", 616, 21, true);

BeginContext("~/Views/Home/Index.cshtml", 637, 28, true);

WriteLiteral(">\n                        <a");

EndContext("~/Views/Home/Index.cshtml", 637, 28, true);

BeginContext("~/Views/Home/Index.cshtml", 665, 31, true);

WriteLiteral(" class=\"btn btn-primary btn-lg\"");

EndContext("~/Views/Home/Index.cshtml", 665, 31, true);

WriteAttribute("href", Tuple.Create(" href=\"", 696), Tuple.Create("\"", 734)
            
            #line 13 "C:\projects\SOEEApp-main\SOEEApp\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 703), Tuple.Create<System.Object, System.Int32>(Url.Action("Login", "Account")
            
            #line default
            #line hidden
, 703), false)
);

BeginContext("~/Views/Home/Index.cshtml", 735, 37, true);

WriteLiteral(">Login</a>\n                        <a");

EndContext("~/Views/Home/Index.cshtml", 735, 37, true);

BeginContext("~/Views/Home/Index.cshtml", 772, 39, true);

WriteLiteral(" class=\"btn btn-outline-primary btn-lg\"");

EndContext("~/Views/Home/Index.cshtml", 772, 39, true);

WriteAttribute("href", Tuple.Create(" href=\"", 811), Tuple.Create("\"", 852)
            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Home\Index.cshtml"
, Tuple.Create(Tuple.Create("", 818), Tuple.Create<System.Object, System.Int32>(Url.Action("Register", "Account")
            
            #line default
            #line hidden
, 818), false)
);

BeginContext("~/Views/Home/Index.cshtml", 853, 116, true);

WriteLiteral(">Register</a>\n                    </div>\n                </div>\n            </div" +
">\n        </div>\n    </div>\n</div>\n");

EndContext("~/Views/Home/Index.cshtml", 853, 116, true);

        }
    }
}
