#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0241CBAA33D17E2AA02BBF5A505E55406041D6CE"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_SOEE_Create_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.ViewModels.SOEECreateViewModel> {
        
#line hidden
        
        public _Page_Views_SOEE_Create_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
  
    ViewBag.Title = "Create SOEE";
    var serviceTypes = ViewBag.ServiceTypes as List<SOEEApp.Models.ServiceType> ?? new List<SOEEApp.Models.ServiceType>();

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Create.cshtml", 216, 24, true);

WriteLiteral("\n\n<h2>Create SOEE</h2>\n\n");

EndContext("~/Views/SOEE/Create.cshtml", 216, 24, true);

            
            #line 10 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
 using (Html.BeginForm("Create", "SOEE", FormMethod.Post))
{
    
            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Create.cshtml", 306, 23, false);

            
            #line 12 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 306, 23, false);

            
            #line 12 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
                            
    
            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Create.cshtml", 335, 64, false);

            
            #line 13 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 335, 64, false);

            
            #line 13 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
                                                                     


            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Create.cshtml", 401, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/SOEE/Create.cshtml", 401, 8, true);

BeginContext("~/Views/SOEE/Create.cshtml", 409, 38, true);

WriteLiteral(" class=\"card card-body shadow-sm mb-3\"");

EndContext("~/Views/SOEE/Create.cshtml", 409, 38, true);

BeginContext("~/Views/SOEE/Create.cshtml", 447, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/SOEE/Create.cshtml", 447, 14, true);

BeginContext("~/Views/SOEE/Create.cshtml", 461, 79, true);

WriteLiteral(" class=\"d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3\"");

EndContext("~/Views/SOEE/Create.cshtml", 461, 79, true);

BeginContext("~/Views/SOEE/Create.cshtml", 540, 17, true);

WriteLiteral(">\n            <h4");

EndContext("~/Views/SOEE/Create.cshtml", 540, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 557, 13, true);

WriteLiteral(" class=\"mb-0\"");

EndContext("~/Views/SOEE/Create.cshtml", 557, 13, true);

BeginContext("~/Views/SOEE/Create.cshtml", 570, 40, true);

WriteLiteral(">Header Details</h4>\n            <button");

EndContext("~/Views/SOEE/Create.cshtml", 570, 40, true);

BeginContext("~/Views/SOEE/Create.cshtml", 610, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/SOEE/Create.cshtml", 610, 14, true);

BeginContext("~/Views/SOEE/Create.cshtml", 624, 18, true);

WriteLiteral(" id=\"loadPrevious\"");

EndContext("~/Views/SOEE/Create.cshtml", 624, 18, true);

BeginContext("~/Views/SOEE/Create.cshtml", 642, 34, true);

WriteLiteral(" class=\"btn btn-outline-secondary\"");

EndContext("~/Views/SOEE/Create.cshtml", 642, 34, true);

BeginContext("~/Views/SOEE/Create.cshtml", 676, 66, true);

WriteLiteral(">Autofill From Previous SOEE</button>\n        </div>\n\n        <div");

EndContext("~/Views/SOEE/Create.cshtml", 676, 66, true);

BeginContext("~/Views/SOEE/Create.cshtml", 742, 25, true);

WriteLiteral(" class=\"alert alert-info\"");

EndContext("~/Views/SOEE/Create.cshtml", 742, 25, true);

BeginContext("~/Views/SOEE/Create.cshtml", 767, 39, true);

WriteLiteral(">\n            Previous SOEE ID: <strong");

EndContext("~/Views/SOEE/Create.cshtml", 767, 39, true);

BeginContext("~/Views/SOEE/Create.cshtml", 806, 23, true);

WriteLiteral(" id=\"previousSoeeLabel\"");

EndContext("~/Views/SOEE/Create.cshtml", 806, 23, true);

BeginContext("~/Views/SOEE/Create.cshtml", 829, 1, true);

WriteLiteral(">");

EndContext("~/Views/SOEE/Create.cshtml", 829, 1, true);

BeginContext("~/Views/SOEE/Create.cshtml", 832, 73, false);

            
            #line 22 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
                                                         Write(Model.PrevSOEEID.HasValue ? Model.PrevSOEEID.ToString() : "Not available");

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 832, 73, false);

BeginContext("~/Views/SOEE/Create.cshtml", 906, 61, true);

WriteLiteral("</strong>\n            |\n            Previous Balance: <strong");

EndContext("~/Views/SOEE/Create.cshtml", 906, 61, true);

BeginContext("~/Views/SOEE/Create.cshtml", 967, 26, true);

WriteLiteral(" id=\"previousBalanceLabel\"");

EndContext("~/Views/SOEE/Create.cshtml", 967, 26, true);

BeginContext("~/Views/SOEE/Create.cshtml", 993, 1, true);

WriteLiteral(">");

EndContext("~/Views/SOEE/Create.cshtml", 993, 1, true);

BeginContext("~/Views/SOEE/Create.cshtml", 995, 40, false);

            
            #line 24 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
                                                           Write(Model.PreviousSOEEBalance.ToString("N2"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 995, 40, false);

BeginContext("~/Views/SOEE/Create.cshtml", 1035, 26, true);

WriteLiteral("</strong>\n        </div>\n\n");

EndContext("~/Views/SOEE/Create.cshtml", 1035, 26, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1061, 8, true);

WriteLiteral("        ");

EndContext("~/Views/SOEE/Create.cshtml", 1061, 8, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1070, 60, false);

            
            #line 27 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
   Write(Html.HiddenFor(m => m.PrevSOEEID, new { id = "PrevSOEEID" }));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 1070, 60, false);

BeginContext("~/Views/SOEE/Create.cshtml", 1130, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Create.cshtml", 1130, 1, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1131, 8, true);

WriteLiteral("        ");

EndContext("~/Views/SOEE/Create.cshtml", 1131, 8, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1140, 78, false);

            
            #line 28 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
   Write(Html.HiddenFor(m => m.PreviousSOEEBalance, new { id = "PreviousSOEEBalance" }));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 1140, 78, false);

BeginContext("~/Views/SOEE/Create.cshtml", 1218, 14, true);

WriteLiteral("\n\n        <div");

EndContext("~/Views/SOEE/Create.cshtml", 1218, 14, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1232, 16, true);

WriteLiteral(" class=\"row g-3\"");

EndContext("~/Views/SOEE/Create.cshtml", 1232, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1248, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/SOEE/Create.cshtml", 1248, 18, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1266, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/SOEE/Create.cshtml", 1266, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1283, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/SOEE/Create.cshtml", 1283, 2, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1285, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 1285, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1302, 31, false);

            
            #line 32 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.LabelFor(m => m.ProjectID));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 1302, 31, false);

BeginContext("~/Views/SOEE/Create.cshtml", 1333, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Create.cshtml", 1333, 1, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1334, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 1334, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1351, 143, false);

            
            #line 33 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.DropDownListFor(m => m.ProjectID, ViewBag.Projects as SelectList, "Select Project", new { @class = "form-control", id = "projectSelect" }));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 1351, 143, false);

BeginContext("~/Views/SOEE/Create.cshtml", 1494, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/SOEE/Create.cshtml", 1494, 36, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1530, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/SOEE/Create.cshtml", 1530, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1547, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/SOEE/Create.cshtml", 1547, 2, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1549, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 1549, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1566, 32, false);

            
            #line 36 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.LabelFor(m => m.CustomerID));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 1566, 32, false);

BeginContext("~/Views/SOEE/Create.cshtml", 1598, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Create.cshtml", 1598, 1, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1599, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 1599, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1616, 124, false);

            
            #line 37 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.DropDownListFor(m => m.CustomerID, ViewBag.Customers as SelectList, "Select Customer", new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 1616, 124, false);

BeginContext("~/Views/SOEE/Create.cshtml", 1740, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/SOEE/Create.cshtml", 1740, 36, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1776, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/SOEE/Create.cshtml", 1776, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1793, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/SOEE/Create.cshtml", 1793, 2, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1795, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 1795, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1812, 33, false);

            
            #line 40 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.LabelFor(m => m.ReferenceNo));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 1812, 33, false);

BeginContext("~/Views/SOEE/Create.cshtml", 1845, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Create.cshtml", 1845, 1, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1846, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 1846, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1863, 88, false);

            
            #line 41 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.TextBoxFor(m => m.ReferenceNo, new { @class = "form-control", id = "ReferenceNo" }));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 1863, 88, false);

BeginContext("~/Views/SOEE/Create.cshtml", 1951, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/SOEE/Create.cshtml", 1951, 36, true);

BeginContext("~/Views/SOEE/Create.cshtml", 1987, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/SOEE/Create.cshtml", 1987, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2004, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/SOEE/Create.cshtml", 2004, 2, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2006, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 2006, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2023, 28, false);

            
            #line 44 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.LabelFor(m => m.MarkTo));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 2023, 28, false);

BeginContext("~/Views/SOEE/Create.cshtml", 2051, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Create.cshtml", 2051, 1, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2052, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 2052, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2069, 78, false);

            
            #line 45 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.TextBoxFor(m => m.MarkTo, new { @class = "form-control", id = "MarkTo" }));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 2069, 78, false);

BeginContext("~/Views/SOEE/Create.cshtml", 2147, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/SOEE/Create.cshtml", 2147, 36, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2183, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/SOEE/Create.cshtml", 2183, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2200, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/SOEE/Create.cshtml", 2200, 2, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2202, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 2202, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2219, 29, false);

            
            #line 48 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.LabelFor(m => m.Subject));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 2219, 29, false);

BeginContext("~/Views/SOEE/Create.cshtml", 2248, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Create.cshtml", 2248, 1, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2249, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 2249, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2266, 80, false);

            
            #line 49 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.TextBoxFor(m => m.Subject, new { @class = "form-control", id = "Subject" }));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 2266, 80, false);

BeginContext("~/Views/SOEE/Create.cshtml", 2346, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/SOEE/Create.cshtml", 2346, 36, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2382, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/SOEE/Create.cshtml", 2382, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2399, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/SOEE/Create.cshtml", 2399, 2, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2401, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 2401, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2418, 31, false);

            
            #line 52 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.LabelFor(m => m.Reference));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 2418, 31, false);

BeginContext("~/Views/SOEE/Create.cshtml", 2449, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Create.cshtml", 2449, 1, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2450, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 2450, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2467, 84, false);

            
            #line 53 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.TextBoxFor(m => m.Reference, new { @class = "form-control", id = "Reference" }));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 2467, 84, false);

BeginContext("~/Views/SOEE/Create.cshtml", 2551, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/SOEE/Create.cshtml", 2551, 36, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2587, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/SOEE/Create.cshtml", 2587, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2604, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/SOEE/Create.cshtml", 2604, 2, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2606, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 2606, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2623, 55, false);

            
            #line 56 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.LabelFor(m => m.SOEERaiseDate, "SOEE Raised Date"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 2623, 55, false);

BeginContext("~/Views/SOEE/Create.cshtml", 2678, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Create.cshtml", 2678, 1, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2679, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 2679, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2696, 103, false);

            
            #line 57 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.TextBoxFor(m => m.SOEERaiseDate, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" }));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 2696, 103, false);

BeginContext("~/Views/SOEE/Create.cshtml", 2799, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/SOEE/Create.cshtml", 2799, 36, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2835, 17, true);

WriteLiteral(" class=\"col-md-8\"");

EndContext("~/Views/SOEE/Create.cshtml", 2835, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2852, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/SOEE/Create.cshtml", 2852, 2, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2854, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 2854, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2871, 51, false);

            
            #line 60 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.LabelFor(m => m.Content, "Description / Note"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 2871, 51, false);

BeginContext("~/Views/SOEE/Create.cshtml", 2922, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Create.cshtml", 2922, 1, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2923, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 2923, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 2940, 88, false);

            
            #line 61 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
           Write(Html.TextAreaFor(m => m.Content, 3, 20, new { @class = "form-control", id = "Content" }));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 2940, 88, false);

BeginContext("~/Views/SOEE/Create.cshtml", 3028, 46, true);

WriteLiteral("\n            </div>\n        </div>\n    </div>\n");

EndContext("~/Views/SOEE/Create.cshtml", 3028, 46, true);

            
            #line 65 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"


            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Create.cshtml", 3075, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/SOEE/Create.cshtml", 3075, 8, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3083, 38, true);

WriteLiteral(" class=\"card card-body shadow-sm mb-3\"");

EndContext("~/Views/SOEE/Create.cshtml", 3083, 38, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3121, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/SOEE/Create.cshtml", 3121, 14, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3135, 63, true);

WriteLiteral(" class=\"d-flex justify-content-between align-items-center mb-3\"");

EndContext("~/Views/SOEE/Create.cshtml", 3135, 63, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3198, 17, true);

WriteLiteral(">\n            <h4");

EndContext("~/Views/SOEE/Create.cshtml", 3198, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3215, 13, true);

WriteLiteral(" class=\"mb-0\"");

EndContext("~/Views/SOEE/Create.cshtml", 3215, 13, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3228, 45, true);

WriteLiteral(">Service Entry Items</h4>\n            <button");

EndContext("~/Views/SOEE/Create.cshtml", 3228, 45, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3273, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/SOEE/Create.cshtml", 3273, 14, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3287, 12, true);

WriteLiteral(" id=\"addRow\"");

EndContext("~/Views/SOEE/Create.cshtml", 3287, 12, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3299, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/SOEE/Create.cshtml", 3299, 24, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3323, 55, true);

WriteLiteral(">Add Service Item</button>\n        </div>\n\n        <div");

EndContext("~/Views/SOEE/Create.cshtml", 3323, 55, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3378, 25, true);

WriteLiteral(" class=\"table-responsive\"");

EndContext("~/Views/SOEE/Create.cshtml", 3378, 25, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3403, 20, true);

WriteLiteral(">\n            <table");

EndContext("~/Views/SOEE/Create.cshtml", 3403, 20, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3423, 29, true);

WriteLiteral(" class=\"table table-bordered\"");

EndContext("~/Views/SOEE/Create.cshtml", 3423, 29, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3452, 18, true);

WriteLiteral(" id=\"serviceTable\"");

EndContext("~/Views/SOEE/Create.cshtml", 3452, 18, true);

BeginContext("~/Views/SOEE/Create.cshtml", 3470, 586, true);

WriteLiteral(@">
                <thead>
                    <tr>
                        <th>Description of Work</th>
                        <th>Service Type</th>
                        <th>Unit</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>Subtotal</th>
                        <th>Service Charge</th>
                        <th>CGST</th>
                        <th>SGST</th>
                        <th>Total</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody");

EndContext("~/Views/SOEE/Create.cshtml", 3470, 586, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4056, 17, true);

WriteLiteral(" id=\"serviceBody\"");

EndContext("~/Views/SOEE/Create.cshtml", 4056, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4073, 57, true);

WriteLiteral("></tbody>\n            </table>\n        </div>\n    </div>\n");

EndContext("~/Views/SOEE/Create.cshtml", 4073, 57, true);

            
            #line 93 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"


            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Create.cshtml", 4131, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/SOEE/Create.cshtml", 4131, 8, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4139, 38, true);

WriteLiteral(" class=\"card card-body shadow-sm mb-3\"");

EndContext("~/Views/SOEE/Create.cshtml", 4139, 38, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4177, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/SOEE/Create.cshtml", 4177, 14, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4191, 16, true);

WriteLiteral(" class=\"row g-3\"");

EndContext("~/Views/SOEE/Create.cshtml", 4191, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4207, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/SOEE/Create.cshtml", 4207, 18, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4225, 17, true);

WriteLiteral(" class=\"col-md-3\"");

EndContext("~/Views/SOEE/Create.cshtml", 4225, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4242, 67, true);

WriteLiteral(">\n                <label>Total Basic</label>\n                <input");

EndContext("~/Views/SOEE/Create.cshtml", 4242, 67, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4309, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/SOEE/Create.cshtml", 4309, 12, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4321, 22, true);

WriteLiteral(" id=\"TotalBasicAmount\"");

EndContext("~/Views/SOEE/Create.cshtml", 4321, 22, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4343, 21, true);

WriteLiteral(" class=\"form-control\"");

EndContext("~/Views/SOEE/Create.cshtml", 4343, 21, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4364, 9, true);

WriteLiteral(" readonly");

EndContext("~/Views/SOEE/Create.cshtml", 4364, 9, true);

WriteAttribute("value", Tuple.Create(" value=\"", 4373), Tuple.Create("\"", 4421)
            
            #line 98 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
              , Tuple.Create(Tuple.Create("", 4381), Tuple.Create<System.Object, System.Int32>(Model.TotalBasicAmount.ToString("0.00")
            
            #line default
            #line hidden
, 4381), false)
);

BeginContext("~/Views/SOEE/Create.cshtml", 4422, 39, true);

WriteLiteral(" />\n            </div>\n            <div");

EndContext("~/Views/SOEE/Create.cshtml", 4422, 39, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4461, 17, true);

WriteLiteral(" class=\"col-md-3\"");

EndContext("~/Views/SOEE/Create.cshtml", 4461, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4478, 77, true);

WriteLiteral(">\n                <label>Total Service Charges</label>\n                <input");

EndContext("~/Views/SOEE/Create.cshtml", 4478, 77, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4555, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/SOEE/Create.cshtml", 4555, 12, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4567, 24, true);

WriteLiteral(" id=\"TotalServiceCharge\"");

EndContext("~/Views/SOEE/Create.cshtml", 4567, 24, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4591, 21, true);

WriteLiteral(" class=\"form-control\"");

EndContext("~/Views/SOEE/Create.cshtml", 4591, 21, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4612, 9, true);

WriteLiteral(" readonly");

EndContext("~/Views/SOEE/Create.cshtml", 4612, 9, true);

WriteAttribute("value", Tuple.Create(" value=\"", 4621), Tuple.Create("\"", 4671)
            
            #line 102 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
                , Tuple.Create(Tuple.Create("", 4629), Tuple.Create<System.Object, System.Int32>(Model.TotalServiceCharge.ToString("0.00")
            
            #line default
            #line hidden
, 4629), false)
);

BeginContext("~/Views/SOEE/Create.cshtml", 4672, 39, true);

WriteLiteral(" />\n            </div>\n            <div");

EndContext("~/Views/SOEE/Create.cshtml", 4672, 39, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4711, 17, true);

WriteLiteral(" class=\"col-md-3\"");

EndContext("~/Views/SOEE/Create.cshtml", 4711, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4728, 72, true);

WriteLiteral(">\n                <label>Total Tax Amount</label>\n                <input");

EndContext("~/Views/SOEE/Create.cshtml", 4728, 72, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4800, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/SOEE/Create.cshtml", 4800, 12, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4812, 20, true);

WriteLiteral(" id=\"TotalTaxAmount\"");

EndContext("~/Views/SOEE/Create.cshtml", 4812, 20, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4832, 21, true);

WriteLiteral(" class=\"form-control\"");

EndContext("~/Views/SOEE/Create.cshtml", 4832, 21, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4853, 9, true);

WriteLiteral(" readonly");

EndContext("~/Views/SOEE/Create.cshtml", 4853, 9, true);

WriteAttribute("value", Tuple.Create(" value=\"", 4862), Tuple.Create("\"", 4908)
            
            #line 106 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
            , Tuple.Create(Tuple.Create("", 4870), Tuple.Create<System.Object, System.Int32>(Model.TotalTaxAmount.ToString("0.00")
            
            #line default
            #line hidden
, 4870), false)
);

BeginContext("~/Views/SOEE/Create.cshtml", 4909, 39, true);

WriteLiteral(" />\n            </div>\n            <div");

EndContext("~/Views/SOEE/Create.cshtml", 4909, 39, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4948, 17, true);

WriteLiteral(" class=\"col-md-3\"");

EndContext("~/Views/SOEE/Create.cshtml", 4948, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 4965, 67, true);

WriteLiteral(">\n                <label>Grand Total</label>\n                <input");

EndContext("~/Views/SOEE/Create.cshtml", 4965, 67, true);

BeginContext("~/Views/SOEE/Create.cshtml", 5032, 12, true);

WriteLiteral(" type=\"text\"");

EndContext("~/Views/SOEE/Create.cshtml", 5032, 12, true);

BeginContext("~/Views/SOEE/Create.cshtml", 5044, 16, true);

WriteLiteral(" id=\"GrandTotal\"");

EndContext("~/Views/SOEE/Create.cshtml", 5044, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 5060, 21, true);

WriteLiteral(" class=\"form-control\"");

EndContext("~/Views/SOEE/Create.cshtml", 5060, 21, true);

BeginContext("~/Views/SOEE/Create.cshtml", 5081, 9, true);

WriteLiteral(" readonly");

EndContext("~/Views/SOEE/Create.cshtml", 5081, 9, true);

WriteAttribute("value", Tuple.Create(" value=\"", 5090), Tuple.Create("\"", 5132)
            
            #line 110 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
        , Tuple.Create(Tuple.Create("", 5098), Tuple.Create<System.Object, System.Int32>(Model.GrandTotal.ToString("0.00")
            
            #line default
            #line hidden
, 5098), false)
);

BeginContext("~/Views/SOEE/Create.cshtml", 5133, 49, true);

WriteLiteral(" />\n            </div>\n        </div>\n    </div>\n");

EndContext("~/Views/SOEE/Create.cshtml", 5133, 49, true);

            
            #line 114 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"


            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Create.cshtml", 5183, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/SOEE/Create.cshtml", 5183, 8, true);

BeginContext("~/Views/SOEE/Create.cshtml", 5191, 21, true);

WriteLiteral(" class=\"d-flex gap-2\"");

EndContext("~/Views/SOEE/Create.cshtml", 5191, 21, true);

BeginContext("~/Views/SOEE/Create.cshtml", 5212, 17, true);

WriteLiteral(">\n        <button");

EndContext("~/Views/SOEE/Create.cshtml", 5212, 17, true);

BeginContext("~/Views/SOEE/Create.cshtml", 5229, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/SOEE/Create.cshtml", 5229, 14, true);

BeginContext("~/Views/SOEE/Create.cshtml", 5243, 24, true);

WriteLiteral(" class=\"btn btn-success\"");

EndContext("~/Views/SOEE/Create.cshtml", 5243, 24, true);

BeginContext("~/Views/SOEE/Create.cshtml", 5267, 31, true);

WriteLiteral(">Save Draft</button>\n        <a");

EndContext("~/Views/SOEE/Create.cshtml", 5267, 31, true);

WriteAttribute("href", Tuple.Create(" href=\"", 5298), Tuple.Create("\"", 5325)
            
            #line 117 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
, Tuple.Create(Tuple.Create("", 5305), Tuple.Create<System.Object, System.Int32>(Url.Action("Index")
            
            #line default
            #line hidden
, 5305), false)
);

BeginContext("~/Views/SOEE/Create.cshtml", 5326, 34, true);

WriteLiteral(" class=\"btn btn-outline-secondary\"");

EndContext("~/Views/SOEE/Create.cshtml", 5326, 34, true);

BeginContext("~/Views/SOEE/Create.cshtml", 5360, 23, true);

WriteLiteral(">Cancel</a>\n    </div>\n");

EndContext("~/Views/SOEE/Create.cshtml", 5360, 23, true);

            
            #line 119 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Create.cshtml", 5385, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Create.cshtml", 5385, 1, true);

DefineSection("Scripts", () => {

BeginContext("~/Views/SOEE/Create.cshtml", 5404, 149, true);

WriteLiteral("\n    <script>\n        var rowIndex = 0;\n\n        function getServiceOptions(selec" +
"tedId) {\n            var html = \'<option value=\"\">Select</option>\';\n");

EndContext("~/Views/SOEE/Create.cshtml", 5404, 149, true);

            
            #line 127 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
            
            
            #line default
            #line hidden
            
            #line 127 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
             foreach (var s in serviceTypes)
            {

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Create.cshtml", 5612, 16, true);

WriteLiteral("                ");

EndContext("~/Views/SOEE/Create.cshtml", 5612, 16, true);

BeginContext("~/Views/SOEE/Create.cshtml", 5630, 24, true);

WriteLiteral("html += \'<option value=\"");

EndContext("~/Views/SOEE/Create.cshtml", 5630, 24, true);

BeginContext("~/Views/SOEE/Create.cshtml", 5655, 15, false);

            
            #line 129 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
                                     Write(s.ServiceTypeID);

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 5655, 15, false);

BeginContext("~/Views/SOEE/Create.cshtml", 5670, 2, true);

WriteLiteral("\">");

EndContext("~/Views/SOEE/Create.cshtml", 5670, 2, true);

BeginContext("~/Views/SOEE/Create.cshtml", 5673, 13, false);

            
            #line 129 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
                                                       Write(s.ServiceName);

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 5673, 13, false);

BeginContext("~/Views/SOEE/Create.cshtml", 5686, 12, true);

WriteLiteral("</option>\';\n");

EndContext("~/Views/SOEE/Create.cshtml", 5686, 12, true);

            
            #line 130 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
            }

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Create.cshtml", 5712, 3762, true);

WriteLiteral("            return html.replace(\'value=\"\' + selectedId + \'\"\', \'value=\"\' + selecte" +
"dId + \'\" selected=\"selected\"\');\n        }\n\n        function buildRow(data) {\n   " +
"         data = data || {};\n            var row = \'<tr>\' +\n                \'<td>" +
"<input type=\"hidden\" name=\"Items[\' + rowIndex + \'].SOEEItemID\" value=\"0\" />\' +\n " +
"               \'<input type=\"hidden\" name=\"Items[\' + rowIndex + \'].IsDeleted\" cl" +
"ass=\"isDeleted\" value=\"false\" />\' +\n                \'<input type=\"text\" name=\"It" +
"ems[\' + rowIndex + \'].DescriptionOfWork\" class=\"form-control description\" value=" +
"\"\' + (data.descriptionOfWork || \'\') + \'\" required /></td>\' +\n                \'<t" +
"d><select name=\"Items[\' + rowIndex + \'].ServiceTypeID\" class=\"form-control servi" +
"ceTypeDropdown\">\' + getServiceOptions(data.serviceTypeID || \'\') + \'</select></td" +
">\' +\n                \'<td><input type=\"number\" step=\"0.01\" name=\"Items[\' + rowIn" +
"dex + \'].Unit\" class=\"form-control unit\" value=\"\' + (data.unit || \'\') + \'\" /></t" +
"d>\' +\n                \'<td><input type=\"number\" step=\"0.01\" name=\"Items[\' + rowI" +
"ndex + \'].Quantity\" class=\"form-control qty\" value=\"\' + (data.quantity || \'\') + " +
"\'\" /></td>\' +\n                \'<td><input type=\"number\" step=\"0.01\" name=\"Items[" +
"\' + rowIndex + \'].UnitPrice\" class=\"form-control unitPrice\" value=\"\' + (data.uni" +
"tPrice || \'\') + \'\" /></td>\' +\n                \'<td><input type=\"text\" name=\"Item" +
"s[\' + rowIndex + \'].SubTotal\" class=\"form-control subTotal\" readonly /></td>\' +\n" +
"                \'<td><input type=\"text\" name=\"Items[\' + rowIndex + \'].ServiceCha" +
"rge\" class=\"form-control serviceCharge\" readonly /></td>\' +\n                \'<td" +
"><input type=\"text\" name=\"Items[\' + rowIndex + \'].CGST\" class=\"form-control cgst" +
"\" readonly /></td>\' +\n                \'<td><input type=\"text\" name=\"Items[\' + ro" +
"wIndex + \'].SGST\" class=\"form-control sgst\" readonly /></td>\' +\n                " +
"\'<td><input type=\"text\" name=\"Items[\' + rowIndex + \'].Total\" class=\"form-control" +
" total\" readonly /></td>\' +\n                \'<td><button type=\"button\" class=\"bt" +
"n btn-outline-danger removeRow\">X</button></td>\' +\n                \'</tr>\';\n\n   " +
"         rowIndex += 1;\n            return row;\n        }\n\n        function upda" +
"teTotals() {\n            var basic = 0;\n            var service = 0;\n           " +
" var tax = 0;\n            var total = 0;\n\n            $(\'#serviceBody tr\').each(" +
"function () {\n                if ($(this).find(\'.isDeleted\').val() === \'true\') {" +
"\n                    return;\n                }\n\n                basic += parseFl" +
"oat($(this).find(\'.subTotal\').val()) || 0;\n                service += parseFloat" +
"($(this).find(\'.serviceCharge\').val()) || 0;\n                tax += (parseFloat(" +
"$(this).find(\'.cgst\').val()) || 0) + (parseFloat($(this).find(\'.sgst\').val()) ||" +
" 0);\n                total += parseFloat($(this).find(\'.total\').val()) || 0;\n   " +
"         });\n\n            $(\'#TotalBasicAmount\').val(basic.toFixed(2));\n        " +
"    $(\'#TotalServiceCharge\').val(service.toFixed(2));\n            $(\'#TotalTaxAm" +
"ount\').val(tax.toFixed(2));\n            $(\'#GrandTotal\').val(total.toFixed(2));\n" +
"        }\n\n        function calculateRow(row) {\n            var unit = parseFloa" +
"t(row.find(\'.unit\').val()) || 0;\n            var qty = parseFloat(row.find(\'.qty" +
"\').val()) || 0;\n            var unitPrice = parseFloat(row.find(\'.unitPrice\').va" +
"l()) || 0;\n            var subtotal = unit * qty * unitPrice;\n            row.fi" +
"nd(\'.subTotal\').val(subtotal.toFixed(2));\n\n            var serviceTypeId = row.f" +
"ind(\'.serviceTypeDropdown\').val();\n            var projectId = $(\'#projectSelect" +
"\').val();\n\n            if (!serviceTypeId || !projectId || subtotal <= 0) {\n    " +
"            row.find(\'.serviceCharge, .cgst, .sgst, .total\').val(\'\');\n          " +
"      updateTotals();\n                return;\n            }\n\n            $.post(" +
"\'");

EndContext("~/Views/SOEE/Create.cshtml", 5712, 3762, true);

BeginContext("~/Views/SOEE/Create.cshtml", 9475, 45, false);

            
            #line 195 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
               Write(Url.Action("GetServiceChargePercent", "SOEE"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 9475, 45, false);

BeginContext("~/Views/SOEE/Create.cshtml", 9520, 1204, true);

WriteLiteral(@"', {
                serviceTypeId: serviceTypeId,
                subtotal: subtotal,
                projectId: projectId
            }).done(function (data) {
                var percent = data.percentage || 0;
                var serviceCharge = subtotal * percent / 100;
                var taxable = subtotal + serviceCharge;
                var cgst = taxable * 0.09;
                var sgst = taxable * 0.09;
                var total = taxable + cgst + sgst;

                row.find('.serviceCharge').val(serviceCharge.toFixed(2));
                row.find('.cgst').val(cgst.toFixed(2));
                row.find('.sgst').val(sgst.toFixed(2));
                row.find('.total').val(total.toFixed(2));
                updateTotals();
            });
        }

        function bindRowEvents() {
            $(document).off('input change', '.unit, .qty, .unitPrice, .serviceTypeDropdown');
            $(document).on('input change', '.unit, .qty, .unitPrice, .serviceTypeDropdown', function () {
                calculateRow($(this).closest('tr'));
            });
        }

        function loadServicesForProject() {
            var pid = $('#projectSelect').val();
            $.getJSON('");

EndContext("~/Views/SOEE/Create.cshtml", 9520, 1204, true);

BeginContext("~/Views/SOEE/Create.cshtml", 10725, 43, false);

            
            #line 224 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
                  Write(Url.Action("GetServicesForProject", "SOEE"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 10725, 43, false);

BeginContext("~/Views/SOEE/Create.cshtml", 10768, 1209, true);

WriteLiteral(@"', { projectId: pid }, function (data) {
                $('.serviceTypeDropdown').each(function () {
                    var ddl = $(this);
                    var current = ddl.val();
                    ddl.empty().append('<option value="""">Select</option>');
                    $.each(data, function (_, item) {
                        ddl.append($('<option/>', { value: item.ServiceTypeID, text: item.ServiceName }));
                    });
                    ddl.val(current);
                });
            });
        }

        $('#addRow').on('click', function () {
            $('#serviceBody').append(buildRow());
        });

        $(document).on('click', '.removeRow', function () {
            $(this).closest('tr').find('.isDeleted').val('true');
            $(this).closest('tr').remove();
            updateTotals();
        });

        $('#projectSelect').on('change', function () {
            loadServicesForProject();
        });

        $('#loadPrevious').on('click', function () {
            var projectId = $('#projectSelect').val();
            if (!projectId) {
                alert('Select a project first.');
                return;
            }

            $.getJSON('");

EndContext("~/Views/SOEE/Create.cshtml", 10768, 1209, true);

BeginContext("~/Views/SOEE/Create.cshtml", 11978, 41, false);

            
            #line 258 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Create.cshtml"
                  Write(Url.Action("GetPreviousSOEEData", "SOEE"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Create.cshtml", 11978, 41, false);

BeginContext("~/Views/SOEE/Create.cshtml", 12019, 1185, true);

WriteLiteral(@"', { projectId: projectId }, function (data) {
                if (!data.found) {
                    alert('No previous SOEE found for this project.');
                    return;
                }

                $('#PrevSOEEID').val(data.soeeId);
                $('#PreviousSOEEBalance').val(data.previousBalance);
                $('#previousSoeeLabel').text(data.soeeId);
                $('#previousBalanceLabel').text(parseFloat(data.previousBalance).toFixed(2));
                $('#ReferenceNo').val(data.referenceNo);
                $('#Subject').val(data.subject);
                $('#Reference').val(data.reference);
                $('#Content').val(data.content);
                $('#MarkTo').val(data.markTo);

                $('#serviceBody').empty();
                $.each(data.items, function (_, item) {
                    $('#serviceBody').append(buildRow(item));
                });

                bindRowEvents();
                $('#serviceBody tr').each(function () { calculateRow($(this)); });
            });
        });

        $(function () {
            bindRowEvents();
            $('#serviceBody').append(buildRow());
        });
    </script>
");

EndContext("~/Views/SOEE/Create.cshtml", 12019, 1185, true);

});

        }
    }
}
