#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "ADFC29301F9548A07AB96E3B7256A90EFE289D2D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Projects_Create_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.Project> {
        
#line hidden
        
        public _Page_Views_Projects_Create_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"
  
    ViewBag.Title = "Create Project";

            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Create.cshtml", 73, 27, true);

WriteLiteral("\n\n<h2>Create Project</h2>\n\n");

EndContext("~/Views/Projects/Create.cshtml", 73, 27, true);

            
            #line 9 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Create.cshtml", 133, 23, false);

            
            #line 11 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Create.cshtml", 133, 23, false);

            
            #line 11 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"
                            


            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Create.cshtml", 158, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Projects/Create.cshtml", 158, 8, true);

BeginContext("~/Views/Projects/Create.cshtml", 166, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Projects/Create.cshtml", 166, 19, true);

BeginContext("~/Views/Projects/Create.cshtml", 185, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Projects/Create.cshtml", 185, 2, true);

BeginContext("~/Views/Projects/Create.cshtml", 187, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Projects/Create.cshtml", 187, 8, true);

BeginContext("~/Views/Projects/Create.cshtml", 196, 26, false);

            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"
   Write(Html.LabelFor(m => m.Name));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Create.cshtml", 196, 26, false);

BeginContext("~/Views/Projects/Create.cshtml", 222, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Projects/Create.cshtml", 222, 1, true);

BeginContext("~/Views/Projects/Create.cshtml", 223, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Projects/Create.cshtml", 223, 8, true);

BeginContext("~/Views/Projects/Create.cshtml", 232, 61, false);

            
            #line 15 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"
   Write(Html.TextBoxFor(m => m.Name, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Create.cshtml", 232, 61, false);

BeginContext("~/Views/Projects/Create.cshtml", 293, 12, true);

WriteLiteral("\n    </div>\n");

EndContext("~/Views/Projects/Create.cshtml", 293, 12, true);

            
            #line 17 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"


            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Create.cshtml", 306, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Projects/Create.cshtml", 306, 8, true);

BeginContext("~/Views/Projects/Create.cshtml", 314, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Projects/Create.cshtml", 314, 19, true);

BeginContext("~/Views/Projects/Create.cshtml", 333, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Projects/Create.cshtml", 333, 2, true);

BeginContext("~/Views/Projects/Create.cshtml", 335, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Projects/Create.cshtml", 335, 8, true);

BeginContext("~/Views/Projects/Create.cshtml", 344, 17, false);

            
            #line 19 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"
   Write(Html.Label("OIC"));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Create.cshtml", 344, 17, false);

BeginContext("~/Views/Projects/Create.cshtml", 361, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Projects/Create.cshtml", 361, 1, true);

BeginContext("~/Views/Projects/Create.cshtml", 362, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Projects/Create.cshtml", 362, 8, true);

BeginContext("~/Views/Projects/Create.cshtml", 371, 124, false);

            
            #line 20 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"
   Write(Html.DropDownListFor(model => model.OICUserId, (SelectList)ViewBag.OICUserId, "Select OIC", new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Create.cshtml", 371, 124, false);

BeginContext("~/Views/Projects/Create.cshtml", 495, 12, true);

WriteLiteral("\n    </div>\n");

EndContext("~/Views/Projects/Create.cshtml", 495, 12, true);

            
            #line 22 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"


            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Create.cshtml", 508, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Projects/Create.cshtml", 508, 8, true);

BeginContext("~/Views/Projects/Create.cshtml", 516, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Projects/Create.cshtml", 516, 19, true);

BeginContext("~/Views/Projects/Create.cshtml", 535, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Projects/Create.cshtml", 535, 2, true);

BeginContext("~/Views/Projects/Create.cshtml", 537, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Projects/Create.cshtml", 537, 8, true);

BeginContext("~/Views/Projects/Create.cshtml", 546, 33, false);

            
            #line 24 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"
   Write(Html.LabelFor(m => m.ProjectCost));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Create.cshtml", 546, 33, false);

BeginContext("~/Views/Projects/Create.cshtml", 579, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Projects/Create.cshtml", 579, 1, true);

BeginContext("~/Views/Projects/Create.cshtml", 580, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Projects/Create.cshtml", 580, 8, true);

BeginContext("~/Views/Projects/Create.cshtml", 589, 111, false);

            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"
   Write(Html.TextBoxFor(m => m.ProjectCost, new { @class = "form-control", type = "number", step = "0.01", min = "0" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Create.cshtml", 589, 111, false);

BeginContext("~/Views/Projects/Create.cshtml", 700, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Projects/Create.cshtml", 700, 1, true);

BeginContext("~/Views/Projects/Create.cshtml", 701, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Projects/Create.cshtml", 701, 8, true);

BeginContext("~/Views/Projects/Create.cshtml", 710, 81, false);

            
            #line 26 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"
   Write(Html.ValidationMessageFor(m => m.ProjectCost, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Create.cshtml", 710, 81, false);

BeginContext("~/Views/Projects/Create.cshtml", 791, 12, true);

WriteLiteral("\n    </div>\n");

EndContext("~/Views/Projects/Create.cshtml", 791, 12, true);

            
            #line 28 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"


            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Create.cshtml", 804, 11, true);

WriteLiteral("    <button");

EndContext("~/Views/Projects/Create.cshtml", 804, 11, true);

BeginContext("~/Views/Projects/Create.cshtml", 815, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Projects/Create.cshtml", 815, 14, true);

BeginContext("~/Views/Projects/Create.cshtml", 829, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/Projects/Create.cshtml", 829, 24, true);

BeginContext("~/Views/Projects/Create.cshtml", 853, 15, true);

WriteLiteral(">Save</button>\n");

EndContext("~/Views/Projects/Create.cshtml", 853, 15, true);

            
            #line 30 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Create.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
