#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "AA08BA46ED70CBBF4BA62B28CC03D6C8EAE200EC"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Account_Register_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.RegisterViewModel> {
        
#line hidden
        
        public _Page_Views_Account_Register_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 2 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
  
    ViewBag.Title = "Register";

            
            #line default
            #line hidden
BeginContext("~/Views/Account/Register.cshtml", 76, 6, true);

WriteLiteral("\n\n<div");

EndContext("~/Views/Account/Register.cshtml", 76, 6, true);

BeginContext("~/Views/Account/Register.cshtml", 82, 25, true);

WriteLiteral(" class=\"text-center mb-3\"");

EndContext("~/Views/Account/Register.cshtml", 82, 25, true);

BeginContext("~/Views/Account/Register.cshtml", 107, 36, true);

WriteLiteral(">\n    <h2>Create Account</h2>\n    <p");

EndContext("~/Views/Account/Register.cshtml", 107, 36, true);

BeginContext("~/Views/Account/Register.cshtml", 143, 19, true);

WriteLiteral(" class=\"text-muted\"");

EndContext("~/Views/Account/Register.cshtml", 143, 19, true);

BeginContext("~/Views/Account/Register.cshtml", 162, 42, true);

WriteLiteral(">Register to access FinTrack.</p>\n</div>\n\n");

EndContext("~/Views/Account/Register.cshtml", 162, 42, true);

            
            #line 11 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
 using (Html.BeginForm("Register", "Account", FormMethod.Post, new { role = "form" }))
{
    
            
            #line default
            #line hidden
BeginContext("~/Views/Account/Register.cshtml", 298, 23, false);

            
            #line 13 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 298, 23, false);

            
            #line 13 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
                            
    
            
            #line default
            #line hidden
BeginContext("~/Views/Account/Register.cshtml", 327, 58, false);

            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
Write(Html.ValidationSummary("", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 327, 58, false);

            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
                                                               

            
            #line default
            #line hidden
BeginContext("~/Views/Account/Register.cshtml", 386, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/Register.cshtml", 386, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 394, 13, true);

WriteLiteral(" class=\"mb-3\"");

EndContext("~/Views/Account/Register.cshtml", 394, 13, true);

BeginContext("~/Views/Account/Register.cshtml", 407, 1, true);

WriteLiteral(">");

EndContext("~/Views/Account/Register.cshtml", 407, 1, true);

BeginContext("~/Views/Account/Register.cshtml", 409, 26, false);

            
            #line 15 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
                 Write(Html.LabelFor(m => m.Name));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 409, 26, false);

BeginContext("~/Views/Account/Register.cshtml", 435, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/Register.cshtml", 435, 1, true);

BeginContext("~/Views/Account/Register.cshtml", 436, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/Register.cshtml", 436, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 445, 61, false);

            
            #line 16 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
   Write(Html.TextBoxFor(m => m.Name, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 445, 61, false);

BeginContext("~/Views/Account/Register.cshtml", 506, 12, true);

WriteLiteral("\n    </div>\n");

EndContext("~/Views/Account/Register.cshtml", 506, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 518, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/Register.cshtml", 518, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 526, 13, true);

WriteLiteral(" class=\"mb-3\"");

EndContext("~/Views/Account/Register.cshtml", 526, 13, true);

BeginContext("~/Views/Account/Register.cshtml", 539, 1, true);

WriteLiteral(">");

EndContext("~/Views/Account/Register.cshtml", 539, 1, true);

BeginContext("~/Views/Account/Register.cshtml", 541, 27, false);

            
            #line 18 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
                 Write(Html.LabelFor(m => m.Email));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 541, 27, false);

BeginContext("~/Views/Account/Register.cshtml", 568, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/Register.cshtml", 568, 1, true);

BeginContext("~/Views/Account/Register.cshtml", 569, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/Register.cshtml", 569, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 578, 62, false);

            
            #line 19 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
   Write(Html.TextBoxFor(m => m.Email, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 578, 62, false);

BeginContext("~/Views/Account/Register.cshtml", 640, 12, true);

WriteLiteral("\n    </div>\n");

EndContext("~/Views/Account/Register.cshtml", 640, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 652, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/Register.cshtml", 652, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 660, 13, true);

WriteLiteral(" class=\"mb-3\"");

EndContext("~/Views/Account/Register.cshtml", 660, 13, true);

BeginContext("~/Views/Account/Register.cshtml", 673, 1, true);

WriteLiteral(">");

EndContext("~/Views/Account/Register.cshtml", 673, 1, true);

BeginContext("~/Views/Account/Register.cshtml", 675, 30, false);

            
            #line 21 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
                 Write(Html.LabelFor(m => m.Password));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 675, 30, false);

BeginContext("~/Views/Account/Register.cshtml", 705, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/Register.cshtml", 705, 1, true);

BeginContext("~/Views/Account/Register.cshtml", 706, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/Register.cshtml", 706, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 715, 66, false);

            
            #line 22 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
   Write(Html.PasswordFor(m => m.Password, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 715, 66, false);

BeginContext("~/Views/Account/Register.cshtml", 781, 12, true);

WriteLiteral("\n    </div>\n");

EndContext("~/Views/Account/Register.cshtml", 781, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 793, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/Register.cshtml", 793, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 801, 13, true);

WriteLiteral(" class=\"mb-3\"");

EndContext("~/Views/Account/Register.cshtml", 801, 13, true);

BeginContext("~/Views/Account/Register.cshtml", 814, 1, true);

WriteLiteral(">");

EndContext("~/Views/Account/Register.cshtml", 814, 1, true);

BeginContext("~/Views/Account/Register.cshtml", 816, 37, false);

            
            #line 24 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
                 Write(Html.LabelFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 816, 37, false);

BeginContext("~/Views/Account/Register.cshtml", 853, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/Register.cshtml", 853, 1, true);

BeginContext("~/Views/Account/Register.cshtml", 854, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/Register.cshtml", 854, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 863, 73, false);

            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
   Write(Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 863, 73, false);

BeginContext("~/Views/Account/Register.cshtml", 936, 12, true);

WriteLiteral("\n    </div>\n");

EndContext("~/Views/Account/Register.cshtml", 936, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 948, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/Register.cshtml", 948, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 956, 13, true);

WriteLiteral(" class=\"mb-3\"");

EndContext("~/Views/Account/Register.cshtml", 956, 13, true);

BeginContext("~/Views/Account/Register.cshtml", 969, 1, true);

WriteLiteral(">");

EndContext("~/Views/Account/Register.cshtml", 969, 1, true);

BeginContext("~/Views/Account/Register.cshtml", 971, 26, false);

            
            #line 27 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
                 Write(Html.LabelFor(m => m.Role));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 971, 26, false);

BeginContext("~/Views/Account/Register.cshtml", 997, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/Register.cshtml", 997, 1, true);

BeginContext("~/Views/Account/Register.cshtml", 998, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/Register.cshtml", 998, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 1007, 196, false);

            
            #line 28 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
   Write(Html.DropDownListFor(m => m.Role,
            new SelectList(new[] { "OIC", "FinanceManager", "FinanceDirector", "Cashier", "Client" }),
            "Select Role", new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 1007, 196, false);

BeginContext("~/Views/Account/Register.cshtml", 1203, 12, true);

WriteLiteral("\n    </div>\n");

EndContext("~/Views/Account/Register.cshtml", 1203, 12, true);

BeginContext("~/Views/Account/Register.cshtml", 1215, 11, true);

WriteLiteral("    <button");

EndContext("~/Views/Account/Register.cshtml", 1215, 11, true);

BeginContext("~/Views/Account/Register.cshtml", 1226, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Account/Register.cshtml", 1226, 14, true);

BeginContext("~/Views/Account/Register.cshtml", 1240, 30, true);

WriteLiteral(" class=\"btn btn-primary w-100\"");

EndContext("~/Views/Account/Register.cshtml", 1240, 30, true);

BeginContext("~/Views/Account/Register.cshtml", 1270, 19, true);

WriteLiteral(">Register</button>\n");

EndContext("~/Views/Account/Register.cshtml", 1270, 19, true);

BeginContext("~/Views/Account/Register.cshtml", 1289, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/Register.cshtml", 1289, 8, true);

BeginContext("~/Views/Account/Register.cshtml", 1297, 25, true);

WriteLiteral(" class=\"mt-3 text-center\"");

EndContext("~/Views/Account/Register.cshtml", 1297, 25, true);

BeginContext("~/Views/Account/Register.cshtml", 1322, 1, true);

WriteLiteral(">");

EndContext("~/Views/Account/Register.cshtml", 1322, 1, true);

BeginContext("~/Views/Account/Register.cshtml", 1324, 107, false);

            
            #line 33 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
                             Write(Html.ActionLink("Already have account? Login", "Login", "Account", null, new { @class = "text-secondary" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 1324, 107, false);

BeginContext("~/Views/Account/Register.cshtml", 1431, 7, true);

WriteLiteral("</div>\n");

EndContext("~/Views/Account/Register.cshtml", 1431, 7, true);

            
            #line 34 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/Account/Register.cshtml", 1440, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/Register.cshtml", 1440, 1, true);

DefineSection("Scripts", () => {

BeginContext("~/Views/Account/Register.cshtml", 1459, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/Register.cshtml", 1459, 1, true);

BeginContext("~/Views/Account/Register.cshtml", 1460, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Account/Register.cshtml", 1460, 4, true);

BeginContext("~/Views/Account/Register.cshtml", 1465, 37, false);

            
            #line 37 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\Register.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
EndContext("~/Views/Account/Register.cshtml", 1465, 37, false);

BeginContext("~/Views/Account/Register.cshtml", 1502, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/Register.cshtml", 1502, 1, true);

});

        }
    }
}
