#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "26BC9C8A88549B0F8F2632B671AD82AC01F4CC76"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Customers_Create_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.Customer> {
        
#line hidden
        
        public _Page_Views_Customers_Create_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
  
    ViewBag.Title = "Create Customer";

            
            #line default
            #line hidden
BeginContext("~/Views/Customers/Create.cshtml", 75, 28, true);

WriteLiteral("\n\n<h2>Create Customer</h2>\n\n");

EndContext("~/Views/Customers/Create.cshtml", 75, 28, true);

            
            #line 9 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
BeginContext("~/Views/Customers/Create.cshtml", 136, 23, false);

            
            #line 11 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Create.cshtml", 136, 23, false);

            
            #line 11 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
                            
    
            
            #line default
            #line hidden
BeginContext("~/Views/Customers/Create.cshtml", 165, 64, false);

            
            #line 12 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Create.cshtml", 165, 64, false);

            
            #line 12 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
                                                                     


            
            #line default
            #line hidden
BeginContext("~/Views/Customers/Create.cshtml", 231, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Customers/Create.cshtml", 231, 8, true);

BeginContext("~/Views/Customers/Create.cshtml", 239, 33, true);

WriteLiteral(" class=\"card card-body shadow-sm\"");

EndContext("~/Views/Customers/Create.cshtml", 239, 33, true);

BeginContext("~/Views/Customers/Create.cshtml", 272, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Customers/Create.cshtml", 272, 14, true);

BeginContext("~/Views/Customers/Create.cshtml", 286, 16, true);

WriteLiteral(" class=\"row g-3\"");

EndContext("~/Views/Customers/Create.cshtml", 286, 16, true);

BeginContext("~/Views/Customers/Create.cshtml", 302, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Customers/Create.cshtml", 302, 18, true);

BeginContext("~/Views/Customers/Create.cshtml", 320, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Customers/Create.cshtml", 320, 17, true);

BeginContext("~/Views/Customers/Create.cshtml", 337, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Customers/Create.cshtml", 337, 2, true);

BeginContext("~/Views/Customers/Create.cshtml", 339, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Create.cshtml", 339, 16, true);

BeginContext("~/Views/Customers/Create.cshtml", 356, 34, false);

            
            #line 17 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
           Write(Html.LabelFor(m => m.CustomerName));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Create.cshtml", 356, 34, false);

BeginContext("~/Views/Customers/Create.cshtml", 390, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Customers/Create.cshtml", 390, 1, true);

BeginContext("~/Views/Customers/Create.cshtml", 391, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Create.cshtml", 391, 16, true);

BeginContext("~/Views/Customers/Create.cshtml", 408, 69, false);

            
            #line 18 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
           Write(Html.TextBoxFor(m => m.CustomerName, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Create.cshtml", 408, 69, false);

BeginContext("~/Views/Customers/Create.cshtml", 477, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/Customers/Create.cshtml", 477, 36, true);

BeginContext("~/Views/Customers/Create.cshtml", 513, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Customers/Create.cshtml", 513, 17, true);

BeginContext("~/Views/Customers/Create.cshtml", 530, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Customers/Create.cshtml", 530, 2, true);

BeginContext("~/Views/Customers/Create.cshtml", 532, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Create.cshtml", 532, 16, true);

BeginContext("~/Views/Customers/Create.cshtml", 549, 27, false);

            
            #line 21 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
           Write(Html.LabelFor(m => m.Email));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Create.cshtml", 549, 27, false);

BeginContext("~/Views/Customers/Create.cshtml", 576, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Customers/Create.cshtml", 576, 1, true);

BeginContext("~/Views/Customers/Create.cshtml", 577, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Create.cshtml", 577, 16, true);

BeginContext("~/Views/Customers/Create.cshtml", 594, 78, false);

            
            #line 22 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
           Write(Html.TextBoxFor(m => m.Email, new { @class = "form-control", type = "email" }));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Create.cshtml", 594, 78, false);

BeginContext("~/Views/Customers/Create.cshtml", 672, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/Customers/Create.cshtml", 672, 36, true);

BeginContext("~/Views/Customers/Create.cshtml", 708, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Customers/Create.cshtml", 708, 17, true);

BeginContext("~/Views/Customers/Create.cshtml", 725, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Customers/Create.cshtml", 725, 2, true);

BeginContext("~/Views/Customers/Create.cshtml", 727, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Create.cshtml", 727, 16, true);

BeginContext("~/Views/Customers/Create.cshtml", 744, 35, false);

            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
           Write(Html.LabelFor(m => m.ContactPerson));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Create.cshtml", 744, 35, false);

BeginContext("~/Views/Customers/Create.cshtml", 779, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Customers/Create.cshtml", 779, 1, true);

BeginContext("~/Views/Customers/Create.cshtml", 780, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Create.cshtml", 780, 16, true);

BeginContext("~/Views/Customers/Create.cshtml", 797, 70, false);

            
            #line 26 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
           Write(Html.TextBoxFor(m => m.ContactPerson, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Create.cshtml", 797, 70, false);

BeginContext("~/Views/Customers/Create.cshtml", 867, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/Customers/Create.cshtml", 867, 36, true);

BeginContext("~/Views/Customers/Create.cshtml", 903, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Customers/Create.cshtml", 903, 17, true);

BeginContext("~/Views/Customers/Create.cshtml", 920, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Customers/Create.cshtml", 920, 2, true);

BeginContext("~/Views/Customers/Create.cshtml", 922, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Create.cshtml", 922, 16, true);

BeginContext("~/Views/Customers/Create.cshtml", 939, 33, false);

            
            #line 29 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
           Write(Html.LabelFor(m => m.PhoneNumber));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Create.cshtml", 939, 33, false);

BeginContext("~/Views/Customers/Create.cshtml", 972, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Customers/Create.cshtml", 972, 1, true);

BeginContext("~/Views/Customers/Create.cshtml", 973, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Create.cshtml", 973, 16, true);

BeginContext("~/Views/Customers/Create.cshtml", 990, 68, false);

            
            #line 30 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
           Write(Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Create.cshtml", 990, 68, false);

BeginContext("~/Views/Customers/Create.cshtml", 1058, 48, true);

WriteLiteral("\n            </div>\n        </div>\n\n        <div");

EndContext("~/Views/Customers/Create.cshtml", 1058, 48, true);

BeginContext("~/Views/Customers/Create.cshtml", 1106, 26, true);

WriteLiteral(" class=\"d-flex gap-2 mt-3\"");

EndContext("~/Views/Customers/Create.cshtml", 1106, 26, true);

BeginContext("~/Views/Customers/Create.cshtml", 1132, 21, true);

WriteLiteral(">\n            <button");

EndContext("~/Views/Customers/Create.cshtml", 1132, 21, true);

BeginContext("~/Views/Customers/Create.cshtml", 1153, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/Customers/Create.cshtml", 1153, 24, true);

BeginContext("~/Views/Customers/Create.cshtml", 1177, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Customers/Create.cshtml", 1177, 14, true);

BeginContext("~/Views/Customers/Create.cshtml", 1191, 29, true);

WriteLiteral(">Save</button>\n            <a");

EndContext("~/Views/Customers/Create.cshtml", 1191, 29, true);

WriteAttribute("href", Tuple.Create(" href=\"", 1220), Tuple.Create("\"", 1247)
            
            #line 36 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1227), Tuple.Create<System.Object, System.Int32>(Url.Action("Index")
            
            #line default
            #line hidden
, 1227), false)
);

BeginContext("~/Views/Customers/Create.cshtml", 1248, 34, true);

WriteLiteral(" class=\"btn btn-outline-secondary\"");

EndContext("~/Views/Customers/Create.cshtml", 1248, 34, true);

BeginContext("~/Views/Customers/Create.cshtml", 1282, 38, true);

WriteLiteral(">Cancel</a>\n        </div>\n    </div>\n");

EndContext("~/Views/Customers/Create.cshtml", 1282, 38, true);

            
            #line 39 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Create.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
