#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "BD9DEF9C71D357F50A1A29E67D2641DE4C9A4382"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Account_ExternalLoginConfirmation_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.ExternalLoginConfirmationViewModel> {
        
#line hidden
        
        public _Page_Views_Account_ExternalLoginConfirmation_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 2 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
  
    ViewBag.Title = "Register";

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 93, 5, true);

WriteLiteral("\n<h2>");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 93, 5, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 99, 13, false);

            
            #line 5 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 99, 13, false);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 112, 26, true);

WriteLiteral(".</h2>\n<h3>Associate your ");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 112, 26, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 139, 21, false);

            
            #line 6 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
              Write(ViewBag.LoginProvider);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 139, 21, false);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 160, 16, true);

WriteLiteral(" account.</h3>\n\n");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 160, 16, true);

            
            #line 8 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
 using (Html.BeginForm("ExternalLoginConfirmation", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    
            
            #line default
            #line hidden
BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 354, 23, false);

            
            #line 10 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 354, 23, false);

            
            #line 10 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
                            


            
            #line default
            #line hidden
BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 379, 30, true);

WriteLiteral("    <h4>Association Form</h4>\n");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 379, 30, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 409, 11, true);

WriteLiteral("    <hr />\n");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 409, 11, true);

            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
    
            
            #line default
            #line hidden
BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 425, 64, false);

            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 425, 64, false);

            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
                                                                     

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 490, 6, true);

WriteLiteral("    <p");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 490, 6, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 496, 18, true);

WriteLiteral(" class=\"text-info\"");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 496, 18, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 514, 57, true);

WriteLiteral(">\n        You\'ve successfully authenticated with <strong>");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 514, 57, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 572, 21, false);

            
            #line 16 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
                                                  Write(ViewBag.LoginProvider);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 572, 21, false);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 593, 133, true);

WriteLiteral("</strong>.\n        Please enter a user name for this site below and click the Reg" +
"ister button to finish\n        logging in.\n    </p>\n");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 593, 133, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 726, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 726, 8, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 734, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 734, 19, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 753, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 753, 2, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 755, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 755, 8, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 764, 70, false);

            
            #line 21 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
   Write(Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 764, 70, false);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 834, 13, true);

WriteLiteral("\n        <div");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 834, 13, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 847, 18, true);

WriteLiteral(" class=\"col-md-10\"");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 847, 18, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 865, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 865, 2, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 867, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 867, 12, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 880, 62, false);

            
            #line 23 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
       Write(Html.TextBoxFor(m => m.Email, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 880, 62, false);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 942, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 942, 1, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 943, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 943, 12, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 956, 75, false);

            
            #line 24 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
       Write(Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 956, 75, false);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1031, 27, true);

WriteLiteral("\n        </div>\n    </div>\n");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1031, 27, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1058, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1058, 8, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1066, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1066, 19, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1085, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1085, 14, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1099, 34, true);

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1099, 34, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1133, 20, true);

WriteLiteral(">\n            <input");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1133, 20, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1153, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1153, 14, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1167, 24, true);

WriteLiteral(" class=\"btn btn-default\"");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1167, 24, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1191, 17, true);

WriteLiteral(" value=\"Register\"");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1191, 17, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1208, 30, true);

WriteLiteral(" />\n        </div>\n    </div>\n");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1208, 30, true);

            
            #line 32 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1240, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1240, 1, true);

DefineSection("Scripts", () => {

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1259, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1259, 1, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1260, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1260, 4, true);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1265, 37, false);

            
            #line 35 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1265, 37, false);

BeginContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1302, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/ExternalLoginConfirmation.cshtml", 1302, 1, true);

});

        }
    }
}
