#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ForgotPasswordConfirmation.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "A52DFD5C9779A695B2C97F41ABEE45ED97D1828A"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Account_ForgotPasswordConfirmation_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Account_ForgotPasswordConfirmation_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ForgotPasswordConfirmation.cshtml"
  
    ViewBag.Title = "Forgot Password Confirmation";

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ForgotPasswordConfirmation.cshtml", 56, 9, true);

WriteLiteral("\n\n<hgroup");

EndContext("~/Views/Account/ForgotPasswordConfirmation.cshtml", 56, 9, true);

BeginContext("~/Views/Account/ForgotPasswordConfirmation.cshtml", 65, 14, true);

WriteLiteral(" class=\"title\"");

EndContext("~/Views/Account/ForgotPasswordConfirmation.cshtml", 65, 14, true);

BeginContext("~/Views/Account/ForgotPasswordConfirmation.cshtml", 79, 10, true);

WriteLiteral(">\n    <h1>");

EndContext("~/Views/Account/ForgotPasswordConfirmation.cshtml", 79, 10, true);

BeginContext("~/Views/Account/ForgotPasswordConfirmation.cshtml", 90, 13, false);

            
            #line 6 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ForgotPasswordConfirmation.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ForgotPasswordConfirmation.cshtml", 90, 13, false);

BeginContext("~/Views/Account/ForgotPasswordConfirmation.cshtml", 103, 105, true);

WriteLiteral(".</h1>\n</hgroup>\n<div>\n    <p>\n        Please check your email to reset your pass" +
"word.\n    </p>\n</div>\n\t\n");

EndContext("~/Views/Account/ForgotPasswordConfirmation.cshtml", 103, 105, true);

        }
    }
}
