#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6A91F823CE29FD490871D544F1DC740BA06D1C66"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_ProjectServiceMaps_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<SOEEApp.Models.ProjectServiceMap>> {
        
#line hidden
        
        public _Page_Views_ProjectServiceMaps_Index_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 2 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Index.cshtml"
  
    ViewBag.Title = "Project-Service Mapping";

            
            #line default
            #line hidden
BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 104, 39, true);

WriteLiteral("\n\n<h2>Project-Service Mapping</h2>\n<p>\n");

EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 104, 39, true);

BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 143, 4, true);

WriteLiteral("    ");

EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 143, 4, true);

BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 148, 111, false);

            
            #line 8 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Index.cshtml"
Write(Html.ActionLink("Create New Mapping", "Create", "ProjectServiceMaps", null, new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 148, 111, false);

BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 259, 13, true);

WriteLiteral("\n</p>\n\n<table");

EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 259, 13, true);

BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 272, 29, true);

WriteLiteral(" class=\"table table-bordered\"");

EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 272, 29, true);

BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 301, 186, true);

WriteLiteral(">\n    <thead>\n        <tr>\n            <th>Project</th>\n            <th>Service T" +
"ype</th>\n            <th>Date</th>\n            <th>Is Active</th>\n        </tr>\n" +
"    </thead>\n    <tbody>\n");

EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 301, 186, true);

            
            #line 21 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 21 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Index.cshtml"
         foreach (var item in Model)
        {

            
            #line default
            #line hidden
BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 534, 37, true);

WriteLiteral("            <tr>\n                <td>");

EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 534, 37, true);

BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 572, 17, false);

            
            #line 24 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Index.cshtml"
               Write(item.Project.Name);

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 572, 17, false);

BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 589, 26, true);

WriteLiteral("</td>\n                <td>");

EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 589, 26, true);

BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 616, 28, false);

            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Index.cshtml"
               Write(item.ServiceType.ServiceName);

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 616, 28, false);

BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 644, 26, true);

WriteLiteral("</td>\n                <td>");

EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 644, 26, true);

BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 671, 32, false);

            
            #line 26 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Index.cshtml"
               Write(item.AddedOn.ToShortDateString());

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 671, 32, false);

BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 703, 26, true);

WriteLiteral("</td>\n                <td>");

EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 703, 26, true);

BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 730, 13, false);

            
            #line 27 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Index.cshtml"
               Write(item.IsActive);

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 730, 13, false);

BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 743, 24, true);

WriteLiteral("</td>\n            </tr>\n");

EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 743, 24, true);

            
            #line 29 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Index.cshtml"
        }

            
            #line default
            #line hidden
BeginContext("~/Views/ProjectServiceMaps/Index.cshtml", 777, 22, true);

WriteLiteral("    </tbody>\n</table>\n");

EndContext("~/Views/ProjectServiceMaps/Index.cshtml", 777, 22, true);

        }
    }
}
