#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_LoginPartial.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "731EA9FFD90F86566F6BA3E715FB7C11996BC7A0"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    #line 1 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_LoginPartial.cshtml"
    using Microsoft.AspNet.Identity;
    
    #line default
    #line hidden
    
    
    public class _Page_Views_Shared__LoginPartial_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Shared__LoginPartial_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Shared/_LoginPartial.cshtml", 34, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 34, 2, true);

            
            #line 3 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_LoginPartial.cshtml"
 if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
    {
        
            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_LoginPartial.cshtml", 179, 23, false);

            
            #line 7 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_LoginPartial.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 179, 23, false);

            
            #line 7 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_LoginPartial.cshtml"
                                


            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_LoginPartial.cshtml", 206, 15, true);

WriteLiteral("            <ul");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 206, 15, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 221, 17, true);

WriteLiteral(" class=\"nav-list\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 221, 17, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 238, 41, true);

WriteLiteral(" style=\"align-items:center; gap:0.45rem;\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 238, 41, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 279, 18, true);

WriteLiteral(">\r\n            <li");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 279, 18, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 297, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 297, 17, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 314, 6, true);

WriteLiteral("><span");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 314, 6, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 320, 17, true);

WriteLiteral(" class=\"nav-user\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 320, 17, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 337, 7, true);

WriteLiteral(">Hello ");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 337, 7, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 345, 27, false);

            
            #line 10 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_LoginPartial.cshtml"
                                                         Write(User.Identity.GetUserName());

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_LoginPartial.cshtml", 345, 27, false);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 372, 30, true);

WriteLiteral("!</span></li>\r\n            <li");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 372, 30, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 402, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 402, 17, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 419, 8, true);

WriteLiteral("><button");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 419, 8, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 427, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 427, 14, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 441, 18, true);

WriteLiteral(" class=\"btn-ghost\"");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 441, 18, true);

BeginContext("~/Views/Shared/_LoginPartial.cshtml", 459, 39, true);

WriteLiteral(">Log off</button></li>\r\n        </ul>\r\n");

EndContext("~/Views/Shared/_LoginPartial.cshtml", 459, 39, true);

            
            #line 13 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_LoginPartial.cshtml"
    }
}

            
            #line default
            #line hidden
        }
    }
}
