#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0811063D05C326CC96D2BAF33C9B48BD99C71ED3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Projects_Edit_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.Project> {
        
#line hidden
        
        public _Page_Views_Projects_Edit_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
  
    ViewBag.Title = "Edit Project";

            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Edit.cshtml", 75, 8, true);

WriteLiteral("\r\n\r\n<div");

EndContext("~/Views/Projects/Edit.cshtml", 75, 8, true);

BeginContext("~/Views/Projects/Edit.cshtml", 83, 40, true);

WriteLiteral(" class=\"row justify-content-center mt-5\"");

EndContext("~/Views/Projects/Edit.cshtml", 83, 40, true);

BeginContext("~/Views/Projects/Edit.cshtml", 123, 11, true);

WriteLiteral(">\r\n    <div");

EndContext("~/Views/Projects/Edit.cshtml", 123, 11, true);

BeginContext("~/Views/Projects/Edit.cshtml", 134, 26, true);

WriteLiteral(" class=\"col-md-6 col-lg-5\"");

EndContext("~/Views/Projects/Edit.cshtml", 134, 26, true);

BeginContext("~/Views/Projects/Edit.cshtml", 160, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/Projects/Edit.cshtml", 160, 15, true);

BeginContext("~/Views/Projects/Edit.cshtml", 175, 32, true);

WriteLiteral(" class=\"card shadow-sm border-0\"");

EndContext("~/Views/Projects/Edit.cshtml", 175, 32, true);

BeginContext("~/Views/Projects/Edit.cshtml", 207, 19, true);

WriteLiteral(">\r\n            <div");

EndContext("~/Views/Projects/Edit.cshtml", 207, 19, true);

BeginContext("~/Views/Projects/Edit.cshtml", 226, 29, true);

WriteLiteral(" class=\"card-header bg-white\"");

EndContext("~/Views/Projects/Edit.cshtml", 226, 29, true);

BeginContext("~/Views/Projects/Edit.cshtml", 255, 22, true);

WriteLiteral(">\r\n                <h4");

EndContext("~/Views/Projects/Edit.cshtml", 255, 22, true);

BeginContext("~/Views/Projects/Edit.cshtml", 277, 26, true);

WriteLiteral(" class=\"mb-0 text-primary\"");

EndContext("~/Views/Projects/Edit.cshtml", 277, 26, true);

BeginContext("~/Views/Projects/Edit.cshtml", 303, 56, true);

WriteLiteral(">Edit Project</h4>\r\n            </div>\r\n            <div");

EndContext("~/Views/Projects/Edit.cshtml", 303, 56, true);

BeginContext("~/Views/Projects/Edit.cshtml", 359, 22, true);

WriteLiteral(" class=\"card-body p-4\"");

EndContext("~/Views/Projects/Edit.cshtml", 359, 22, true);

BeginContext("~/Views/Projects/Edit.cshtml", 381, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Projects/Edit.cshtml", 381, 3, true);

            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                 using (Html.BeginForm())
                {
                    
            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Edit.cshtml", 467, 23, false);

            
            #line 16 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 467, 23, false);

            
            #line 16 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                                            
                    
            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Edit.cshtml", 513, 40, false);

            
            #line 17 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
               Write(Html.HiddenFor(model => model.ProjectID));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 513, 40, false);

            
            #line 17 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                                                             


            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Edit.cshtml", 557, 24, true);

WriteLiteral("                    <div");

EndContext("~/Views/Projects/Edit.cshtml", 557, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 581, 13, true);

WriteLiteral(" class=\"mb-3\"");

EndContext("~/Views/Projects/Edit.cshtml", 581, 13, true);

BeginContext("~/Views/Projects/Edit.cshtml", 594, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Projects/Edit.cshtml", 594, 3, true);

BeginContext("~/Views/Projects/Edit.cshtml", 597, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Edit.cshtml", 597, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 622, 57, false);

            
            #line 20 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Name, new { @class = "form-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 622, 57, false);

BeginContext("~/Views/Projects/Edit.cshtml", 679, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Projects/Edit.cshtml", 679, 2, true);

BeginContext("~/Views/Projects/Edit.cshtml", 681, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Edit.cshtml", 681, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 706, 61, false);

            
            #line 21 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                   Write(Html.TextBoxFor(m => m.Name, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 706, 61, false);

BeginContext("~/Views/Projects/Edit.cshtml", 767, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Projects/Edit.cshtml", 767, 2, true);

BeginContext("~/Views/Projects/Edit.cshtml", 769, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Edit.cshtml", 769, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 794, 80, false);

            
            #line 22 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger small" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 794, 80, false);

BeginContext("~/Views/Projects/Edit.cshtml", 874, 30, true);

WriteLiteral("\r\n                    </div>\r\n");

EndContext("~/Views/Projects/Edit.cshtml", 874, 30, true);

            
            #line 24 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"


            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Edit.cshtml", 906, 24, true);

WriteLiteral("                    <div");

EndContext("~/Views/Projects/Edit.cshtml", 906, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 930, 13, true);

WriteLiteral(" class=\"mb-3\"");

EndContext("~/Views/Projects/Edit.cshtml", 930, 13, true);

BeginContext("~/Views/Projects/Edit.cshtml", 943, 32, true);

WriteLiteral(">\n                        <label");

EndContext("~/Views/Projects/Edit.cshtml", 943, 32, true);

BeginContext("~/Views/Projects/Edit.cshtml", 975, 19, true);

WriteLiteral(" class=\"form-label\"");

EndContext("~/Views/Projects/Edit.cshtml", 975, 19, true);

BeginContext("~/Views/Projects/Edit.cshtml", 994, 18, true);

WriteLiteral(">OIC User</label>\n");

EndContext("~/Views/Projects/Edit.cshtml", 994, 18, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1012, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Edit.cshtml", 1012, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1037, 82, false);

            
            #line 27 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                   Write(Html.DropDownList("OICUserId", null, "Select OIC", new { @class = "form-select" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 1037, 82, false);

BeginContext("~/Views/Projects/Edit.cshtml", 1119, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Projects/Edit.cshtml", 1119, 1, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1120, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Edit.cshtml", 1120, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1145, 85, false);

            
            #line 28 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.OICUserId, "", new { @class = "text-danger small" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 1145, 85, false);

BeginContext("~/Views/Projects/Edit.cshtml", 1230, 28, true);

WriteLiteral("\n                    </div>\n");

EndContext("~/Views/Projects/Edit.cshtml", 1230, 28, true);

            
            #line 30 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"


            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Edit.cshtml", 1259, 24, true);

WriteLiteral("                    <div");

EndContext("~/Views/Projects/Edit.cshtml", 1259, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1283, 13, true);

WriteLiteral(" class=\"mb-3\"");

EndContext("~/Views/Projects/Edit.cshtml", 1283, 13, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1296, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Projects/Edit.cshtml", 1296, 2, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1298, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Edit.cshtml", 1298, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1323, 64, false);

            
            #line 32 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                   Write(Html.LabelFor(m => m.ProjectCost, new { @class = "form-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 1323, 64, false);

BeginContext("~/Views/Projects/Edit.cshtml", 1387, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Projects/Edit.cshtml", 1387, 1, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1388, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Edit.cshtml", 1388, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1413, 111, false);

            
            #line 33 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                   Write(Html.TextBoxFor(m => m.ProjectCost, new { @class = "form-control", type = "number", step = "0.01", min = "0" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 1413, 111, false);

BeginContext("~/Views/Projects/Edit.cshtml", 1524, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Projects/Edit.cshtml", 1524, 1, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1525, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Edit.cshtml", 1525, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1550, 87, false);

            
            #line 34 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.ProjectCost, "", new { @class = "text-danger small" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 1550, 87, false);

BeginContext("~/Views/Projects/Edit.cshtml", 1637, 28, true);

WriteLiteral("\n                    </div>\n");

EndContext("~/Views/Projects/Edit.cshtml", 1637, 28, true);

            
            #line 36 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                    

            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Edit.cshtml", 1686, 24, true);

WriteLiteral("                    <div");

EndContext("~/Views/Projects/Edit.cshtml", 1686, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1710, 13, true);

WriteLiteral(" class=\"mb-3\"");

EndContext("~/Views/Projects/Edit.cshtml", 1710, 13, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1723, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Projects/Edit.cshtml", 1723, 2, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1725, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Edit.cshtml", 1725, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1750, 59, false);

            
            #line 38 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Status, new { @class = "form-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 1750, 59, false);

BeginContext("~/Views/Projects/Edit.cshtml", 1809, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Projects/Edit.cshtml", 1809, 1, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1810, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Edit.cshtml", 1810, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1835, 63, false);

            
            #line 39 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                   Write(Html.TextBoxFor(m => m.Status, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 1835, 63, false);

BeginContext("~/Views/Projects/Edit.cshtml", 1898, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Projects/Edit.cshtml", 1898, 1, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1899, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Edit.cshtml", 1899, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 1924, 82, false);

            
            #line 40 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Status, "", new { @class = "text-danger small" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 1924, 82, false);

BeginContext("~/Views/Projects/Edit.cshtml", 2006, 29, true);

WriteLiteral("\n                    </div>\r\n");

EndContext("~/Views/Projects/Edit.cshtml", 2006, 29, true);

            
            #line 42 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"


            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Edit.cshtml", 2037, 24, true);

WriteLiteral("                    <div");

EndContext("~/Views/Projects/Edit.cshtml", 2037, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 2061, 26, true);

WriteLiteral(" class=\"d-grid gap-2 mt-4\"");

EndContext("~/Views/Projects/Edit.cshtml", 2061, 26, true);

BeginContext("~/Views/Projects/Edit.cshtml", 2087, 33, true);

WriteLiteral(">\r\n                        <input");

EndContext("~/Views/Projects/Edit.cshtml", 2087, 33, true);

BeginContext("~/Views/Projects/Edit.cshtml", 2120, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Projects/Edit.cshtml", 2120, 14, true);

BeginContext("~/Views/Projects/Edit.cshtml", 2134, 21, true);

WriteLiteral(" value=\"Save Changes\"");

EndContext("~/Views/Projects/Edit.cshtml", 2134, 21, true);

BeginContext("~/Views/Projects/Edit.cshtml", 2155, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/Projects/Edit.cshtml", 2155, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 2179, 5, true);

WriteLiteral(" />\r\n");

EndContext("~/Views/Projects/Edit.cshtml", 2179, 5, true);

BeginContext("~/Views/Projects/Edit.cshtml", 2184, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Projects/Edit.cshtml", 2184, 24, true);

BeginContext("~/Views/Projects/Edit.cshtml", 2209, 89, false);

            
            #line 45 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                   Write(Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-light text-secondary" }));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 2209, 89, false);

BeginContext("~/Views/Projects/Edit.cshtml", 2298, 30, true);

WriteLiteral("\r\n                    </div>\r\n");

EndContext("~/Views/Projects/Edit.cshtml", 2298, 30, true);

            
            #line 47 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
                }

            
            #line default
            #line hidden
BeginContext("~/Views/Projects/Edit.cshtml", 2347, 58, true);

WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

EndContext("~/Views/Projects/Edit.cshtml", 2347, 58, true);

DefineSection("Scripts", () => {

BeginContext("~/Views/Projects/Edit.cshtml", 2423, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Projects/Edit.cshtml", 2423, 2, true);

BeginContext("~/Views/Projects/Edit.cshtml", 2425, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Projects/Edit.cshtml", 2425, 4, true);

BeginContext("~/Views/Projects/Edit.cshtml", 2430, 37, false);

            
            #line 54 "C:\projects\SOEEApp-main\SOEEApp\Views\Projects\Edit.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
EndContext("~/Views/Projects/Edit.cshtml", 2430, 37, false);

BeginContext("~/Views/Projects/Edit.cshtml", 2467, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/Projects/Edit.cshtml", 2467, 2, true);

});

        }
    }
}
