#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6C73680B6A2346C177DEA904D59B99547C1C8D86"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_ProjectServiceMaps_ManageServices_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.ManageServicesViewModel> {
        
#line hidden
        
        public _Page_Views_ProjectServiceMaps_ManageServices_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 47, 33, true);

WriteLiteral("<h2>Manage Services for Project: ");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 47, 33, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 81, 18, false);

            
            #line 3 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml"
                            Write(Model.Project.Name);

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 81, 18, false);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 99, 41, true);

WriteLiteral("</h2>\n\n<hr />\n\n<h3>Add Service</h3>\n<form");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 99, 41, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 140, 14, true);

WriteLiteral(" method=\"post\"");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 140, 14, true);

WriteAttribute("action", Tuple.Create(" action=\"", 154), Tuple.Create("\"", 188)
            
            #line 8 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml"
, Tuple.Create(Tuple.Create("", 163), Tuple.Create<System.Object, System.Int32>(Url.Action("AddService")
            
            #line default
            #line hidden
, 163), false)
);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 189, 12, true);

WriteLiteral(">\n    <input");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 189, 12, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 201, 14, true);

WriteLiteral(" type=\"hidden\"");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 201, 14, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 215, 17, true);

WriteLiteral(" name=\"projectId\"");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 215, 17, true);

WriteAttribute("value", Tuple.Create(" value=\"", 232), Tuple.Create("\"", 264)
            
            #line 9 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml"
, Tuple.Create(Tuple.Create("", 240), Tuple.Create<System.Object, System.Int32>(Model.Project.ProjectID
            
            #line default
            #line hidden
, 240), false)
);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 265, 16, true);

WriteLiteral(" />\n\n    <select");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 265, 16, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 281, 21, true);

WriteLiteral(" class=\"form-control\"");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 281, 21, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 302, 21, true);

WriteLiteral(" name=\"serviceTypeID\"");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 302, 21, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 323, 17, true);

WriteLiteral(">\n        <option");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 323, 17, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 340, 9, true);

WriteLiteral(" value=\"\"");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 340, 9, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 349, 31, true);

WriteLiteral(">-- Select Service --</option>\n");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 349, 31, true);

            
            #line 13 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml"
        
            
            #line default
            #line hidden
            
            #line 13 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml"
         foreach (var s in Model.AllServices)
        {

            
            #line default
            #line hidden
BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 436, 19, true);

WriteLiteral("            <option");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 436, 19, true);

WriteAttribute("value", Tuple.Create(" value=\"", 455), Tuple.Create("\"", 479)
            
            #line 15 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml"
, Tuple.Create(Tuple.Create("", 463), Tuple.Create<System.Object, System.Int32>(s.ServiceTypeID
            
            #line default
            #line hidden
, 463), false)
);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 480, 1, true);

WriteLiteral(">");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 480, 1, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 482, 13, false);

            
            #line 15 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml"
                                        Write(s.ServiceName);

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 482, 13, false);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 495, 10, true);

WriteLiteral("</option>\n");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 495, 10, true);

            
            #line 16 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml"
        }

            
            #line default
            #line hidden
BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 515, 37, true);

WriteLiteral("    </select>\n\n    <br />\n    <button");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 515, 37, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 552, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 552, 24, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 576, 70, true);

WriteLiteral(">Add</button>\n</form>\n\n<hr />\n\n<h3>Services Already Added</h3>\n\n<table");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 576, 70, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 646, 29, true);

WriteLiteral(" class=\"table table-bordered\"");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 646, 29, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 675, 97, true);

WriteLiteral(">\n    <tr>\n        <th>Service</th>\n        <th>Added On</th>\n        <th>Action<" +
"/th>\n    </tr>\n\n");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 675, 97, true);

            
            #line 34 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml"
    
            
            #line default
            #line hidden
            
            #line 34 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml"
     foreach (var item in Model.ExistingServices)
    {

            
            #line default
            #line hidden
BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 828, 29, true);

WriteLiteral("        <tr>\n            <td>");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 828, 29, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 858, 28, false);

            
            #line 37 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml"
           Write(item.ServiceType.ServiceName);

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 858, 28, false);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 886, 22, true);

WriteLiteral("</td>\n            <td>");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 886, 22, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 909, 35, false);

            
            #line 38 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml"
           Write(item.AddedOn.ToString("dd-MM-yyyy"));

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 909, 35, false);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 944, 41, true);

WriteLiteral("</td>\n            <td>\n                <a");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 944, 41, true);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 985, 30, true);

WriteLiteral(" class=\"btn btn-danger btn-sm\"");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 985, 30, true);

WriteAttribute("href", Tuple.Create("\n                   href=\"", 1015), Tuple.Create("\"", 1132)
            
            #line 41 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml"
, Tuple.Create(Tuple.Create("", 1041), Tuple.Create<System.Object, System.Int32>(Url.Action("Remove", new { id = item.ProjServMapID, projectId = Model.Project.ProjectID })
            
            #line default
            #line hidden
, 1041), false)
);

BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 1133, 82, true);

WriteLiteral(">\n                    Remove\n                </a>\n            </td>\n        </tr>" +
"\n");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 1133, 82, true);

            
            #line 46 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\ManageServices.cshtml"
    }

            
            #line default
            #line hidden
BeginContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 1221, 9, true);

WriteLiteral("</table>\n");

EndContext("~/Views/ProjectServiceMaps/ManageServices.cshtml", 1221, 9, true);

        }
    }
}
