#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Account\_ExternalLoginsListPartial.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7E82C0B055E4EAA8CA26F45676AE36F1FA14FFD3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    #line 2 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\_ExternalLoginsListPartial.cshtml"
    using Microsoft.Owin.Security;
    
    #line default
    #line hidden
    
    
    public class _Page_Views_Account__ExternalLoginsListPartial_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.ExternalLoginListViewModel> {
        
#line hidden
        
        public _Page_Views_Account__ExternalLoginsListPartial_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 80, 48, true);

WriteLiteral("\n<h4>Use another service to log in.</h4>\n<hr />\n");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 80, 48, true);

            
            #line 6 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\_ExternalLoginsListPartial.cshtml"
  
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0) {

            
            #line default
            #line hidden
BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 269, 110, true);

WriteLiteral("        <div>\n            <p>\n                There are no external authenticatio" +
"n services configured. See <a");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 269, 110, true);

BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 379, 53, true);

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=403804\"");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 379, 53, true);

BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 432, 162, true);

WriteLiteral(">this article</a>\n                for details on setting up this ASP.NET applicat" +
"ion to support logging in via external services.\n            </p>\n        </div>" +
"\n");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 432, 162, true);

            
            #line 15 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\_ExternalLoginsListPartial.cshtml"
    }
    else {
        using (Html.BeginForm("ExternalLogin", "Account", new { ReturnUrl = Model.ReturnUrl })) {
            
            
            #line default
            #line hidden
BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 722, 23, false);

            
            #line 18 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\_ExternalLoginsListPartial.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 722, 23, false);

            
            #line 18 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\_ExternalLoginsListPartial.cshtml"
                                    

            
            #line default
            #line hidden
BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 746, 16, true);

WriteLiteral("            <div");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 746, 16, true);

BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 762, 21, true);

WriteLiteral(" id=\"socialLoginList\"");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 762, 21, true);

BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 783, 22, true);

WriteLiteral(">\n                <p>\n");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 783, 22, true);

            
            #line 21 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\_ExternalLoginsListPartial.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 21 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\_ExternalLoginsListPartial.cshtml"
                     foreach (AuthenticationDescription p in loginProviders) {

            
            #line default
            #line hidden
BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 884, 31, true);

WriteLiteral("                        <button");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 884, 31, true);

BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 915, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 915, 14, true);

BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 929, 24, true);

WriteLiteral(" class=\"btn btn-default\"");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 929, 24, true);

WriteAttribute("id", Tuple.Create(" id=\"", 953), Tuple.Create("\"", 979)
            
            #line 22 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\_ExternalLoginsListPartial.cshtml"
, Tuple.Create(Tuple.Create("", 958), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 958), false)
);

BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 980, 16, true);

WriteLiteral(" name=\"provider\"");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 980, 16, true);

WriteAttribute("value", Tuple.Create(" value=\"", 996), Tuple.Create("\"", 1025)
            
            #line 22 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\_ExternalLoginsListPartial.cshtml"
                                        , Tuple.Create(Tuple.Create("", 1004), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 1004), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1026), Tuple.Create("\"", 1070)
, Tuple.Create(Tuple.Create("", 1034), Tuple.Create("Log", 1034), true)
, Tuple.Create(Tuple.Create(" ", 1037), Tuple.Create("in", 1038), true)
, Tuple.Create(Tuple.Create(" ", 1040), Tuple.Create("using", 1041), true)
, Tuple.Create(Tuple.Create(" ", 1046), Tuple.Create("your", 1047), true)
            
            #line 22 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\_ExternalLoginsListPartial.cshtml"
                                                                                       , Tuple.Create(Tuple.Create(" ", 1051), Tuple.Create<System.Object, System.Int32>(p.Caption
            
            #line default
            #line hidden
, 1052), false)
, Tuple.Create(Tuple.Create(" ", 1062), Tuple.Create("account", 1063), true)
);

BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 1071, 1, true);

WriteLiteral(">");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 1071, 1, true);

BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 1073, 20, false);

            
            #line 22 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\_ExternalLoginsListPartial.cshtml"
                                                                                                                                                                                       Write(p.AuthenticationType);

            
            #line default
            #line hidden
EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 1073, 20, false);

BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 1093, 10, true);

WriteLiteral("</button>\n");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 1093, 10, true);

            
            #line 23 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\_ExternalLoginsListPartial.cshtml"
                    }

            
            #line default
            #line hidden
BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 1125, 40, true);

WriteLiteral("                </p>\n            </div>\n");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 1125, 40, true);

            
            #line 26 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\_ExternalLoginsListPartial.cshtml"
        }
    }

            
            #line default
            #line hidden
BeginContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 1182, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/_ExternalLoginsListPartial.cshtml", 1182, 1, true);

        }
    }
}
