#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypes\Edit.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "FC7820FEE6FC706C59C9C64C319D71BFA009438E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_ServiceTypes_Edit_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.ServiceType> {
        
#line hidden
        
        public _Page_Views_ServiceTypes_Edit_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/ServiceTypes/Edit.cshtml", 34, 28, true);

WriteLiteral("<h2>Edit Service Type</h2>\n\n");

EndContext("~/Views/ServiceTypes/Edit.cshtml", 34, 28, true);

            
            #line 4 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypes\Edit.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
BeginContext("~/Views/ServiceTypes/Edit.cshtml", 95, 23, false);

            
            #line 6 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypes\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/ServiceTypes/Edit.cshtml", 95, 23, false);

            
            #line 6 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypes\Edit.cshtml"
                            

    
            
            #line default
            #line hidden
BeginContext("~/Views/ServiceTypes/Edit.cshtml", 125, 36, false);

            
            #line 8 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypes\Edit.cshtml"
Write(Html.HiddenFor(m => m.ServiceTypeID));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceTypes/Edit.cshtml", 125, 36, false);

            
            #line 8 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypes\Edit.cshtml"
                                         


            
            #line default
            #line hidden
BeginContext("~/Views/ServiceTypes/Edit.cshtml", 163, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/ServiceTypes/Edit.cshtml", 163, 8, true);

BeginContext("~/Views/ServiceTypes/Edit.cshtml", 171, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/ServiceTypes/Edit.cshtml", 171, 19, true);

BeginContext("~/Views/ServiceTypes/Edit.cshtml", 190, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/ServiceTypes/Edit.cshtml", 190, 2, true);

BeginContext("~/Views/ServiceTypes/Edit.cshtml", 192, 8, true);

WriteLiteral("        ");

EndContext("~/Views/ServiceTypes/Edit.cshtml", 192, 8, true);

BeginContext("~/Views/ServiceTypes/Edit.cshtml", 201, 33, false);

            
            #line 11 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypes\Edit.cshtml"
   Write(Html.LabelFor(m => m.ServiceName));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceTypes/Edit.cshtml", 201, 33, false);

BeginContext("~/Views/ServiceTypes/Edit.cshtml", 234, 1, true);

WriteLiteral("\n");

EndContext("~/Views/ServiceTypes/Edit.cshtml", 234, 1, true);

BeginContext("~/Views/ServiceTypes/Edit.cshtml", 235, 8, true);

WriteLiteral("        ");

EndContext("~/Views/ServiceTypes/Edit.cshtml", 235, 8, true);

BeginContext("~/Views/ServiceTypes/Edit.cshtml", 244, 132, false);

            
            #line 12 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypes\Edit.cshtml"
   Write(Html.DropDownListFor(m => m.ServiceName, (SelectList)ViewBag.AllowedServiceNames, "Select service", new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceTypes/Edit.cshtml", 244, 132, false);

BeginContext("~/Views/ServiceTypes/Edit.cshtml", 376, 1, true);

WriteLiteral("\n");

EndContext("~/Views/ServiceTypes/Edit.cshtml", 376, 1, true);

BeginContext("~/Views/ServiceTypes/Edit.cshtml", 377, 8, true);

WriteLiteral("        ");

EndContext("~/Views/ServiceTypes/Edit.cshtml", 377, 8, true);

BeginContext("~/Views/ServiceTypes/Edit.cshtml", 386, 81, false);

            
            #line 13 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypes\Edit.cshtml"
   Write(Html.ValidationMessageFor(m => m.ServiceName, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceTypes/Edit.cshtml", 386, 81, false);

BeginContext("~/Views/ServiceTypes/Edit.cshtml", 467, 12, true);

WriteLiteral("\n    </div>\n");

EndContext("~/Views/ServiceTypes/Edit.cshtml", 467, 12, true);

            
            #line 15 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypes\Edit.cshtml"


            
            #line default
            #line hidden
BeginContext("~/Views/ServiceTypes/Edit.cshtml", 480, 11, true);

WriteLiteral("    <button");

EndContext("~/Views/ServiceTypes/Edit.cshtml", 480, 11, true);

BeginContext("~/Views/ServiceTypes/Edit.cshtml", 491, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/ServiceTypes/Edit.cshtml", 491, 14, true);

BeginContext("~/Views/ServiceTypes/Edit.cshtml", 505, 24, true);

WriteLiteral(" class=\"btn btn-success\"");

EndContext("~/Views/ServiceTypes/Edit.cshtml", 505, 24, true);

BeginContext("~/Views/ServiceTypes/Edit.cshtml", 529, 17, true);

WriteLiteral(">Update</button>\n");

EndContext("~/Views/ServiceTypes/Edit.cshtml", 529, 17, true);

            
            #line 17 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypes\Edit.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
