#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\Error.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "DC4AAC2642C126A9C41A37CA6C95644DE30A7DF8"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Shared_Error_cshtml : System.Web.Mvc.WebViewPage<System.Web.Mvc.HandleErrorInfo> {
        
#line hidden
        
        public _Page_Views_Shared_Error_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\Error.cshtml"
  
    ViewBag.Title = "Error";

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/Error.cshtml", 72, 5, true);

WriteLiteral("\n\n<h1");

EndContext("~/Views/Shared/Error.cshtml", 72, 5, true);

BeginContext("~/Views/Shared/Error.cshtml", 77, 20, true);

WriteLiteral(" class=\"text-danger\"");

EndContext("~/Views/Shared/Error.cshtml", 77, 20, true);

BeginContext("~/Views/Shared/Error.cshtml", 97, 16, true);

WriteLiteral(">Error.</h1>\n<h2");

EndContext("~/Views/Shared/Error.cshtml", 97, 16, true);

BeginContext("~/Views/Shared/Error.cshtml", 113, 20, true);

WriteLiteral(" class=\"text-danger\"");

EndContext("~/Views/Shared/Error.cshtml", 113, 20, true);

BeginContext("~/Views/Shared/Error.cshtml", 133, 56, true);

WriteLiteral(">An error occurred while processing your request.</h2>\n\n");

EndContext("~/Views/Shared/Error.cshtml", 133, 56, true);

        }
    }
}
