#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "15F99D33CD809E12CB9A05EADC0949BBDCAD44C4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Shared__Layout_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Shared/_Layout.cshtml", 0, 22, true);

WriteLiteral("<!DOCTYPE html>\r\n<html");

EndContext("~/Views/Shared/_Layout.cshtml", 0, 22, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 22, 10, true);

WriteLiteral(" lang=\"en\"");

EndContext("~/Views/Shared/_Layout.cshtml", 22, 10, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 32, 20, true);

WriteLiteral(">\r\n<head>\r\n    <meta");

EndContext("~/Views/Shared/_Layout.cshtml", 32, 20, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 52, 16, true);

WriteLiteral(" charset=\"utf-8\"");

EndContext("~/Views/Shared/_Layout.cshtml", 52, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 68, 14, true);

WriteLiteral(" />\r\n    <meta");

EndContext("~/Views/Shared/_Layout.cshtml", 68, 14, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 82, 16, true);

WriteLiteral(" name=\"viewport\"");

EndContext("~/Views/Shared/_Layout.cshtml", 82, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 98, 48, true);

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

EndContext("~/Views/Shared/_Layout.cshtml", 98, 48, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 146, 14, true);

WriteLiteral(">\r\n    <title>");

EndContext("~/Views/Shared/_Layout.cshtml", 146, 14, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 161, 13, false);

            
            #line 6 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 161, 13, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 174, 21, true);

WriteLiteral(" - FinTrack</title>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 174, 21, true);

            
            #line 7 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 7 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
      
        var currentController = ViewContext.RouteData.Values["controller"]?.ToString() ?? "";
        var currentAction = ViewContext.RouteData.Values["action"]?.ToString() ?? "";
        var hideLayout = currentController == "Account" && (currentAction == "Login" || currentAction == "Register");
    
            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 509, 45, true);

WriteLiteral("\r\n    <!-- Google Fonts: Inter -->\r\n    <link");

EndContext("~/Views/Shared/_Layout.cshtml", 509, 45, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 554, 17, true);

WriteLiteral(" rel=\"preconnect\"");

EndContext("~/Views/Shared/_Layout.cshtml", 554, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 571, 36, true);

WriteLiteral(" href=\"https://fonts.googleapis.com\"");

EndContext("~/Views/Shared/_Layout.cshtml", 571, 36, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 607, 12, true);

WriteLiteral(">\r\n    <link");

EndContext("~/Views/Shared/_Layout.cshtml", 607, 12, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 619, 17, true);

WriteLiteral(" rel=\"preconnect\"");

EndContext("~/Views/Shared/_Layout.cshtml", 619, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 636, 33, true);

WriteLiteral(" href=\"https://fonts.gstatic.com\"");

EndContext("~/Views/Shared/_Layout.cshtml", 636, 33, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 669, 24, true);

WriteLiteral(" crossorigin>\r\n    <link");

EndContext("~/Views/Shared/_Layout.cshtml", 669, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 693, 88, true);

WriteLiteral(" href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&displa" +
"y=swap\"");

EndContext("~/Views/Shared/_Layout.cshtml", 693, 88, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 781, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Shared/_Layout.cshtml", 781, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 798, 12, true);

WriteLiteral(">\r\n    <link");

EndContext("~/Views/Shared/_Layout.cshtml", 798, 12, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 810, 107, true);

WriteLiteral(" href=\"https://fonts.googleapis.com/css2?family=Great+Vibes&family=Inter:wght@300" +
";400;500;600&display=swap\"");

EndContext("~/Views/Shared/_Layout.cshtml", 810, 107, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 917, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Shared/_Layout.cshtml", 917, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 934, 48, true);

WriteLiteral(">\r\n    \r\n    <!-- Bootstrap 5 CDN -->\r\n    <link");

EndContext("~/Views/Shared/_Layout.cshtml", 934, 48, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 982, 79, true);

WriteLiteral(" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"");

EndContext("~/Views/Shared/_Layout.cshtml", 982, 79, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1061, 17, true);

WriteLiteral(" rel=\"stylesheet\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1061, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1078, 84, true);

WriteLiteral(" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2" +
"HN\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1078, 84, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1162, 24, true);

WriteLiteral(" crossorigin=\"anonymous\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1162, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1186, 9, true);

WriteLiteral(">\r\n    \r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1186, 9, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1195, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 1195, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1200, 30, false);

            
            #line 21 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/Content/css"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1200, 30, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1230, 16, true);

WriteLiteral("\r\n</head>\r\n<body");

EndContext("~/Views/Shared/_Layout.cshtml", 1230, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1246, 17, true);

WriteLiteral(" class=\"app-root\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1246, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1263, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1263, 3, true);

            
            #line 24 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 24 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
     if (!hideLayout)
    {

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 1296, 15, true);

WriteLiteral("        <header");

EndContext("~/Views/Shared/_Layout.cshtml", 1296, 15, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1311, 16, true);

WriteLiteral(" class=\"app-nav\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1311, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1327, 19, true);

WriteLiteral(">\r\n            <div");

EndContext("~/Views/Shared/_Layout.cshtml", 1327, 19, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1346, 18, true);

WriteLiteral(" class=\"container\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1346, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1364, 23, true);

WriteLiteral(">\r\n                <div");

EndContext("~/Views/Shared/_Layout.cshtml", 1364, 23, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1387, 67, true);

WriteLiteral(" class=\"d-flex align-items-center justify-content-center flex-fill\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1387, 67, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1454, 25, true);

WriteLiteral(">\r\n                    <a");

EndContext("~/Views/Shared/_Layout.cshtml", 1454, 25, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1479, 44, true);

WriteLiteral(" class=\"app-brand fs-3 fw-bold text-primary\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1479, 44, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1523, 19, true);

WriteLiteral(" href=\"/Home/Index\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1523, 19, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1542, 59, true);

WriteLiteral(">FinTrack</a>\r\n                </div>\r\n                <nav");

EndContext("~/Views/Shared/_Layout.cshtml", 1542, 59, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1601, 18, true);

WriteLiteral(" class=\"flex-fill\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1601, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1619, 26, true);

WriteLiteral(">\r\n                    <ul");

EndContext("~/Views/Shared/_Layout.cshtml", 1619, 26, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1645, 37, true);

WriteLiteral(" class=\"nav-list justify-content-end\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1645, 37, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1682, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1682, 3, true);

            
            #line 33 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 33 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                         if (User.IsInRole("OIC"))
                        {

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 1764, 31, true);

WriteLiteral("                            <li");

EndContext("~/Views/Shared/_Layout.cshtml", 1764, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1795, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1795, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1812, 1, true);

WriteLiteral(">");

EndContext("~/Views/Shared/_Layout.cshtml", 1812, 1, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1814, 78, false);

            
            #line 35 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                                            Write(Html.ActionLink("My SOEE", "Index", "SOEE", null, new { @class = "nav-link" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1814, 78, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 1892, 7, true);

WriteLiteral("</li>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 1892, 7, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1899, 31, true);

WriteLiteral("                            <li");

EndContext("~/Views/Shared/_Layout.cshtml", 1899, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1930, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Shared/_Layout.cshtml", 1930, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1947, 1, true);

WriteLiteral(">");

EndContext("~/Views/Shared/_Layout.cshtml", 1947, 1, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 1949, 83, false);

            
            #line 36 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                                            Write(Html.ActionLink("Create SOEE", "Create", "SOEE", null, new { @class = "nav-link" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 1949, 83, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 2032, 7, true);

WriteLiteral("</li>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 2032, 7, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2039, 31, true);

WriteLiteral("                            <li");

EndContext("~/Views/Shared/_Layout.cshtml", 2039, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2070, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2070, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2087, 1, true);

WriteLiteral(">");

EndContext("~/Views/Shared/_Layout.cshtml", 2087, 1, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2089, 83, false);

            
            #line 37 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                                            Write(Html.ActionLink("Projects", "Index", "Projects", null, new { @class = "nav-link" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 2089, 83, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 2172, 7, true);

WriteLiteral("</li>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 2172, 7, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2179, 31, true);

WriteLiteral("                            <li");

EndContext("~/Views/Shared/_Layout.cshtml", 2179, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2210, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2210, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2227, 1, true);

WriteLiteral(">");

EndContext("~/Views/Shared/_Layout.cshtml", 2227, 1, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2229, 93, false);

            
            #line 38 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                                            Write(Html.ActionLink("Cost Slabs", "Index", "ServiceCostSlabs", null, new { @class = "nav-link" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 2229, 93, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 2322, 7, true);

WriteLiteral("</li>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 2322, 7, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2329, 31, true);

WriteLiteral("                            <li");

EndContext("~/Views/Shared/_Layout.cshtml", 2329, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2360, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2360, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2377, 1, true);

WriteLiteral(">");

EndContext("~/Views/Shared/_Layout.cshtml", 2377, 1, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2379, 90, false);

            
            #line 39 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                                            Write(Html.ActionLink("Client Details", "Index", "Customers", null, new { @class = "nav-link" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 2379, 90, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 2469, 7, true);

WriteLiteral("</li>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 2469, 7, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2476, 31, true);

WriteLiteral("                            <li");

EndContext("~/Views/Shared/_Layout.cshtml", 2476, 31, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2507, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2507, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2524, 1, true);

WriteLiteral(">");

EndContext("~/Views/Shared/_Layout.cshtml", 2524, 1, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2526, 92, false);

            
            #line 40 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                                            Write(Html.ActionLink("Mapping", "Index", "ProjectServiceMaps", null, new { @class = "nav-link" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 2526, 92, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 2618, 7, true);

WriteLiteral("</li>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 2618, 7, true);

            
            #line 41 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                        }

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 2652, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Shared/_Layout.cshtml", 2652, 24, true);

            
            #line 42 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                         if (User.IsInRole("FinanceManager")) {
            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 2715, 4, true);

WriteLiteral(" <li");

EndContext("~/Views/Shared/_Layout.cshtml", 2715, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2719, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2719, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2736, 1, true);

WriteLiteral(">");

EndContext("~/Views/Shared/_Layout.cshtml", 2736, 1, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2738, 85, false);

            
            #line 42 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                                                                                Write(Html.ActionLink("Pending FM", "PendingFM", "SOEE", null, new { @class = "nav-link" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 2738, 85, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 2823, 6, true);

WriteLiteral("</li> ");

EndContext("~/Views/Shared/_Layout.cshtml", 2823, 6, true);

            
            #line 42 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                                                                                                                                                                                 }

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 2832, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Shared/_Layout.cshtml", 2832, 24, true);

            
            #line 43 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                         if (User.IsInRole("FinanceDirector")) {
            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 2896, 4, true);

WriteLiteral(" <li");

EndContext("~/Views/Shared/_Layout.cshtml", 2896, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2900, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Shared/_Layout.cshtml", 2900, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2917, 1, true);

WriteLiteral(">");

EndContext("~/Views/Shared/_Layout.cshtml", 2917, 1, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 2919, 85, false);

            
            #line 43 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                                                                                 Write(Html.ActionLink("Pending FD", "PendingFD", "SOEE", null, new { @class = "nav-link" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 2919, 85, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 3004, 6, true);

WriteLiteral("</li> ");

EndContext("~/Views/Shared/_Layout.cshtml", 3004, 6, true);

            
            #line 43 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                                                                                                                                                                                  }

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 3013, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Shared/_Layout.cshtml", 3013, 24, true);

            
            #line 44 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                         if (User.IsInRole("Cashier")) {
            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 3069, 4, true);

WriteLiteral(" <li");

EndContext("~/Views/Shared/_Layout.cshtml", 3069, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3073, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3073, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3090, 1, true);

WriteLiteral(">");

EndContext("~/Views/Shared/_Layout.cshtml", 3090, 1, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3092, 83, false);

            
            #line 44 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                                                                         Write(Html.ActionLink("Payments", "Index", "Payments", null, new { @class = "nav-link" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 3092, 83, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 3175, 6, true);

WriteLiteral("</li> ");

EndContext("~/Views/Shared/_Layout.cshtml", 3175, 6, true);

            
            #line 44 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                                                                                                                                                                        }

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 3184, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Shared/_Layout.cshtml", 3184, 24, true);

            
            #line 45 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                         if (User.IsInRole("Client")) {
            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 3239, 4, true);

WriteLiteral(" <li");

EndContext("~/Views/Shared/_Layout.cshtml", 3239, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3243, 17, true);

WriteLiteral(" class=\"nav-item\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3243, 17, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3260, 1, true);

WriteLiteral(">");

EndContext("~/Views/Shared/_Layout.cshtml", 3260, 1, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3262, 80, false);

            
            #line 45 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                                                                        Write(Html.ActionLink("My SOEEs", "MySOEE", "SOEE", null, new { @class = "nav-link" }));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 3262, 80, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 3342, 6, true);

WriteLiteral("</li> ");

EndContext("~/Views/Shared/_Layout.cshtml", 3342, 6, true);

            
            #line 45 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                                                                                                                                                                    }

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 3351, 71, true);

WriteLiteral("                    </ul>\r\n                </nav>\r\n                <div");

EndContext("~/Views/Shared/_Layout.cshtml", 3351, 71, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3422, 53, true);

WriteLiteral(" style=\"display:flex;gap:0.6rem; align-items:center;\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3422, 53, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3475, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 3475, 3, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3478, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/Shared/_Layout.cshtml", 3478, 20, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3499, 29, false);

            
            #line 49 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
               Write(Html.Partial("_LoginPartial"));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 3499, 29, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 3528, 65, true);

WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </header>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 3528, 65, true);

            
            #line 53 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 3600, 10, true);

WriteLiteral("\r\n    <div");

EndContext("~/Views/Shared/_Layout.cshtml", 3600, 10, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3610, 60, true);

WriteLiteral(" class=\"container-fluid body-content mt-5 pt-4 px-3 px-md-4\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3610, 60, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3670, 16, true);

WriteLiteral(">\r\n        <main");

EndContext("~/Views/Shared/_Layout.cshtml", 3670, 16, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3686, 12, true);

WriteLiteral(" role=\"main\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3686, 12, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3698, 13, true);

WriteLiteral(" class=\"pb-4\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3698, 13, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3711, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 3711, 3, true);

            
            #line 57 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
            
            
            #line default
            #line hidden
            
            #line 57 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
             if (hideLayout)
            {

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 3759, 20, true);

WriteLiteral("                <div");

EndContext("~/Views/Shared/_Layout.cshtml", 3759, 20, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3779, 72, true);

WriteLiteral(" class=\"auth-page-wrap d-flex justify-content-center align-items-center\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3779, 72, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3851, 27, true);

WriteLiteral(">\r\n                    <div");

EndContext("~/Views/Shared/_Layout.cshtml", 3851, 27, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3878, 49, true);

WriteLiteral(" class=\"auth-card p-5 rounded shadow-lg bg-white\"");

EndContext("~/Views/Shared/_Layout.cshtml", 3878, 49, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3927, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 3927, 3, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3930, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/Shared/_Layout.cshtml", 3930, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 3955, 12, false);

            
            #line 61 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                   Write(RenderBody());

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 3955, 12, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 3967, 54, true);

WriteLiteral("\r\n                    </div>\r\n                </div>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 3967, 54, true);

            
            #line 64 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 4069, 20, true);

WriteLiteral("                <div");

EndContext("~/Views/Shared/_Layout.cshtml", 4069, 20, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4089, 62, true);

WriteLiteral(" class=\"content-frame rounded-3 p-3 p-md-4 shadow-sm bg-white\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4089, 62, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4151, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 4151, 3, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4154, 20, true);

WriteLiteral("                    ");

EndContext("~/Views/Shared/_Layout.cshtml", 4154, 20, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4175, 12, false);

            
            #line 68 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
               Write(RenderBody());

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 4175, 12, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 4187, 26, true);

WriteLiteral("\r\n                </div>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 4187, 26, true);

            
            #line 70 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
            }

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 4228, 33, true);

WriteLiteral("        </main>\r\n    </div>\r\n\r\n\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 4228, 33, true);

            
            #line 75 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 75 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
     if (!hideLayout)
    {

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 4291, 15, true);

WriteLiteral("        <footer");

EndContext("~/Views/Shared/_Layout.cshtml", 4291, 15, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4306, 30, true);

WriteLiteral(" class=\"footer mt-5 pt-3 pb-2\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4306, 30, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4336, 19, true);

WriteLiteral(">\r\n            <div");

EndContext("~/Views/Shared/_Layout.cshtml", 4336, 19, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4355, 47, true);

WriteLiteral(" class=\"container text-center small text-muted\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4355, 47, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4402, 26, true);

WriteLiteral(">\r\n                &copy; ");

EndContext("~/Views/Shared/_Layout.cshtml", 4402, 26, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4429, 17, false);

            
            #line 79 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
                  Write(DateTime.Now.Year);

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 4429, 17, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 4446, 89, true);

WriteLiteral(" - FinTrack · Designed for modern workflow teams\r\n            </div>\r\n        </f" +
"ooter>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 4446, 89, true);

            
            #line 82 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
BeginContext("~/Views/Shared/_Layout.cshtml", 4542, 13, true);

WriteLiteral("\r\n    <script");

EndContext("~/Views/Shared/_Layout.cshtml", 4542, 13, true);

WriteAttribute("src", Tuple.Create(" src=\"", 4555), Tuple.Create("\"", 4607)
            
            #line 84 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 4561), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/jquery-1.10.2.min.js")
            
            #line default
            #line hidden
, 4561), false)
);

BeginContext("~/Views/Shared/_Layout.cshtml", 4608, 68, true);

WriteLiteral("></script>\r\n    <!-- Bootstrap 5 Bundle with Popper -->\r\n    <script");

EndContext("~/Views/Shared/_Layout.cshtml", 4608, 68, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4676, 83, true);

WriteLiteral(" src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.j" +
"s\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4676, 83, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4759, 84, true);

WriteLiteral(" integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cD" +
"fL\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4759, 84, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4843, 24, true);

WriteLiteral(" crossorigin=\"anonymous\"");

EndContext("~/Views/Shared/_Layout.cshtml", 4843, 24, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4867, 18, true);

WriteLiteral("></script>\r\n    \r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 4867, 18, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4885, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Shared/_Layout.cshtml", 4885, 4, true);

BeginContext("~/Views/Shared/_Layout.cshtml", 4890, 41, false);

            
            #line 88 "C:\projects\SOEEApp-main\SOEEApp\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
EndContext("~/Views/Shared/_Layout.cshtml", 4890, 41, false);

BeginContext("~/Views/Shared/_Layout.cshtml", 4931, 20, true);

WriteLiteral("\r\n</body>\r\n</html>\r\n");

EndContext("~/Views/Shared/_Layout.cshtml", 4931, 20, true);

        }
    }
}
