#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7BBC3833BD8615A26792C7A98844A029C99A0574"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_ProjectServiceMaps_Create_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.ProjectServiceMap> {
        
#line hidden
        
        public _Page_Views_ProjectServiceMaps_Create_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 2 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
  
    ViewBag.Title = "Create Project-Service Mapping";

            
            #line default
            #line hidden
BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 98, 43, true);

WriteLiteral("\n\n<h2>Create Project-Service Mapping</h2>\n\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 98, 43, true);

            
            #line 8 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 174, 23, false);

            
            #line 10 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 174, 23, false);

            
            #line 10 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
                            

            
            #line default
            #line hidden
BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 198, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 198, 8, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 206, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 206, 19, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 225, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 225, 2, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 227, 8, true);

WriteLiteral("        ");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 227, 8, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 236, 31, false);

            
            #line 12 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
   Write(Html.LabelFor(m => m.ProjectID));

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 236, 31, false);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 267, 1, true);

WriteLiteral("\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 267, 1, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 268, 8, true);

WriteLiteral("        ");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 268, 8, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 277, 119, false);

            
            #line 13 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
   Write(Html.DropDownListFor(m => m.ProjectID, (SelectList)ViewBag.Projects, "Select Project", new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 277, 119, false);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 396, 12, true);

WriteLiteral("\n    </div>\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 396, 12, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 408, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 408, 8, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 416, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 416, 19, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 435, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 435, 2, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 437, 8, true);

WriteLiteral("        ");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 437, 8, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 446, 35, false);

            
            #line 16 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
   Write(Html.LabelFor(m => m.ServiceTypeID));

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 446, 35, false);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 481, 1, true);

WriteLiteral("\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 481, 1, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 482, 8, true);

WriteLiteral("        ");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 482, 8, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 491, 153, false);

            
            #line 17 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
   Write(Html.DropDownListFor(m => m.ServiceTypeID, (SelectList)ViewBag.ServiceTypes, "Select Service", new { @class = "form-control", id = "serviceTypeSelect" }));

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 491, 153, false);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 644, 12, true);

WriteLiteral("\n    </div>\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 644, 12, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 656, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 656, 8, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 664, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 664, 19, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 683, 16, true);

WriteLiteral(">\n        <label");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 683, 16, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 699, 17, true);

WriteLiteral(" for=\"slabSelect\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 699, 17, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 716, 35, true);

WriteLiteral(">Slab Range</label>\n        <select");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 716, 35, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 751, 16, true);

WriteLiteral(" id=\"slabSelect\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 751, 16, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 767, 14, true);

WriteLiteral(" name=\"slabId\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 767, 14, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 781, 21, true);

WriteLiteral(" class=\"form-control\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 781, 21, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 802, 21, true);

WriteLiteral(">\n            <option");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 802, 21, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 823, 9, true);

WriteLiteral(" value=\"\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 823, 9, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 832, 22, true);

WriteLiteral(">Select Slab</option>\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 832, 22, true);

            
            #line 23 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
            
            
            #line default
            #line hidden
            
            #line 23 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
             foreach (var slab in (List<SelectListItem>)ViewBag.Slabs)
            {

            
            #line default
            #line hidden
BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 939, 23, true);

WriteLiteral("                <option");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 939, 23, true);

WriteAttribute("value", Tuple.Create(" value=\"", 962), Tuple.Create("\"", 981)
            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
, Tuple.Create(Tuple.Create("", 970), Tuple.Create<System.Object, System.Int32>(slab.Value
            
            #line default
            #line hidden
, 970), false)
);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 982, 1, true);

WriteLiteral(">");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 982, 1, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 984, 9, false);

            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
                                       Write(slab.Text);

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 984, 9, false);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 993, 10, true);

WriteLiteral("</option>\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 993, 10, true);

            
            #line 26 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
            }

            
            #line default
            #line hidden
BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1017, 29, true);

WriteLiteral("        </select>\n    </div>\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1017, 29, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1046, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1046, 8, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1054, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1054, 19, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1073, 56, true);

WriteLiteral(">\n        <label>Service Charge %</label>\n        <input");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1073, 56, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1129, 19, true);

WriteLiteral(" id=\"serviceCharge\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1129, 19, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1148, 21, true);

WriteLiteral(" class=\"form-control\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1148, 21, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1169, 9, true);

WriteLiteral(" readonly");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1169, 9, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1178, 10, true);

WriteLiteral(" value=\"-\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1178, 10, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1188, 15, true);

WriteLiteral(" />\n    </div>\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1188, 15, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1203, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1203, 8, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1211, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1211, 19, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1230, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1230, 2, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1232, 8, true);

WriteLiteral("        ");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1232, 8, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1241, 29, false);

            
            #line 34 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
   Write(Html.LabelFor(m => m.AddedOn));

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1241, 29, false);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1270, 1, true);

WriteLiteral("\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1270, 1, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1271, 8, true);

WriteLiteral("        ");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1271, 8, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1280, 97, false);

            
            #line 35 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
   Write(Html.TextBoxFor(m => m.AddedOn, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" }));

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1280, 97, false);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1377, 12, true);

WriteLiteral("\n    </div>\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1377, 12, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1389, 421, true);

WriteLiteral(@"    <script>
        function updateCharge() {
            var serviceTypeId = document.getElementById('serviceTypeSelect').value;
            var slabId = document.getElementById('slabSelect').value;
            var chargeInput = document.getElementById('serviceCharge');
            if (!serviceTypeId || !slabId) {
                chargeInput.value = '-';
                return;
            }

            $.getJSON('");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1389, 421, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1811, 59, false);

            
            #line 47 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
                  Write(Url.Action("GetServiceChargeBySlab", "ServiceTypeSlabMaps"));

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1811, 59, false);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 1870, 730, true);

WriteLiteral(@"', { serviceTypeId: serviceTypeId, slabId: slabId })
                .done(function (data) {
                    if (data.success) {
                        chargeInput.value = data.percentage + ' %';
                    } else {
                        chargeInput.value = 'Not mapped';
                    }
                })
                .fail(function () {
                    chargeInput.value = 'Error';
                });
        }

        document.addEventListener('DOMContentLoaded', function () {
            document.getElementById('serviceTypeSelect').addEventListener('change', updateCharge);
            document.getElementById('slabSelect').addEventListener('change', updateCharge);
        });
    </script>
");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 1870, 730, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 2600, 11, true);

WriteLiteral("    <button");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 2600, 11, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 2611, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 2611, 14, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 2625, 24, true);

WriteLiteral(" class=\"btn btn-success\"");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 2625, 24, true);

BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 2649, 15, true);

WriteLiteral(">Save</button>\n");

EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 2649, 15, true);

            
            #line 66 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
    
            
            #line default
            #line hidden
BeginContext("~/Views/ProjectServiceMaps/Create.cshtml", 2669, 82, false);

            
            #line 66 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
Write(Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" }));

            
            #line default
            #line hidden
EndContext("~/Views/ProjectServiceMaps/Create.cshtml", 2669, 82, false);

            
            #line 66 "C:\projects\SOEEApp-main\SOEEApp\Views\ProjectServiceMaps\Create.cshtml"
                                                                                       
}

            
            #line default
            #line hidden
        }
    }
}
