#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "F3C9A5B2699D0DE97897D63C4ECD6DB519D26E49"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_ServiceCostSlabs_Edit_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.ServiceCostSlab> {
        
#line hidden
        
        public _Page_Views_ServiceCostSlabs_Edit_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
  
    ViewBag.Title = "Edit Slab";

            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 80, 8, true);

WriteLiteral("\r\n\r\n<div");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 80, 8, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 88, 40, true);

WriteLiteral(" class=\"row justify-content-center mt-5\"");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 88, 40, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 128, 11, true);

WriteLiteral(">\r\n    <div");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 128, 11, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 139, 26, true);

WriteLiteral(" class=\"col-md-6 col-lg-5\"");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 139, 26, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 165, 15, true);

WriteLiteral(">\r\n        <div");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 165, 15, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 180, 32, true);

WriteLiteral(" class=\"card shadow-sm border-0\"");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 180, 32, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 212, 19, true);

WriteLiteral(">\r\n            <div");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 212, 19, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 231, 29, true);

WriteLiteral(" class=\"card-header bg-white\"");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 231, 29, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 260, 22, true);

WriteLiteral(">\r\n                <h4");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 260, 22, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 282, 26, true);

WriteLiteral(" class=\"mb-0 text-primary\"");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 282, 26, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 308, 53, true);

WriteLiteral(">Edit Slab</h4>\r\n            </div>\r\n            <div");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 308, 53, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 361, 22, true);

WriteLiteral(" class=\"card-body p-4\"");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 361, 22, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 383, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 383, 3, true);

            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
                
            
            #line default
            #line hidden
            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
                 using (Html.BeginForm())
                {
                    
            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 469, 23, false);

            
            #line 16 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
               Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 469, 23, false);

            
            #line 16 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
                                            
                    
            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 515, 83, false);

            
            #line 17 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
               Write(Html.ValidationSummary(true, "", new { @class = "text-danger alert alert-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 515, 83, false);

            
            #line 17 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
                                                                                                        
                    
            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 621, 33, false);

            
            #line 18 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
               Write(Html.HiddenFor(model => model.Id));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 621, 33, false);

            
            #line 18 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
                                                      


            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 658, 24, true);

WriteLiteral("                    <div");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 658, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 682, 13, true);

WriteLiteral(" class=\"mb-3\"");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 682, 13, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 695, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 695, 3, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 698, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 698, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 723, 62, false);

            
            #line 21 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
                   Write(Html.LabelFor(m => m.MinAmount, new { @class = "form-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 723, 62, false);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 785, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 785, 2, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 787, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 787, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 812, 66, false);

            
            #line 22 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
                   Write(Html.TextBoxFor(m => m.MinAmount, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 812, 66, false);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 878, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 878, 2, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 880, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 880, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 905, 85, false);

            
            #line 23 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.MinAmount, "", new { @class = "text-danger small" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 905, 85, false);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 990, 30, true);

WriteLiteral("\r\n                    </div>\r\n");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 990, 30, true);

            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"


            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1022, 24, true);

WriteLiteral("                    <div");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1022, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1046, 13, true);

WriteLiteral(" class=\"mb-3\"");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1046, 13, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1059, 3, true);

WriteLiteral(">\r\n");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1059, 3, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1062, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1062, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1087, 62, false);

            
            #line 27 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
                   Write(Html.LabelFor(m => m.MaxAmount, new { @class = "form-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1087, 62, false);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1149, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1149, 2, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1151, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1151, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1176, 66, false);

            
            #line 28 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
                   Write(Html.TextBoxFor(m => m.MaxAmount, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1176, 66, false);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1242, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1242, 2, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1244, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1244, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1269, 85, false);

            
            #line 29 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.MaxAmount, "", new { @class = "text-danger small" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1269, 85, false);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1354, 30, true);

WriteLiteral("\r\n                    </div>\r\n");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1354, 30, true);

            
            #line 31 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"

                    
            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1407, 39, false);

            
            #line 32 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
               Write(Html.HiddenFor(model => model.IsActive));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1407, 39, false);

            
            #line 32 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
                                                            


            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1450, 24, true);

WriteLiteral("                    <div");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1450, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1474, 26, true);

WriteLiteral(" class=\"d-grid gap-2 mt-4\"");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1474, 26, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1500, 33, true);

WriteLiteral(">\r\n                        <input");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1500, 33, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1533, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1533, 14, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1547, 21, true);

WriteLiteral(" value=\"Save Changes\"");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1547, 21, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1568, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1568, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1592, 5, true);

WriteLiteral(" />\r\n");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1592, 5, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1597, 24, true);

WriteLiteral("                        ");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1597, 24, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1622, 89, false);

            
            #line 36 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
                   Write(Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-light text-secondary" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1622, 89, false);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1711, 30, true);

WriteLiteral("\r\n                    </div>\r\n");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1711, 30, true);

            
            #line 38 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
                }

            
            #line default
            #line hidden
BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1760, 58, true);

WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1760, 58, true);

DefineSection("Scripts", () => {

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1836, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1836, 2, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1838, 4, true);

WriteLiteral("    ");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1838, 4, true);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1843, 37, false);

            
            #line 45 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceCostSlabs\Edit.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1843, 37, false);

BeginContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1880, 2, true);

WriteLiteral("\r\n");

EndContext("~/Views/ServiceCostSlabs/Edit.cshtml", 1880, 2, true);

});

        }
    }
}
