#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "DFEDF81E690B4CAC110D3C306E829128AE6EBDF3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Customers_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<SOEEApp.Models.Customer>> {
        
#line hidden
        
        public _Page_Views_Customers_Index_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/Customers/Index.cshtml", 45, 4, true);

WriteLiteral("<div");

EndContext("~/Views/Customers/Index.cshtml", 45, 4, true);

BeginContext("~/Views/Customers/Index.cshtml", 49, 36, true);

WriteLiteral(" class=\"row mb-4 align-items-center\"");

EndContext("~/Views/Customers/Index.cshtml", 49, 36, true);

BeginContext("~/Views/Customers/Index.cshtml", 85, 10, true);

WriteLiteral(">\n    <div");

EndContext("~/Views/Customers/Index.cshtml", 85, 10, true);

BeginContext("~/Views/Customers/Index.cshtml", 95, 12, true);

WriteLiteral(" class=\"col\"");

EndContext("~/Views/Customers/Index.cshtml", 95, 12, true);

BeginContext("~/Views/Customers/Index.cshtml", 107, 13, true);

WriteLiteral(">\n        <h2");

EndContext("~/Views/Customers/Index.cshtml", 107, 13, true);

BeginContext("~/Views/Customers/Index.cshtml", 120, 13, true);

WriteLiteral(" class=\"mb-0\"");

EndContext("~/Views/Customers/Index.cshtml", 120, 13, true);

BeginContext("~/Views/Customers/Index.cshtml", 133, 35, true);

WriteLiteral(">Customers</h2>\n    </div>\n    <div");

EndContext("~/Views/Customers/Index.cshtml", 133, 35, true);

BeginContext("~/Views/Customers/Index.cshtml", 168, 17, true);

WriteLiteral(" class=\"col-auto\"");

EndContext("~/Views/Customers/Index.cshtml", 168, 17, true);

BeginContext("~/Views/Customers/Index.cshtml", 185, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Customers/Index.cshtml", 185, 2, true);

BeginContext("~/Views/Customers/Index.cshtml", 187, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Customers/Index.cshtml", 187, 8, true);

BeginContext("~/Views/Customers/Index.cshtml", 196, 87, false);

            
            #line 8 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Index.cshtml"
   Write(Html.ActionLink("Add New Customer", "Create", null, new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Index.cshtml", 196, 87, false);

BeginContext("~/Views/Customers/Index.cshtml", 283, 24, true);

WriteLiteral("\n    </div>\n</div>\n\n<div");

EndContext("~/Views/Customers/Index.cshtml", 283, 24, true);

BeginContext("~/Views/Customers/Index.cshtml", 307, 23, true);

WriteLiteral(" class=\"card shadow-sm\"");

EndContext("~/Views/Customers/Index.cshtml", 307, 23, true);

BeginContext("~/Views/Customers/Index.cshtml", 330, 10, true);

WriteLiteral(">\n    <div");

EndContext("~/Views/Customers/Index.cshtml", 330, 10, true);

BeginContext("~/Views/Customers/Index.cshtml", 340, 25, true);

WriteLiteral(" class=\"table-responsive\"");

EndContext("~/Views/Customers/Index.cshtml", 340, 25, true);

BeginContext("~/Views/Customers/Index.cshtml", 365, 16, true);

WriteLiteral(">\n        <table");

EndContext("~/Views/Customers/Index.cshtml", 365, 16, true);

BeginContext("~/Views/Customers/Index.cshtml", 381, 44, true);

WriteLiteral(" class=\"table table-hover align-middle mb-0\"");

EndContext("~/Views/Customers/Index.cshtml", 381, 44, true);

BeginContext("~/Views/Customers/Index.cshtml", 425, 20, true);

WriteLiteral(">\n            <thead");

EndContext("~/Views/Customers/Index.cshtml", 425, 20, true);

BeginContext("~/Views/Customers/Index.cshtml", 445, 20, true);

WriteLiteral(" class=\"table-light\"");

EndContext("~/Views/Customers/Index.cshtml", 445, 20, true);

BeginContext("~/Views/Customers/Index.cshtml", 465, 198, true);

WriteLiteral(">\n                <tr>\n                    <th>Customer</th>\n                    " +
"<th>Email</th>\n                    <th>Contact Person</th>\n                    <" +
"th>Phone</th>\n                    <th");

EndContext("~/Views/Customers/Index.cshtml", 465, 198, true);

BeginContext("~/Views/Customers/Index.cshtml", 663, 17, true);

WriteLiteral(" class=\"text-end\"");

EndContext("~/Views/Customers/Index.cshtml", 663, 17, true);

BeginContext("~/Views/Customers/Index.cshtml", 680, 77, true);

WriteLiteral(">Actions</th>\n                </tr>\n            </thead>\n            <tbody>\n");

EndContext("~/Views/Customers/Index.cshtml", 680, 77, true);

            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Index.cshtml"
                 foreach (var item in Model)
                {

            
            #line default
            #line hidden
BeginContext("~/Views/Customers/Index.cshtml", 820, 53, true);

WriteLiteral("                    <tr>\n                        <td>");

EndContext("~/Views/Customers/Index.cshtml", 820, 53, true);

BeginContext("~/Views/Customers/Index.cshtml", 874, 17, false);

            
            #line 28 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Index.cshtml"
                       Write(item.CustomerName);

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Index.cshtml", 874, 17, false);

BeginContext("~/Views/Customers/Index.cshtml", 891, 34, true);

WriteLiteral("</td>\n                        <td>");

EndContext("~/Views/Customers/Index.cshtml", 891, 34, true);

BeginContext("~/Views/Customers/Index.cshtml", 926, 10, false);

            
            #line 29 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Index.cshtml"
                       Write(item.Email);

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Index.cshtml", 926, 10, false);

BeginContext("~/Views/Customers/Index.cshtml", 936, 34, true);

WriteLiteral("</td>\n                        <td>");

EndContext("~/Views/Customers/Index.cshtml", 936, 34, true);

BeginContext("~/Views/Customers/Index.cshtml", 971, 18, false);

            
            #line 30 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Index.cshtml"
                       Write(item.ContactPerson);

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Index.cshtml", 971, 18, false);

BeginContext("~/Views/Customers/Index.cshtml", 989, 34, true);

WriteLiteral("</td>\n                        <td>");

EndContext("~/Views/Customers/Index.cshtml", 989, 34, true);

BeginContext("~/Views/Customers/Index.cshtml", 1024, 16, false);

            
            #line 31 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Index.cshtml"
                       Write(item.PhoneNumber);

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Index.cshtml", 1024, 16, false);

BeginContext("~/Views/Customers/Index.cshtml", 1040, 33, true);

WriteLiteral("</td>\n                        <td");

EndContext("~/Views/Customers/Index.cshtml", 1040, 33, true);

BeginContext("~/Views/Customers/Index.cshtml", 1073, 17, true);

WriteLiteral(" class=\"text-end\"");

EndContext("~/Views/Customers/Index.cshtml", 1073, 17, true);

BeginContext("~/Views/Customers/Index.cshtml", 1090, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Customers/Index.cshtml", 1090, 2, true);

BeginContext("~/Views/Customers/Index.cshtml", 1092, 28, true);

WriteLiteral("                            ");

EndContext("~/Views/Customers/Index.cshtml", 1092, 28, true);

BeginContext("~/Views/Customers/Index.cshtml", 1121, 117, false);

            
            #line 33 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Index.cshtml"
                       Write(Html.ActionLink("Edit", "Edit", new { id = item.CustomerID }, new { @class = "btn btn-sm btn-outline-primary me-1" }));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Index.cshtml", 1121, 117, false);

BeginContext("~/Views/Customers/Index.cshtml", 1238, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Customers/Index.cshtml", 1238, 1, true);

BeginContext("~/Views/Customers/Index.cshtml", 1239, 28, true);

WriteLiteral("                            ");

EndContext("~/Views/Customers/Index.cshtml", 1239, 28, true);

BeginContext("~/Views/Customers/Index.cshtml", 1268, 115, false);

            
            #line 34 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Index.cshtml"
                       Write(Html.ActionLink("Delete", "Delete", new { id = item.CustomerID }, new { @class = "btn btn-sm btn-outline-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Index.cshtml", 1268, 115, false);

BeginContext("~/Views/Customers/Index.cshtml", 1383, 57, true);

WriteLiteral("\n                        </td>\n                    </tr>\n");

EndContext("~/Views/Customers/Index.cshtml", 1383, 57, true);

            
            #line 37 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Index.cshtml"
                }

            
            #line default
            #line hidden
BeginContext("~/Views/Customers/Index.cshtml", 1458, 56, true);

WriteLiteral("            </tbody>\n        </table>\n    </div>\n</div>\n");

EndContext("~/Views/Customers/Index.cshtml", 1458, 56, true);

        }
    }
}
