#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Delete.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9E36024BA448CD0B39CEB78F72B28F434B3BBBC8"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Customers_Delete_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.Customer> {
        
#line hidden
        
        public _Page_Views_Customers_Delete_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Delete.cshtml"
  
    ViewBag.Title = "Delete Customer";

            
            #line default
            #line hidden
BeginContext("~/Views/Customers/Delete.cshtml", 75, 32, true);

WriteLiteral("\n\n<h2>Delete Customer</h2>\n\n<div");

EndContext("~/Views/Customers/Delete.cshtml", 75, 32, true);

BeginContext("~/Views/Customers/Delete.cshtml", 107, 33, true);

WriteLiteral(" class=\"card card-body shadow-sm\"");

EndContext("~/Views/Customers/Delete.cshtml", 107, 33, true);

BeginContext("~/Views/Customers/Delete.cshtml", 140, 24, true);

WriteLiteral(">\n    <p>Delete <strong>");

EndContext("~/Views/Customers/Delete.cshtml", 140, 24, true);

BeginContext("~/Views/Customers/Delete.cshtml", 165, 18, false);

            
            #line 10 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Delete.cshtml"
                 Write(Model.CustomerName);

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Delete.cshtml", 165, 18, false);

BeginContext("~/Views/Customers/Delete.cshtml", 183, 22, true);

WriteLiteral("</strong>?</p>\n    <dl");

EndContext("~/Views/Customers/Delete.cshtml", 183, 22, true);

BeginContext("~/Views/Customers/Delete.cshtml", 205, 12, true);

WriteLiteral(" class=\"row\"");

EndContext("~/Views/Customers/Delete.cshtml", 205, 12, true);

BeginContext("~/Views/Customers/Delete.cshtml", 217, 13, true);

WriteLiteral(">\n        <dt");

EndContext("~/Views/Customers/Delete.cshtml", 217, 13, true);

BeginContext("~/Views/Customers/Delete.cshtml", 230, 17, true);

WriteLiteral(" class=\"col-sm-3\"");

EndContext("~/Views/Customers/Delete.cshtml", 230, 17, true);

BeginContext("~/Views/Customers/Delete.cshtml", 247, 23, true);

WriteLiteral(">Email</dt>\n        <dd");

EndContext("~/Views/Customers/Delete.cshtml", 247, 23, true);

BeginContext("~/Views/Customers/Delete.cshtml", 270, 17, true);

WriteLiteral(" class=\"col-sm-9\"");

EndContext("~/Views/Customers/Delete.cshtml", 270, 17, true);

BeginContext("~/Views/Customers/Delete.cshtml", 287, 1, true);

WriteLiteral(">");

EndContext("~/Views/Customers/Delete.cshtml", 287, 1, true);

BeginContext("~/Views/Customers/Delete.cshtml", 289, 11, false);

            
            #line 13 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Delete.cshtml"
                        Write(Model.Email);

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Delete.cshtml", 289, 11, false);

BeginContext("~/Views/Customers/Delete.cshtml", 300, 17, true);

WriteLiteral("</dd>\n        <dt");

EndContext("~/Views/Customers/Delete.cshtml", 300, 17, true);

BeginContext("~/Views/Customers/Delete.cshtml", 317, 17, true);

WriteLiteral(" class=\"col-sm-3\"");

EndContext("~/Views/Customers/Delete.cshtml", 317, 17, true);

BeginContext("~/Views/Customers/Delete.cshtml", 334, 32, true);

WriteLiteral(">Contact Person</dt>\n        <dd");

EndContext("~/Views/Customers/Delete.cshtml", 334, 32, true);

BeginContext("~/Views/Customers/Delete.cshtml", 366, 17, true);

WriteLiteral(" class=\"col-sm-9\"");

EndContext("~/Views/Customers/Delete.cshtml", 366, 17, true);

BeginContext("~/Views/Customers/Delete.cshtml", 383, 1, true);

WriteLiteral(">");

EndContext("~/Views/Customers/Delete.cshtml", 383, 1, true);

BeginContext("~/Views/Customers/Delete.cshtml", 385, 19, false);

            
            #line 15 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Delete.cshtml"
                        Write(Model.ContactPerson);

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Delete.cshtml", 385, 19, false);

BeginContext("~/Views/Customers/Delete.cshtml", 404, 17, true);

WriteLiteral("</dd>\n        <dt");

EndContext("~/Views/Customers/Delete.cshtml", 404, 17, true);

BeginContext("~/Views/Customers/Delete.cshtml", 421, 17, true);

WriteLiteral(" class=\"col-sm-3\"");

EndContext("~/Views/Customers/Delete.cshtml", 421, 17, true);

BeginContext("~/Views/Customers/Delete.cshtml", 438, 23, true);

WriteLiteral(">Phone</dt>\n        <dd");

EndContext("~/Views/Customers/Delete.cshtml", 438, 23, true);

BeginContext("~/Views/Customers/Delete.cshtml", 461, 17, true);

WriteLiteral(" class=\"col-sm-9\"");

EndContext("~/Views/Customers/Delete.cshtml", 461, 17, true);

BeginContext("~/Views/Customers/Delete.cshtml", 478, 1, true);

WriteLiteral(">");

EndContext("~/Views/Customers/Delete.cshtml", 478, 1, true);

BeginContext("~/Views/Customers/Delete.cshtml", 480, 17, false);

            
            #line 17 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Delete.cshtml"
                        Write(Model.PhoneNumber);

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Delete.cshtml", 480, 17, false);

BeginContext("~/Views/Customers/Delete.cshtml", 497, 17, true);

WriteLiteral("</dd>\n    </dl>\n\n");

EndContext("~/Views/Customers/Delete.cshtml", 497, 17, true);

            
            #line 20 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Delete.cshtml"
    
            
            #line default
            #line hidden
            
            #line 20 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Delete.cshtml"
     using (Html.BeginForm())
    {
        
            
            #line default
            #line hidden
BeginContext("~/Views/Customers/Delete.cshtml", 559, 23, false);

            
            #line 22 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Delete.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Delete.cshtml", 559, 23, false);

            
            #line 22 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Delete.cshtml"
                                

            
            #line default
            #line hidden
BeginContext("~/Views/Customers/Delete.cshtml", 583, 12, true);

WriteLiteral("        <div");

EndContext("~/Views/Customers/Delete.cshtml", 583, 12, true);

BeginContext("~/Views/Customers/Delete.cshtml", 595, 21, true);

WriteLiteral(" class=\"d-flex gap-2\"");

EndContext("~/Views/Customers/Delete.cshtml", 595, 21, true);

BeginContext("~/Views/Customers/Delete.cshtml", 616, 21, true);

WriteLiteral(">\n            <button");

EndContext("~/Views/Customers/Delete.cshtml", 616, 21, true);

BeginContext("~/Views/Customers/Delete.cshtml", 637, 23, true);

WriteLiteral(" class=\"btn btn-danger\"");

EndContext("~/Views/Customers/Delete.cshtml", 637, 23, true);

BeginContext("~/Views/Customers/Delete.cshtml", 660, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Customers/Delete.cshtml", 660, 14, true);

BeginContext("~/Views/Customers/Delete.cshtml", 674, 31, true);

WriteLiteral(">Delete</button>\n            <a");

EndContext("~/Views/Customers/Delete.cshtml", 674, 31, true);

WriteAttribute("href", Tuple.Create(" href=\"", 705), Tuple.Create("\"", 732)
            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Delete.cshtml"
, Tuple.Create(Tuple.Create("", 712), Tuple.Create<System.Object, System.Int32>(Url.Action("Index")
            
            #line default
            #line hidden
, 712), false)
);

BeginContext("~/Views/Customers/Delete.cshtml", 733, 34, true);

WriteLiteral(" class=\"btn btn-outline-secondary\"");

EndContext("~/Views/Customers/Delete.cshtml", 733, 34, true);

BeginContext("~/Views/Customers/Delete.cshtml", 767, 27, true);

WriteLiteral(">Cancel</a>\n        </div>\n");

EndContext("~/Views/Customers/Delete.cshtml", 767, 27, true);

            
            #line 27 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Delete.cshtml"
    }

            
            #line default
            #line hidden
BeginContext("~/Views/Customers/Delete.cshtml", 800, 7, true);

WriteLiteral("</div>\n");

EndContext("~/Views/Customers/Delete.cshtml", 800, 7, true);

        }
    }
}
