#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Home\About.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "01880814E9A6D5EB77BA0C823C7588549C14C9FB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Home_About_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden
        
        public _Page_Views_Home_About_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "C:\projects\SOEEApp-main\SOEEApp\Views\Home\About.cshtml"
  
    ViewBag.Title = "About";

            
            #line default
            #line hidden
BeginContext("~/Views/Home/About.cshtml", 33, 5, true);

WriteLiteral("\n<h2>");

EndContext("~/Views/Home/About.cshtml", 33, 5, true);

BeginContext("~/Views/Home/About.cshtml", 39, 13, false);

            
            #line 4 "C:\projects\SOEEApp-main\SOEEApp\Views\Home\About.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Home/About.cshtml", 39, 13, false);

BeginContext("~/Views/Home/About.cshtml", 52, 11, true);

WriteLiteral(".</h2>\n<h3>");

EndContext("~/Views/Home/About.cshtml", 52, 11, true);

BeginContext("~/Views/Home/About.cshtml", 64, 15, false);

            
            #line 5 "C:\projects\SOEEApp-main\SOEEApp\Views\Home\About.cshtml"
Write(ViewBag.Message);

            
            #line default
            #line hidden
EndContext("~/Views/Home/About.cshtml", 64, 15, false);

BeginContext("~/Views/Home/About.cshtml", 79, 63, true);

WriteLiteral("</h3>\n\n<p>Use this area to provide additional information.</p>\n");

EndContext("~/Views/Home/About.cshtml", 79, 63, true);

        }
    }
}
