#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\_ViewStart.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "683F65E7C2CEE7E587BE69A0C5AA97D79468167F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views__ViewStart_cshtml : System.Web.Mvc.ViewStartPage {
        
#line hidden
        
        public _Page_Views__ViewStart_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 1 "C:\projects\SOEEApp-main\SOEEApp\Views\_ViewStart.cshtml"
  
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
BeginContext("~/Views/_ViewStart.cshtml", 50, 1, true);

WriteLiteral("\n");

EndContext("~/Views/_ViewStart.cshtml", 50, 1, true);

        }
    }
}
