#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5A6AE84A8AFBC7EA14FB47EF23B8B21A5B4DD281"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Account_ResetPassword_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.ResetPasswordViewModel> {
        
#line hidden
        
        public _Page_Views_Account_ResetPassword_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 2 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
  
    ViewBag.Title = "Reset password";

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ResetPassword.cshtml", 87, 6, true);

WriteLiteral("\n\n<h2>");

EndContext("~/Views/Account/ResetPassword.cshtml", 87, 6, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 94, 13, false);

            
            #line 6 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
EndContext("~/Views/Account/ResetPassword.cshtml", 94, 13, false);

BeginContext("~/Views/Account/ResetPassword.cshtml", 107, 8, true);

WriteLiteral(".</h2>\n\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 107, 8, true);

            
            #line 8 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
 using (Html.BeginForm("ResetPassword", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    
            
            #line default
            #line hidden
BeginContext("~/Views/Account/ResetPassword.cshtml", 242, 23, false);

            
            #line 10 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Account/ResetPassword.cshtml", 242, 23, false);

            
            #line 10 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
                            

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ResetPassword.cshtml", 266, 34, true);

WriteLiteral("    <h4>Reset your password.</h4>\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 266, 34, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 300, 11, true);

WriteLiteral("    <hr />\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 300, 11, true);

            
            #line 13 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
    
            
            #line default
            #line hidden
BeginContext("~/Views/Account/ResetPassword.cshtml", 316, 58, false);

            
            #line 13 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
Write(Html.ValidationSummary("", new { @class = "text-danger" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ResetPassword.cshtml", 316, 58, false);

            
            #line 13 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
                                                               
    
            
            #line default
            #line hidden
BeginContext("~/Views/Account/ResetPassword.cshtml", 380, 35, false);

            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
Write(Html.HiddenFor(model => model.Code));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ResetPassword.cshtml", 380, 35, false);

            
            #line 14 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
                                        

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ResetPassword.cshtml", 416, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/ResetPassword.cshtml", 416, 8, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 424, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/ResetPassword.cshtml", 424, 19, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 443, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 443, 2, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 445, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/ResetPassword.cshtml", 445, 8, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 454, 70, false);

            
            #line 16 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
   Write(Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ResetPassword.cshtml", 454, 70, false);

BeginContext("~/Views/Account/ResetPassword.cshtml", 524, 13, true);

WriteLiteral("\n        <div");

EndContext("~/Views/Account/ResetPassword.cshtml", 524, 13, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 537, 18, true);

WriteLiteral(" class=\"col-md-10\"");

EndContext("~/Views/Account/ResetPassword.cshtml", 537, 18, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 555, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 555, 2, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 557, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/ResetPassword.cshtml", 557, 12, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 570, 62, false);

            
            #line 18 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
       Write(Html.TextBoxFor(m => m.Email, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ResetPassword.cshtml", 570, 62, false);

BeginContext("~/Views/Account/ResetPassword.cshtml", 632, 27, true);

WriteLiteral("\n        </div>\n    </div>\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 632, 27, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 659, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/ResetPassword.cshtml", 659, 8, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 667, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/ResetPassword.cshtml", 667, 19, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 686, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 686, 2, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 688, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/ResetPassword.cshtml", 688, 8, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 697, 73, false);

            
            #line 22 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
   Write(Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ResetPassword.cshtml", 697, 73, false);

BeginContext("~/Views/Account/ResetPassword.cshtml", 770, 13, true);

WriteLiteral("\n        <div");

EndContext("~/Views/Account/ResetPassword.cshtml", 770, 13, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 783, 18, true);

WriteLiteral(" class=\"col-md-10\"");

EndContext("~/Views/Account/ResetPassword.cshtml", 783, 18, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 801, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 801, 2, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 803, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/ResetPassword.cshtml", 803, 12, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 816, 66, false);

            
            #line 24 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
       Write(Html.PasswordFor(m => m.Password, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ResetPassword.cshtml", 816, 66, false);

BeginContext("~/Views/Account/ResetPassword.cshtml", 882, 27, true);

WriteLiteral("\n        </div>\n    </div>\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 882, 27, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 909, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/ResetPassword.cshtml", 909, 8, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 917, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/ResetPassword.cshtml", 917, 19, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 936, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 936, 2, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 938, 8, true);

WriteLiteral("        ");

EndContext("~/Views/Account/ResetPassword.cshtml", 938, 8, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 947, 80, false);

            
            #line 28 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
   Write(Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ResetPassword.cshtml", 947, 80, false);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1027, 13, true);

WriteLiteral("\n        <div");

EndContext("~/Views/Account/ResetPassword.cshtml", 1027, 13, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1040, 18, true);

WriteLiteral(" class=\"col-md-10\"");

EndContext("~/Views/Account/ResetPassword.cshtml", 1040, 18, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1058, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 1058, 2, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1060, 12, true);

WriteLiteral("            ");

EndContext("~/Views/Account/ResetPassword.cshtml", 1060, 12, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1073, 73, false);

            
            #line 30 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
       Write(Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ResetPassword.cshtml", 1073, 73, false);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1146, 27, true);

WriteLiteral("\n        </div>\n    </div>\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 1146, 27, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1173, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Account/ResetPassword.cshtml", 1173, 8, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1181, 19, true);

WriteLiteral(" class=\"form-group\"");

EndContext("~/Views/Account/ResetPassword.cshtml", 1181, 19, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1200, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Account/ResetPassword.cshtml", 1200, 14, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1214, 34, true);

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

EndContext("~/Views/Account/ResetPassword.cshtml", 1214, 34, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1248, 20, true);

WriteLiteral(">\n            <input");

EndContext("~/Views/Account/ResetPassword.cshtml", 1248, 20, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1268, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Account/ResetPassword.cshtml", 1268, 14, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1282, 24, true);

WriteLiteral(" class=\"btn btn-default\"");

EndContext("~/Views/Account/ResetPassword.cshtml", 1282, 24, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1306, 14, true);

WriteLiteral(" value=\"Reset\"");

EndContext("~/Views/Account/ResetPassword.cshtml", 1306, 14, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1320, 30, true);

WriteLiteral(" />\n        </div>\n    </div>\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 1320, 30, true);

            
            #line 38 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/Account/ResetPassword.cshtml", 1352, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 1352, 1, true);

DefineSection("Scripts", () => {

BeginContext("~/Views/Account/ResetPassword.cshtml", 1371, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 1371, 1, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1372, 4, true);

WriteLiteral("    ");

EndContext("~/Views/Account/ResetPassword.cshtml", 1372, 4, true);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1377, 37, false);

            
            #line 41 "C:\projects\SOEEApp-main\SOEEApp\Views\Account\ResetPassword.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
EndContext("~/Views/Account/ResetPassword.cshtml", 1377, 37, false);

BeginContext("~/Views/Account/ResetPassword.cshtml", 1414, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Account/ResetPassword.cshtml", 1414, 1, true);

});

        }
    }
}
