#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "30141D922E2324F967C1DFE7DA8FC4AF9119AF89"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_Customers_Edit_cshtml : System.Web.Mvc.WebViewPage<SOEEApp.Models.Customer> {
        
#line hidden
        
        public _Page_Views_Customers_Edit_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 3 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
  
    ViewBag.Title = "Edit Customer";

            
            #line default
            #line hidden
BeginContext("~/Views/Customers/Edit.cshtml", 73, 26, true);

WriteLiteral("\n\n<h2>Edit Customer</h2>\n\n");

EndContext("~/Views/Customers/Edit.cshtml", 73, 26, true);

            
            #line 9 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
BeginContext("~/Views/Customers/Edit.cshtml", 132, 23, false);

            
            #line 11 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Edit.cshtml", 132, 23, false);

            
            #line 11 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
                            
    
            
            #line default
            #line hidden
BeginContext("~/Views/Customers/Edit.cshtml", 161, 33, false);

            
            #line 12 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
Write(Html.HiddenFor(m => m.CustomerID));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Edit.cshtml", 161, 33, false);

            
            #line 12 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
                                      


            
            #line default
            #line hidden
BeginContext("~/Views/Customers/Edit.cshtml", 196, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/Customers/Edit.cshtml", 196, 8, true);

BeginContext("~/Views/Customers/Edit.cshtml", 204, 33, true);

WriteLiteral(" class=\"card card-body shadow-sm\"");

EndContext("~/Views/Customers/Edit.cshtml", 204, 33, true);

BeginContext("~/Views/Customers/Edit.cshtml", 237, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/Customers/Edit.cshtml", 237, 14, true);

BeginContext("~/Views/Customers/Edit.cshtml", 251, 16, true);

WriteLiteral(" class=\"row g-3\"");

EndContext("~/Views/Customers/Edit.cshtml", 251, 16, true);

BeginContext("~/Views/Customers/Edit.cshtml", 267, 18, true);

WriteLiteral(">\n            <div");

EndContext("~/Views/Customers/Edit.cshtml", 267, 18, true);

BeginContext("~/Views/Customers/Edit.cshtml", 285, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Customers/Edit.cshtml", 285, 17, true);

BeginContext("~/Views/Customers/Edit.cshtml", 302, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Customers/Edit.cshtml", 302, 2, true);

BeginContext("~/Views/Customers/Edit.cshtml", 304, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Edit.cshtml", 304, 16, true);

BeginContext("~/Views/Customers/Edit.cshtml", 321, 34, false);

            
            #line 17 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
           Write(Html.LabelFor(m => m.CustomerName));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Edit.cshtml", 321, 34, false);

BeginContext("~/Views/Customers/Edit.cshtml", 355, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Customers/Edit.cshtml", 355, 1, true);

BeginContext("~/Views/Customers/Edit.cshtml", 356, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Edit.cshtml", 356, 16, true);

BeginContext("~/Views/Customers/Edit.cshtml", 373, 69, false);

            
            #line 18 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
           Write(Html.TextBoxFor(m => m.CustomerName, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Edit.cshtml", 373, 69, false);

BeginContext("~/Views/Customers/Edit.cshtml", 442, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/Customers/Edit.cshtml", 442, 36, true);

BeginContext("~/Views/Customers/Edit.cshtml", 478, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Customers/Edit.cshtml", 478, 17, true);

BeginContext("~/Views/Customers/Edit.cshtml", 495, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Customers/Edit.cshtml", 495, 2, true);

BeginContext("~/Views/Customers/Edit.cshtml", 497, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Edit.cshtml", 497, 16, true);

BeginContext("~/Views/Customers/Edit.cshtml", 514, 27, false);

            
            #line 21 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
           Write(Html.LabelFor(m => m.Email));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Edit.cshtml", 514, 27, false);

BeginContext("~/Views/Customers/Edit.cshtml", 541, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Customers/Edit.cshtml", 541, 1, true);

BeginContext("~/Views/Customers/Edit.cshtml", 542, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Edit.cshtml", 542, 16, true);

BeginContext("~/Views/Customers/Edit.cshtml", 559, 78, false);

            
            #line 22 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
           Write(Html.TextBoxFor(m => m.Email, new { @class = "form-control", type = "email" }));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Edit.cshtml", 559, 78, false);

BeginContext("~/Views/Customers/Edit.cshtml", 637, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/Customers/Edit.cshtml", 637, 36, true);

BeginContext("~/Views/Customers/Edit.cshtml", 673, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Customers/Edit.cshtml", 673, 17, true);

BeginContext("~/Views/Customers/Edit.cshtml", 690, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Customers/Edit.cshtml", 690, 2, true);

BeginContext("~/Views/Customers/Edit.cshtml", 692, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Edit.cshtml", 692, 16, true);

BeginContext("~/Views/Customers/Edit.cshtml", 709, 35, false);

            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
           Write(Html.LabelFor(m => m.ContactPerson));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Edit.cshtml", 709, 35, false);

BeginContext("~/Views/Customers/Edit.cshtml", 744, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Customers/Edit.cshtml", 744, 1, true);

BeginContext("~/Views/Customers/Edit.cshtml", 745, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Edit.cshtml", 745, 16, true);

BeginContext("~/Views/Customers/Edit.cshtml", 762, 70, false);

            
            #line 26 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
           Write(Html.TextBoxFor(m => m.ContactPerson, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Edit.cshtml", 762, 70, false);

BeginContext("~/Views/Customers/Edit.cshtml", 832, 36, true);

WriteLiteral("\n            </div>\n            <div");

EndContext("~/Views/Customers/Edit.cshtml", 832, 36, true);

BeginContext("~/Views/Customers/Edit.cshtml", 868, 17, true);

WriteLiteral(" class=\"col-md-6\"");

EndContext("~/Views/Customers/Edit.cshtml", 868, 17, true);

BeginContext("~/Views/Customers/Edit.cshtml", 885, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/Customers/Edit.cshtml", 885, 2, true);

BeginContext("~/Views/Customers/Edit.cshtml", 887, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Edit.cshtml", 887, 16, true);

BeginContext("~/Views/Customers/Edit.cshtml", 904, 33, false);

            
            #line 29 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
           Write(Html.LabelFor(m => m.PhoneNumber));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Edit.cshtml", 904, 33, false);

BeginContext("~/Views/Customers/Edit.cshtml", 937, 1, true);

WriteLiteral("\n");

EndContext("~/Views/Customers/Edit.cshtml", 937, 1, true);

BeginContext("~/Views/Customers/Edit.cshtml", 938, 16, true);

WriteLiteral("                ");

EndContext("~/Views/Customers/Edit.cshtml", 938, 16, true);

BeginContext("~/Views/Customers/Edit.cshtml", 955, 68, false);

            
            #line 30 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
           Write(Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/Customers/Edit.cshtml", 955, 68, false);

BeginContext("~/Views/Customers/Edit.cshtml", 1023, 48, true);

WriteLiteral("\n            </div>\n        </div>\n\n        <div");

EndContext("~/Views/Customers/Edit.cshtml", 1023, 48, true);

BeginContext("~/Views/Customers/Edit.cshtml", 1071, 26, true);

WriteLiteral(" class=\"d-flex gap-2 mt-3\"");

EndContext("~/Views/Customers/Edit.cshtml", 1071, 26, true);

BeginContext("~/Views/Customers/Edit.cshtml", 1097, 21, true);

WriteLiteral(">\n            <button");

EndContext("~/Views/Customers/Edit.cshtml", 1097, 21, true);

BeginContext("~/Views/Customers/Edit.cshtml", 1118, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/Customers/Edit.cshtml", 1118, 24, true);

BeginContext("~/Views/Customers/Edit.cshtml", 1142, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/Customers/Edit.cshtml", 1142, 14, true);

BeginContext("~/Views/Customers/Edit.cshtml", 1156, 29, true);

WriteLiteral(">Save</button>\n            <a");

EndContext("~/Views/Customers/Edit.cshtml", 1156, 29, true);

WriteAttribute("href", Tuple.Create(" href=\"", 1185), Tuple.Create("\"", 1212)
            
            #line 36 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1192), Tuple.Create<System.Object, System.Int32>(Url.Action("Index")
            
            #line default
            #line hidden
, 1192), false)
);

BeginContext("~/Views/Customers/Edit.cshtml", 1213, 34, true);

WriteLiteral(" class=\"btn btn-outline-secondary\"");

EndContext("~/Views/Customers/Edit.cshtml", 1213, 34, true);

BeginContext("~/Views/Customers/Edit.cshtml", 1247, 38, true);

WriteLiteral(">Cancel</a>\n        </div>\n    </div>\n");

EndContext("~/Views/Customers/Edit.cshtml", 1247, 38, true);

            
            #line 39 "C:\projects\SOEEApp-main\SOEEApp\Views\Customers\Edit.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
