#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypeSlabMaps\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8018ED8A56E0B98170148C082562D132634D8D2E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    
    public class _Page_Views_ServiceTypeSlabMaps_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<SOEEApp.Models.ServiceTypeSlabMatrixRow>> {
        
#line hidden
        
        public _Page_Views_ServiceTypeSlabMaps_Index_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 61, 4, true);

WriteLiteral("<div");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 61, 4, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 65, 36, true);

WriteLiteral(" class=\"row mb-4 align-items-center\"");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 65, 36, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 101, 10, true);

WriteLiteral(">\n    <div");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 101, 10, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 111, 12, true);

WriteLiteral(" class=\"col\"");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 111, 12, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 123, 13, true);

WriteLiteral(">\n        <h2");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 123, 13, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 136, 13, true);

WriteLiteral(" class=\"mb-0\"");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 136, 13, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 149, 51, true);

WriteLiteral(">Service Type Rates Matrix</h2>\n    </div>\n    <div");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 149, 51, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 200, 17, true);

WriteLiteral(" class=\"col-auto\"");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 200, 17, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 217, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 217, 2, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 219, 8, true);

WriteLiteral("        ");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 219, 8, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 228, 89, false);

            
            #line 8 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypeSlabMaps\Index.cshtml"
   Write(Html.ActionLink("Create New Mapping", "Create", null, new { @class = "btn btn-primary" }));

            
            #line default
            #line hidden
EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 228, 89, false);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 317, 24, true);

WriteLiteral("\n    </div>\n</div>\n\n<div");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 317, 24, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 341, 23, true);

WriteLiteral(" class=\"card shadow-sm\"");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 341, 23, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 364, 10, true);

WriteLiteral(">\n    <div");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 364, 10, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 374, 22, true);

WriteLiteral(" class=\"card-body p-0\"");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 374, 22, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 396, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 396, 14, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 410, 25, true);

WriteLiteral(" class=\"table-responsive\"");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 410, 25, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 435, 20, true);

WriteLiteral(">\n            <table");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 435, 20, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 455, 44, true);

WriteLiteral(" class=\"table table-hover align-middle mb-0\"");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 455, 44, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 499, 24, true);

WriteLiteral(">\n                <thead");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 499, 24, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 523, 17, true);

WriteLiteral(" class=\"bg-light\"");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 523, 17, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 540, 54, true);

WriteLiteral(">\n                    <tr>\n                        <th");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 540, 54, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 594, 13, true);

WriteLiteral(" class=\"ps-4\"");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 594, 13, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 607, 225, true);

WriteLiteral(">Service Type</th>\n                        <th>0 - 25 Lac</th>\n                  " +
"      <th>25 Lac - 1 Cr</th>\n                        <th>1 Cr +</th>\n           " +
"         </tr>\n                </thead>\n                <tbody>\n");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 607, 225, true);

            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypeSlabMaps\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 25 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypeSlabMaps\Index.cshtml"
                     foreach (var row in Model)
                    {

            
            #line default
            #line hidden
BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 902, 60, true);

WriteLiteral("                        <tr>\n                            <td");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 902, 60, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 962, 13, true);

WriteLiteral(" class=\"ps-4\"");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 962, 13, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 975, 1, true);

WriteLiteral(">");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 975, 1, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 977, 15, false);

            
            #line 28 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypeSlabMaps\Index.cshtml"
                                        Write(row.ServiceType);

            
            #line default
            #line hidden
EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 977, 15, false);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 992, 38, true);

WriteLiteral("</td>\n                            <td>");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 992, 38, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 1032, 82, false);

            
            #line 29 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypeSlabMaps\Index.cshtml"
                            Write(row.Range0To25Lac.HasValue ? row.Range0To25Lac.Value.ToString("0.##") + " %" : "-");

            
            #line default
            #line hidden
EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 1032, 82, false);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 1115, 38, true);

WriteLiteral("</td>\n                            <td>");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 1115, 38, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 1155, 86, false);

            
            #line 30 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypeSlabMaps\Index.cshtml"
                            Write(row.Range25LacTo1Cr.HasValue ? row.Range25LacTo1Cr.Value.ToString("0.##") + " %" : "-");

            
            #line default
            #line hidden
EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 1155, 86, false);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 1242, 38, true);

WriteLiteral("</td>\n                            <td>");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 1242, 38, true);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 1282, 80, false);

            
            #line 31 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypeSlabMaps\Index.cshtml"
                            Write(row.Range1CrPlus.HasValue ? row.Range1CrPlus.Value.ToString("0.##") + " %" : "-");

            
            #line default
            #line hidden
EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 1282, 80, false);

BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 1363, 36, true);

WriteLiteral("</td>\n                        </tr>\n");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 1363, 36, true);

            
            #line 33 "C:\projects\SOEEApp-main\SOEEApp\Views\ServiceTypeSlabMaps\Index.cshtml"
                    }

            
            #line default
            #line hidden
BeginContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 1421, 79, true);

WriteLiteral("                </tbody>\n            </table>\n        </div>\n    </div>\n</div>\n");

EndContext("~/Views/ServiceTypeSlabMaps/Index.cshtml", 1421, 79, true);

        }
    }
}
