#pragma checksum "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "EDB2C23A10B5465B3C59702642F9EADC83F18684"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using SOEEApp;
    
    #line 1 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
    using SOEEApp.Models;
    
    #line default
    #line hidden
    
    
    public class _Page_Views_SOEE_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<SOEEApp.Models.SOEE>> {
        
#line hidden
        
        public _Page_Views_SOEE_Index_cshtml() {
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
            
            #line 4 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
  
    ViewBag.Title = "SOEE List";

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 100, 6, true);

WriteLiteral("\n\n<div");

EndContext("~/Views/SOEE/Index.cshtml", 100, 6, true);

BeginContext("~/Views/SOEE/Index.cshtml", 106, 79, true);

WriteLiteral(" class=\"d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3\"");

EndContext("~/Views/SOEE/Index.cshtml", 106, 79, true);

BeginContext("~/Views/SOEE/Index.cshtml", 185, 23, true);

WriteLiteral(">\n    <div>\n        <h2");

EndContext("~/Views/SOEE/Index.cshtml", 185, 23, true);

BeginContext("~/Views/SOEE/Index.cshtml", 208, 13, true);

WriteLiteral(" class=\"mb-1\"");

EndContext("~/Views/SOEE/Index.cshtml", 208, 13, true);

BeginContext("~/Views/SOEE/Index.cshtml", 221, 30, true);

WriteLiteral(">SOEE Register</h2>\n        <p");

EndContext("~/Views/SOEE/Index.cshtml", 221, 30, true);

BeginContext("~/Views/SOEE/Index.cshtml", 251, 24, true);

WriteLiteral(" class=\"text-muted mb-0\"");

EndContext("~/Views/SOEE/Index.cshtml", 251, 24, true);

BeginContext("~/Views/SOEE/Index.cshtml", 275, 86, true);

WriteLiteral(">Project-wise list with workflow, payment and closure status.</p>\n    </div>\n\n   " +
" <div");

EndContext("~/Views/SOEE/Index.cshtml", 275, 86, true);

BeginContext("~/Views/SOEE/Index.cshtml", 361, 31, true);

WriteLiteral(" class=\"d-flex gap-2 flex-wrap\"");

EndContext("~/Views/SOEE/Index.cshtml", 361, 31, true);

BeginContext("~/Views/SOEE/Index.cshtml", 392, 2, true);

WriteLiteral(">\n");

EndContext("~/Views/SOEE/Index.cshtml", 392, 2, true);

            
            #line 15 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 15 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
         if (User.IsInRole("OIC"))
        {

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 439, 14, true);

WriteLiteral("            <a");

EndContext("~/Views/SOEE/Index.cshtml", 439, 14, true);

WriteAttribute("href", Tuple.Create(" href=\"", 453), Tuple.Create("\"", 481)
            
            #line 17 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
, Tuple.Create(Tuple.Create("", 460), Tuple.Create<System.Object, System.Int32>(Url.Action("Create")
            
            #line default
            #line hidden
, 460), false)
);

BeginContext("~/Views/SOEE/Index.cshtml", 482, 24, true);

WriteLiteral(" class=\"btn btn-primary\"");

EndContext("~/Views/SOEE/Index.cshtml", 482, 24, true);

BeginContext("~/Views/SOEE/Index.cshtml", 506, 17, true);

WriteLiteral(">Create SOEE</a>\n");

EndContext("~/Views/SOEE/Index.cshtml", 506, 17, true);

            
            #line 18 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
        }

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 533, 10, true);

WriteLiteral("        <a");

EndContext("~/Views/SOEE/Index.cshtml", 533, 10, true);

WriteAttribute("href", Tuple.Create(" href=\"", 543), Tuple.Create("\"", 657)
            
            #line 19 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
, Tuple.Create(Tuple.Create("", 550), Tuple.Create<System.Object, System.Int32>(Url.Action("ExportCsv", "SOEE", new { projectId = Request["projectId"], status = ViewBag.SelectedStatus })
            
            #line default
            #line hidden
, 550), false)
);

BeginContext("~/Views/SOEE/Index.cshtml", 658, 32, true);

WriteLiteral(" class=\"btn btn-outline-success\"");

EndContext("~/Views/SOEE/Index.cshtml", 658, 32, true);

BeginContext("~/Views/SOEE/Index.cshtml", 690, 28, true);

WriteLiteral(">Export Excel</a>\n        <a");

EndContext("~/Views/SOEE/Index.cshtml", 690, 28, true);

WriteAttribute("href", Tuple.Create(" href=\"", 718), Tuple.Create("\"", 756)
            
            #line 20 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
, Tuple.Create(Tuple.Create("", 725), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Reports")
            
            #line default
            #line hidden
, 725), false)
);

BeginContext("~/Views/SOEE/Index.cshtml", 757, 34, true);

WriteLiteral(" class=\"btn btn-outline-secondary\"");

EndContext("~/Views/SOEE/Index.cshtml", 757, 34, true);

BeginContext("~/Views/SOEE/Index.cshtml", 791, 32, true);

WriteLiteral(">Reports</a>\n    </div>\n</div>\n\n");

EndContext("~/Views/SOEE/Index.cshtml", 791, 32, true);

            
            #line 24 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
 using (Html.BeginForm("Index", "SOEE", FormMethod.Get, new { @class = "card card-body shadow-sm mb-3" }))
{

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 932, 8, true);

WriteLiteral("    <div");

EndContext("~/Views/SOEE/Index.cshtml", 932, 8, true);

BeginContext("~/Views/SOEE/Index.cshtml", 940, 32, true);

WriteLiteral(" class=\"row g-3 align-items-end\"");

EndContext("~/Views/SOEE/Index.cshtml", 940, 32, true);

BeginContext("~/Views/SOEE/Index.cshtml", 972, 14, true);

WriteLiteral(">\n        <div");

EndContext("~/Views/SOEE/Index.cshtml", 972, 14, true);

BeginContext("~/Views/SOEE/Index.cshtml", 986, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/SOEE/Index.cshtml", 986, 17, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1003, 20, true);

WriteLiteral(">\n            <label");

EndContext("~/Views/SOEE/Index.cshtml", 1003, 20, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1023, 19, true);

WriteLiteral(" class=\"form-label\"");

EndContext("~/Views/SOEE/Index.cshtml", 1023, 19, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1042, 17, true);

WriteLiteral(">Project</label>\n");

EndContext("~/Views/SOEE/Index.cshtml", 1042, 17, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1059, 12, true);

WriteLiteral("            ");

EndContext("~/Views/SOEE/Index.cshtml", 1059, 12, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1072, 111, false);

            
            #line 29 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
       Write(Html.DropDownList("projectId", ViewBag.Projects as SelectList, "All Projects", new { @class = "form-control" }));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 1072, 111, false);

BeginContext("~/Views/SOEE/Index.cshtml", 1183, 28, true);

WriteLiteral("\n        </div>\n        <div");

EndContext("~/Views/SOEE/Index.cshtml", 1183, 28, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1211, 17, true);

WriteLiteral(" class=\"col-md-4\"");

EndContext("~/Views/SOEE/Index.cshtml", 1211, 17, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1228, 20, true);

WriteLiteral(">\n            <label");

EndContext("~/Views/SOEE/Index.cshtml", 1228, 20, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1248, 19, true);

WriteLiteral(" class=\"form-label\"");

EndContext("~/Views/SOEE/Index.cshtml", 1248, 19, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1267, 35, true);

WriteLiteral(">Status</label>\n            <select");

EndContext("~/Views/SOEE/Index.cshtml", 1267, 35, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1302, 14, true);

WriteLiteral(" name=\"status\"");

EndContext("~/Views/SOEE/Index.cshtml", 1302, 14, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1316, 21, true);

WriteLiteral(" class=\"form-control\"");

EndContext("~/Views/SOEE/Index.cshtml", 1316, 21, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1337, 25, true);

WriteLiteral(">\n                <option");

EndContext("~/Views/SOEE/Index.cshtml", 1337, 25, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1362, 9, true);

WriteLiteral(" value=\"\"");

EndContext("~/Views/SOEE/Index.cshtml", 1362, 9, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1371, 23, true);

WriteLiteral(">All Statuses</option>\n");

EndContext("~/Views/SOEE/Index.cshtml", 1371, 23, true);

            
            #line 35 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 35 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                 foreach (SOEEStatus status in Enum.GetValues(typeof(SOEEStatus)))
                {

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 1495, 27, true);

WriteLiteral("                    <option");

EndContext("~/Views/SOEE/Index.cshtml", 1495, 27, true);

WriteAttribute("value", Tuple.Create(" value=\"", 1522), Tuple.Create("\"", 1537)
            
            #line 37 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1530), Tuple.Create<System.Object, System.Int32>(status
            
            #line default
            #line hidden
, 1530), false)
);

BeginContext("~/Views/SOEE/Index.cshtml", 1538, 1, true);

WriteLiteral(" ");

EndContext("~/Views/SOEE/Index.cshtml", 1538, 1, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1541, 118, false);

            
            #line 37 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                        Write(string.Equals((string)ViewBag.SelectedStatus, status.ToString(), StringComparison.OrdinalIgnoreCase) ? "selected" : "");

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 1541, 118, false);

BeginContext("~/Views/SOEE/Index.cshtml", 1660, 1, true);

WriteLiteral(">");

EndContext("~/Views/SOEE/Index.cshtml", 1660, 1, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1662, 6, false);

            
            #line 37 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                                                                                                                 Write(status);

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 1662, 6, false);

BeginContext("~/Views/SOEE/Index.cshtml", 1668, 10, true);

WriteLiteral("</option>\n");

EndContext("~/Views/SOEE/Index.cshtml", 1668, 10, true);

            
            #line 38 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                }

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 1696, 49, true);

WriteLiteral("            </select>\n        </div>\n        <div");

EndContext("~/Views/SOEE/Index.cshtml", 1696, 49, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1745, 30, true);

WriteLiteral(" class=\"col-md-4 d-flex gap-2\"");

EndContext("~/Views/SOEE/Index.cshtml", 1745, 30, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1775, 21, true);

WriteLiteral(">\n            <button");

EndContext("~/Views/SOEE/Index.cshtml", 1775, 21, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1796, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/SOEE/Index.cshtml", 1796, 14, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1810, 21, true);

WriteLiteral(" class=\"btn btn-dark\"");

EndContext("~/Views/SOEE/Index.cshtml", 1810, 21, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1831, 30, true);

WriteLiteral(">Apply</button>\n            <a");

EndContext("~/Views/SOEE/Index.cshtml", 1831, 30, true);

WriteAttribute("href", Tuple.Create(" href=\"", 1861), Tuple.Create("\"", 1888)
            
            #line 43 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1868), Tuple.Create<System.Object, System.Int32>(Url.Action("Index")
            
            #line default
            #line hidden
, 1868), false)
);

BeginContext("~/Views/SOEE/Index.cshtml", 1889, 34, true);

WriteLiteral(" class=\"btn btn-outline-secondary\"");

EndContext("~/Views/SOEE/Index.cshtml", 1889, 34, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1923, 37, true);

WriteLiteral(">Reset</a>\n        </div>\n    </div>\n");

EndContext("~/Views/SOEE/Index.cshtml", 1923, 37, true);

            
            #line 46 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
}

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 1962, 5, true);

WriteLiteral("\n<div");

EndContext("~/Views/SOEE/Index.cshtml", 1962, 5, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1967, 23, true);

WriteLiteral(" class=\"card shadow-sm\"");

EndContext("~/Views/SOEE/Index.cshtml", 1967, 23, true);

BeginContext("~/Views/SOEE/Index.cshtml", 1990, 10, true);

WriteLiteral(">\n    <div");

EndContext("~/Views/SOEE/Index.cshtml", 1990, 10, true);

BeginContext("~/Views/SOEE/Index.cshtml", 2000, 25, true);

WriteLiteral(" class=\"table-responsive\"");

EndContext("~/Views/SOEE/Index.cshtml", 2000, 25, true);

BeginContext("~/Views/SOEE/Index.cshtml", 2025, 16, true);

WriteLiteral(">\n        <table");

EndContext("~/Views/SOEE/Index.cshtml", 2025, 16, true);

BeginContext("~/Views/SOEE/Index.cshtml", 2041, 44, true);

WriteLiteral(" class=\"table table-hover align-middle mb-0\"");

EndContext("~/Views/SOEE/Index.cshtml", 2041, 44, true);

BeginContext("~/Views/SOEE/Index.cshtml", 2085, 20, true);

WriteLiteral(">\n            <thead");

EndContext("~/Views/SOEE/Index.cshtml", 2085, 20, true);

BeginContext("~/Views/SOEE/Index.cshtml", 2105, 20, true);

WriteLiteral(" class=\"table-light\"");

EndContext("~/Views/SOEE/Index.cshtml", 2105, 20, true);

BeginContext("~/Views/SOEE/Index.cshtml", 2125, 301, true);

WriteLiteral(@">
                <tr>
                    <th>SOEE ID</th>
                    <th>Project</th>
                    <th>Customer</th>
                    <th>Date</th>
                    <th>Total</th>
                    <th>Received</th>
                    <th>Status</th>
                    <th");

EndContext("~/Views/SOEE/Index.cshtml", 2125, 301, true);

BeginContext("~/Views/SOEE/Index.cshtml", 2426, 17, true);

WriteLiteral(" class=\"text-end\"");

EndContext("~/Views/SOEE/Index.cshtml", 2426, 17, true);

BeginContext("~/Views/SOEE/Index.cshtml", 2443, 77, true);

WriteLiteral(">Actions</th>\n                </tr>\n            </thead>\n            <tbody>\n");

EndContext("~/Views/SOEE/Index.cshtml", 2443, 77, true);

            
            #line 64 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 64 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                 foreach (var item in Model)
                {
                    var received = item.Payments != null ? item.Payments.Sum(p => p.AmountReceived) : 0m;

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 2689, 53, true);

WriteLiteral("                    <tr>\n                        <td>");

EndContext("~/Views/SOEE/Index.cshtml", 2689, 53, true);

BeginContext("~/Views/SOEE/Index.cshtml", 2743, 11, false);

            
            #line 68 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                       Write(item.SOEEID);

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 2743, 11, false);

BeginContext("~/Views/SOEE/Index.cshtml", 2754, 34, true);

WriteLiteral("</td>\n                        <td>");

EndContext("~/Views/SOEE/Index.cshtml", 2754, 34, true);

BeginContext("~/Views/SOEE/Index.cshtml", 2790, 45, false);

            
            #line 69 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                        Write(item.Project != null ? item.Project.Name : "");

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 2790, 45, false);

BeginContext("~/Views/SOEE/Index.cshtml", 2836, 34, true);

WriteLiteral("</td>\n                        <td>");

EndContext("~/Views/SOEE/Index.cshtml", 2836, 34, true);

BeginContext("~/Views/SOEE/Index.cshtml", 2872, 55, false);

            
            #line 70 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                        Write(item.Customer != null ? item.Customer.CustomerName : "");

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 2872, 55, false);

BeginContext("~/Views/SOEE/Index.cshtml", 2928, 34, true);

WriteLiteral("</td>\n                        <td>");

EndContext("~/Views/SOEE/Index.cshtml", 2928, 34, true);

BeginContext("~/Views/SOEE/Index.cshtml", 2963, 42, false);

            
            #line 71 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                       Write(item.SOEERaiseDate.ToString("dd-MMM-yyyy"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 2963, 42, false);

BeginContext("~/Views/SOEE/Index.cshtml", 3005, 34, true);

WriteLiteral("</td>\n                        <td>");

EndContext("~/Views/SOEE/Index.cshtml", 3005, 34, true);

BeginContext("~/Views/SOEE/Index.cshtml", 3040, 30, false);

            
            #line 72 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                       Write(item.GrandTotal.ToString("N2"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 3040, 30, false);

BeginContext("~/Views/SOEE/Index.cshtml", 3070, 34, true);

WriteLiteral("</td>\n                        <td>");

EndContext("~/Views/SOEE/Index.cshtml", 3070, 34, true);

BeginContext("~/Views/SOEE/Index.cshtml", 3105, 23, false);

            
            #line 73 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                       Write(received.ToString("N2"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 3105, 23, false);

BeginContext("~/Views/SOEE/Index.cshtml", 3128, 39, true);

WriteLiteral("</td>\n                        <td><span");

EndContext("~/Views/SOEE/Index.cshtml", 3128, 39, true);

BeginContext("~/Views/SOEE/Index.cshtml", 3167, 27, true);

WriteLiteral(" class=\"badge bg-secondary\"");

EndContext("~/Views/SOEE/Index.cshtml", 3167, 27, true);

BeginContext("~/Views/SOEE/Index.cshtml", 3194, 1, true);

WriteLiteral(">");

EndContext("~/Views/SOEE/Index.cshtml", 3194, 1, true);

BeginContext("~/Views/SOEE/Index.cshtml", 3196, 11, false);

            
            #line 74 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                        Write(item.Status);

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 3196, 11, false);

BeginContext("~/Views/SOEE/Index.cshtml", 3207, 40, true);

WriteLiteral("</span></td>\n                        <td");

EndContext("~/Views/SOEE/Index.cshtml", 3207, 40, true);

BeginContext("~/Views/SOEE/Index.cshtml", 3247, 17, true);

WriteLiteral(" class=\"text-end\"");

EndContext("~/Views/SOEE/Index.cshtml", 3247, 17, true);

BeginContext("~/Views/SOEE/Index.cshtml", 3264, 34, true);

WriteLiteral(">\n                            <div");

EndContext("~/Views/SOEE/Index.cshtml", 3264, 34, true);

BeginContext("~/Views/SOEE/Index.cshtml", 3298, 51, true);

WriteLiteral(" class=\"d-flex justify-content-end gap-2 flex-wrap\"");

EndContext("~/Views/SOEE/Index.cshtml", 3298, 51, true);

BeginContext("~/Views/SOEE/Index.cshtml", 3349, 36, true);

WriteLiteral(">\n                                <a");

EndContext("~/Views/SOEE/Index.cshtml", 3349, 36, true);

WriteAttribute("href", Tuple.Create(" href=\"", 3385), Tuple.Create("\"", 3440)
            
            #line 77 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3392), Tuple.Create<System.Object, System.Int32>(Url.Action("Details", new { id = item.SOEEID })
            
            #line default
            #line hidden
, 3392), false)
);

BeginContext("~/Views/SOEE/Index.cshtml", 3441, 36, true);

WriteLiteral(" class=\"btn btn-sm btn-outline-info\"");

EndContext("~/Views/SOEE/Index.cshtml", 3441, 36, true);

BeginContext("~/Views/SOEE/Index.cshtml", 3477, 44, true);

WriteLiteral(">View</a>\n                                <a");

EndContext("~/Views/SOEE/Index.cshtml", 3477, 44, true);

WriteAttribute("href", Tuple.Create(" href=\"", 3521), Tuple.Create("\"", 3574)
            
            #line 78 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3528), Tuple.Create<System.Object, System.Int32>(Url.Action("Print", new { id = item.SOEEID })
            
            #line default
            #line hidden
, 3528), false)
);

BeginContext("~/Views/SOEE/Index.cshtml", 3575, 36, true);

WriteLiteral(" class=\"btn btn-sm btn-outline-dark\"");

EndContext("~/Views/SOEE/Index.cshtml", 3575, 36, true);

BeginContext("~/Views/SOEE/Index.cshtml", 3611, 16, true);

WriteLiteral(" target=\"_blank\"");

EndContext("~/Views/SOEE/Index.cshtml", 3611, 16, true);

BeginContext("~/Views/SOEE/Index.cshtml", 3627, 12, true);

WriteLiteral(">Print</a>\n\n");

EndContext("~/Views/SOEE/Index.cshtml", 3627, 12, true);

            
            #line 80 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 80 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                 if (User.IsInRole("OIC") && (item.Status == SOEEStatus.Draft || item.Status == SOEEStatus.NeedCorrection))
                                {

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 3813, 38, true);

WriteLiteral("                                    <a");

EndContext("~/Views/SOEE/Index.cshtml", 3813, 38, true);

WriteAttribute("href", Tuple.Create(" href=\"", 3851), Tuple.Create("\"", 3903)
            
            #line 82 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3858), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", new { id = item.SOEEID })
            
            #line default
            #line hidden
, 3858), false)
);

BeginContext("~/Views/SOEE/Index.cshtml", 3904, 39, true);

WriteLiteral(" class=\"btn btn-sm btn-outline-warning\"");

EndContext("~/Views/SOEE/Index.cshtml", 3904, 39, true);

BeginContext("~/Views/SOEE/Index.cshtml", 3943, 10, true);

WriteLiteral(">Edit</a>\n");

EndContext("~/Views/SOEE/Index.cshtml", 3943, 10, true);

            
            #line 83 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                    using (Html.BeginForm("Submit", "SOEE", FormMethod.Post, new { style = "display:inline;" }))
                                    {
                                        
            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 4161, 23, false);

            
            #line 85 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 4161, 23, false);

            
            #line 85 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                
                                        
            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 4226, 30, false);

            
            #line 86 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                   Write(Html.Hidden("id", item.SOEEID));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 4226, 30, false);

            
            #line 86 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                       

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 4257, 47, true);

WriteLiteral("                                        <button");

EndContext("~/Views/SOEE/Index.cshtml", 4257, 47, true);

BeginContext("~/Views/SOEE/Index.cshtml", 4304, 41, true);

WriteLiteral(" class=\"btn btn-sm btn-success js-submit\"");

EndContext("~/Views/SOEE/Index.cshtml", 4304, 41, true);

BeginContext("~/Views/SOEE/Index.cshtml", 4345, 10, true);

WriteLiteral(" data-id=\"");

EndContext("~/Views/SOEE/Index.cshtml", 4345, 10, true);

BeginContext("~/Views/SOEE/Index.cshtml", 4356, 11, false);

            
            #line 87 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                                             Write(item.SOEEID);

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 4356, 11, false);

BeginContext("~/Views/SOEE/Index.cshtml", 4367, 1, true);

WriteLiteral("\"");

EndContext("~/Views/SOEE/Index.cshtml", 4367, 1, true);

BeginContext("~/Views/SOEE/Index.cshtml", 4368, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/SOEE/Index.cshtml", 4368, 14, true);

BeginContext("~/Views/SOEE/Index.cshtml", 4382, 17, true);

WriteLiteral(">Submit</button>\n");

EndContext("~/Views/SOEE/Index.cshtml", 4382, 17, true);

            
            #line 88 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                    }
                                }

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 4471, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Index.cshtml", 4471, 1, true);

            
            #line 91 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 91 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                 if (User.IsInRole("FinanceManager") && item.Status == SOEEStatus.Submitted)
                                {
                                    using (Html.BeginForm("ApproveByFM", "SOEE", FormMethod.Post, new { style = "display:inline;" }))
                                    {
                                        
            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 4828, 23, false);

            
            #line 95 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 4828, 23, false);

            
            #line 95 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                
                                        
            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 4893, 30, false);

            
            #line 96 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                   Write(Html.Hidden("id", item.SOEEID));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 4893, 30, false);

            
            #line 96 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                       

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 4924, 47, true);

WriteLiteral("                                        <button");

EndContext("~/Views/SOEE/Index.cshtml", 4924, 47, true);

BeginContext("~/Views/SOEE/Index.cshtml", 4971, 50, true);

WriteLiteral(" class=\"btn btn-sm btn-outline-primary js-approve\"");

EndContext("~/Views/SOEE/Index.cshtml", 4971, 50, true);

BeginContext("~/Views/SOEE/Index.cshtml", 5021, 10, true);

WriteLiteral(" data-id=\"");

EndContext("~/Views/SOEE/Index.cshtml", 5021, 10, true);

BeginContext("~/Views/SOEE/Index.cshtml", 5032, 11, false);

            
            #line 97 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                                                      Write(item.SOEEID);

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 5032, 11, false);

BeginContext("~/Views/SOEE/Index.cshtml", 5043, 1, true);

WriteLiteral("\"");

EndContext("~/Views/SOEE/Index.cshtml", 5043, 1, true);

BeginContext("~/Views/SOEE/Index.cshtml", 5044, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/SOEE/Index.cshtml", 5044, 14, true);

BeginContext("~/Views/SOEE/Index.cshtml", 5058, 18, true);

WriteLiteral(">Approve</button>\n");

EndContext("~/Views/SOEE/Index.cshtml", 5058, 18, true);

            
            #line 98 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                    }
                                    using (Html.BeginForm("NeedCorrectionByFM", "SOEE", FormMethod.Post, new { style = "display:inline;" }))
                                    {
                                        
            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 5334, 23, false);

            
            #line 101 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 5334, 23, false);

            
            #line 101 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                
                                        
            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 5399, 30, false);

            
            #line 102 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                   Write(Html.Hidden("id", item.SOEEID));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 5399, 30, false);

            
            #line 102 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                       

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 5430, 47, true);

WriteLiteral("                                        <button");

EndContext("~/Views/SOEE/Index.cshtml", 5430, 47, true);

BeginContext("~/Views/SOEE/Index.cshtml", 5477, 53, true);

WriteLiteral(" class=\"btn btn-sm btn-outline-warning js-correction\"");

EndContext("~/Views/SOEE/Index.cshtml", 5477, 53, true);

BeginContext("~/Views/SOEE/Index.cshtml", 5530, 10, true);

WriteLiteral(" data-id=\"");

EndContext("~/Views/SOEE/Index.cshtml", 5530, 10, true);

BeginContext("~/Views/SOEE/Index.cshtml", 5541, 11, false);

            
            #line 103 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                                                         Write(item.SOEEID);

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 5541, 11, false);

BeginContext("~/Views/SOEE/Index.cshtml", 5552, 1, true);

WriteLiteral("\"");

EndContext("~/Views/SOEE/Index.cshtml", 5552, 1, true);

BeginContext("~/Views/SOEE/Index.cshtml", 5553, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/SOEE/Index.cshtml", 5553, 14, true);

BeginContext("~/Views/SOEE/Index.cshtml", 5567, 21, true);

WriteLiteral(">Correction</button>\n");

EndContext("~/Views/SOEE/Index.cshtml", 5567, 21, true);

            
            #line 104 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                    }
                                }

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 5660, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Index.cshtml", 5660, 1, true);

            
            #line 107 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 107 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                 if (User.IsInRole("FinanceDirector") && item.Status == SOEEStatus.Approved)
                                {
                                    using (Html.BeginForm("ApproveByFD", "SOEE", FormMethod.Post, new { style = "display:inline;" }))
                                    {
                                        
            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 6017, 23, false);

            
            #line 111 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 6017, 23, false);

            
            #line 111 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                
                                        
            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 6082, 30, false);

            
            #line 112 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                   Write(Html.Hidden("id", item.SOEEID));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 6082, 30, false);

            
            #line 112 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                       

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 6113, 47, true);

WriteLiteral("                                        <button");

EndContext("~/Views/SOEE/Index.cshtml", 6113, 47, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6160, 48, true);

WriteLiteral(" class=\"btn btn-sm btn-success js-final-approve\"");

EndContext("~/Views/SOEE/Index.cshtml", 6160, 48, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6208, 10, true);

WriteLiteral(" data-id=\"");

EndContext("~/Views/SOEE/Index.cshtml", 6208, 10, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6219, 11, false);

            
            #line 113 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                                                    Write(item.SOEEID);

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 6219, 11, false);

BeginContext("~/Views/SOEE/Index.cshtml", 6230, 1, true);

WriteLiteral("\"");

EndContext("~/Views/SOEE/Index.cshtml", 6230, 1, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6231, 14, true);

WriteLiteral(" type=\"submit\"");

EndContext("~/Views/SOEE/Index.cshtml", 6231, 14, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6245, 19, true);

WriteLiteral(">Dispatch</button>\n");

EndContext("~/Views/SOEE/Index.cshtml", 6245, 19, true);

            
            #line 114 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                    }
                                }

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 6336, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Index.cshtml", 6336, 1, true);

            
            #line 117 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 117 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                 if (User.IsInRole("Client") && (item.Status == SOEEStatus.Dispatched || item.Status == SOEEStatus.ErrorInPayment))
                                {

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 6519, 43, true);

WriteLiteral("                                    <button");

EndContext("~/Views/SOEE/Index.cshtml", 6519, 43, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6562, 50, true);

WriteLiteral(" class=\"btn btn-sm btn-outline-warning js-partial\"");

EndContext("~/Views/SOEE/Index.cshtml", 6562, 50, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6612, 10, true);

WriteLiteral(" data-id=\"");

EndContext("~/Views/SOEE/Index.cshtml", 6612, 10, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6623, 11, false);

            
            #line 119 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                                                  Write(item.SOEEID);

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 6623, 11, false);

BeginContext("~/Views/SOEE/Index.cshtml", 6634, 1, true);

WriteLiteral("\"");

EndContext("~/Views/SOEE/Index.cshtml", 6634, 1, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6635, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/SOEE/Index.cshtml", 6635, 14, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6649, 18, true);

WriteLiteral(">Partial</button>\n");

EndContext("~/Views/SOEE/Index.cshtml", 6649, 18, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6667, 43, true);

WriteLiteral("                                    <button");

EndContext("~/Views/SOEE/Index.cshtml", 6667, 43, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6710, 47, true);

WriteLiteral(" class=\"btn btn-sm btn-outline-success js-full\"");

EndContext("~/Views/SOEE/Index.cshtml", 6710, 47, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6757, 10, true);

WriteLiteral(" data-id=\"");

EndContext("~/Views/SOEE/Index.cshtml", 6757, 10, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6768, 11, false);

            
            #line 120 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                                               Write(item.SOEEID);

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 6768, 11, false);

BeginContext("~/Views/SOEE/Index.cshtml", 6779, 1, true);

WriteLiteral("\"");

EndContext("~/Views/SOEE/Index.cshtml", 6779, 1, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6780, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/SOEE/Index.cshtml", 6780, 14, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6794, 15, true);

WriteLiteral(">Full</button>\n");

EndContext("~/Views/SOEE/Index.cshtml", 6794, 15, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6809, 43, true);

WriteLiteral("                                    <button");

EndContext("~/Views/SOEE/Index.cshtml", 6809, 43, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6852, 48, true);

WriteLiteral(" class=\"btn btn-sm btn-outline-danger js-reject\"");

EndContext("~/Views/SOEE/Index.cshtml", 6852, 48, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6900, 10, true);

WriteLiteral(" data-id=\"");

EndContext("~/Views/SOEE/Index.cshtml", 6900, 10, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6911, 11, false);

            
            #line 121 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                                                Write(item.SOEEID);

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 6911, 11, false);

BeginContext("~/Views/SOEE/Index.cshtml", 6922, 1, true);

WriteLiteral("\"");

EndContext("~/Views/SOEE/Index.cshtml", 6922, 1, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6923, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/SOEE/Index.cshtml", 6923, 14, true);

BeginContext("~/Views/SOEE/Index.cshtml", 6937, 17, true);

WriteLiteral(">Reject</button>\n");

EndContext("~/Views/SOEE/Index.cshtml", 6937, 17, true);

            
            #line 122 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                }

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 6988, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Index.cshtml", 6988, 1, true);

            
            #line 124 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 124 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                 if (User.IsInRole("Cashier") && (item.Status == SOEEStatus.Reconciled || item.Status == SOEEStatus.PartiallyPaid || item.Status == SOEEStatus.FullyPaid || item.Status == SOEEStatus.ErrorInPayment))
                                {

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 7254, 38, true);

WriteLiteral("                                    <a");

EndContext("~/Views/SOEE/Index.cshtml", 7254, 38, true);

WriteAttribute("href", Tuple.Create(" href=\"", 7292), Tuple.Create("\"", 7362)
            
            #line 126 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
, Tuple.Create(Tuple.Create("", 7299), Tuple.Create<System.Object, System.Int32>(Url.Action("Record", "Payments", new { soeeId = item.SOEEID })
            
            #line default
            #line hidden
, 7299), false)
);

BeginContext("~/Views/SOEE/Index.cshtml", 7363, 39, true);

WriteLiteral(" class=\"btn btn-sm btn-outline-primary\"");

EndContext("~/Views/SOEE/Index.cshtml", 7363, 39, true);

BeginContext("~/Views/SOEE/Index.cshtml", 7402, 20, true);

WriteLiteral(">Record Payment</a>\n");

EndContext("~/Views/SOEE/Index.cshtml", 7402, 20, true);

BeginContext("~/Views/SOEE/Index.cshtml", 7422, 38, true);

WriteLiteral("                                    <a");

EndContext("~/Views/SOEE/Index.cshtml", 7422, 38, true);

WriteAttribute("href", Tuple.Create(" href=\"", 7460), Tuple.Create("\"", 7533)
            
            #line 127 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
, Tuple.Create(Tuple.Create("", 7467), Tuple.Create<System.Object, System.Int32>(Url.Action("Reconcile", "Payments", new { soeeId = item.SOEEID })
            
            #line default
            #line hidden
, 7467), false)
);

BeginContext("~/Views/SOEE/Index.cshtml", 7534, 39, true);

WriteLiteral(" class=\"btn btn-sm btn-outline-primary\"");

EndContext("~/Views/SOEE/Index.cshtml", 7534, 39, true);

BeginContext("~/Views/SOEE/Index.cshtml", 7573, 15, true);

WriteLiteral(">Reconcile</a>\n");

EndContext("~/Views/SOEE/Index.cshtml", 7573, 15, true);

BeginContext("~/Views/SOEE/Index.cshtml", 7588, 43, true);

WriteLiteral("                                    <button");

EndContext("~/Views/SOEE/Index.cshtml", 7588, 43, true);

BeginContext("~/Views/SOEE/Index.cshtml", 7631, 55, true);

WriteLiteral(" class=\"btn btn-sm btn-outline-danger js-error-payment\"");

EndContext("~/Views/SOEE/Index.cshtml", 7631, 55, true);

BeginContext("~/Views/SOEE/Index.cshtml", 7686, 10, true);

WriteLiteral(" data-id=\"");

EndContext("~/Views/SOEE/Index.cshtml", 7686, 10, true);

BeginContext("~/Views/SOEE/Index.cshtml", 7697, 11, false);

            
            #line 128 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                                                       Write(item.SOEEID);

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 7697, 11, false);

BeginContext("~/Views/SOEE/Index.cshtml", 7708, 1, true);

WriteLiteral("\"");

EndContext("~/Views/SOEE/Index.cshtml", 7708, 1, true);

BeginContext("~/Views/SOEE/Index.cshtml", 7709, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/SOEE/Index.cshtml", 7709, 14, true);

BeginContext("~/Views/SOEE/Index.cshtml", 7723, 16, true);

WriteLiteral(">Error</button>\n");

EndContext("~/Views/SOEE/Index.cshtml", 7723, 16, true);

            
            #line 129 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                }

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 7773, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Index.cshtml", 7773, 1, true);

            
            #line 131 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 131 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                 if (User.IsInRole("OIC") && item.Status == SOEEStatus.Reconciled)
                                {

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 7907, 43, true);

WriteLiteral("                                    <button");

EndContext("~/Views/SOEE/Index.cshtml", 7907, 43, true);

BeginContext("~/Views/SOEE/Index.cshtml", 7950, 40, true);

WriteLiteral(" class=\"btn btn-sm btn-success js-close\"");

EndContext("~/Views/SOEE/Index.cshtml", 7950, 40, true);

BeginContext("~/Views/SOEE/Index.cshtml", 7990, 10, true);

WriteLiteral(" data-id=\"");

EndContext("~/Views/SOEE/Index.cshtml", 7990, 10, true);

BeginContext("~/Views/SOEE/Index.cshtml", 8001, 11, false);

            
            #line 133 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                                                                        Write(item.SOEEID);

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 8001, 11, false);

BeginContext("~/Views/SOEE/Index.cshtml", 8012, 1, true);

WriteLiteral("\"");

EndContext("~/Views/SOEE/Index.cshtml", 8012, 1, true);

BeginContext("~/Views/SOEE/Index.cshtml", 8013, 14, true);

WriteLiteral(" type=\"button\"");

EndContext("~/Views/SOEE/Index.cshtml", 8013, 14, true);

BeginContext("~/Views/SOEE/Index.cshtml", 8027, 16, true);

WriteLiteral(">Close</button>\n");

EndContext("~/Views/SOEE/Index.cshtml", 8027, 16, true);

            
            #line 134 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                                }

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 8077, 91, true);

WriteLiteral("                            </div>\n                        </td>\n                " +
"    </tr>\n");

EndContext("~/Views/SOEE/Index.cshtml", 8077, 91, true);

            
            #line 138 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                }

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 8186, 57, true);

WriteLiteral("            </tbody>\n        </table>\n    </div>\n</div>\n\n");

EndContext("~/Views/SOEE/Index.cshtml", 8186, 57, true);

            
            #line 144 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
 using (Html.BeginForm())
{
    
            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 8276, 23, false);

            
            #line 146 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 8276, 23, false);

            
            #line 146 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                            
}

            
            #line default
            #line hidden
BeginContext("~/Views/SOEE/Index.cshtml", 8302, 1, true);

WriteLiteral("\n");

EndContext("~/Views/SOEE/Index.cshtml", 8302, 1, true);

DefineSection("Scripts", () => {

BeginContext("~/Views/SOEE/Index.cshtml", 8321, 774, true);

WriteLiteral(@"
    <script>
        function updateSOEE(url, id) {
            var token = $('input[name=""__RequestVerificationToken""]').first().val();

            $.ajax({
                url: url,
                type: ""POST"",
                data: {
                    __RequestVerificationToken: token,
                    id: id
                },
                success: function (res) {
                    if (res.success) {
                        window.location.reload();
                    }
                },
                error: function (xhr) {
                    alert(""Action failed: "" + xhr.status);
                }
            });
        }

        $(document).on(""click"", "".js-submit"", function (e) {
            e.preventDefault();
            updateSOEE(""");

EndContext("~/Views/SOEE/Index.cshtml", 8321, 774, true);

BeginContext("~/Views/SOEE/Index.cshtml", 9096, 32, false);

            
            #line 174 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                   Write(Url.Action("SubmitAjax", "SOEE"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 9096, 32, false);

BeginContext("~/Views/SOEE/Index.cshtml", 9128, 155, true);

WriteLiteral("\", $(this).data(\"id\"));\n        });\n\n        $(document).on(\"click\", \".js-approve" +
"\", function (e) {\n            e.preventDefault();\n            updateSOEE(\"");

EndContext("~/Views/SOEE/Index.cshtml", 9128, 155, true);

BeginContext("~/Views/SOEE/Index.cshtml", 9284, 37, false);

            
            #line 179 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                   Write(Url.Action("ApproveByFMAjax", "SOEE"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 9284, 37, false);

BeginContext("~/Views/SOEE/Index.cshtml", 9321, 158, true);

WriteLiteral("\", $(this).data(\"id\"));\n        });\n\n        $(document).on(\"click\", \".js-correct" +
"ion\", function (e) {\n            e.preventDefault();\n            updateSOEE(\"");

EndContext("~/Views/SOEE/Index.cshtml", 9321, 158, true);

BeginContext("~/Views/SOEE/Index.cshtml", 9480, 44, false);

            
            #line 184 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                   Write(Url.Action("NeedCorrectionByFMAjax", "SOEE"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 9480, 44, false);

BeginContext("~/Views/SOEE/Index.cshtml", 9524, 161, true);

WriteLiteral("\", $(this).data(\"id\"));\n        });\n\n        $(document).on(\"click\", \".js-final-a" +
"pprove\", function (e) {\n            e.preventDefault();\n            updateSOEE(\"" +
"");

EndContext("~/Views/SOEE/Index.cshtml", 9524, 161, true);

BeginContext("~/Views/SOEE/Index.cshtml", 9686, 37, false);

            
            #line 189 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                   Write(Url.Action("ApproveByFDAjax", "SOEE"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 9686, 37, false);

BeginContext("~/Views/SOEE/Index.cshtml", 9723, 122, true);

WriteLiteral("\", $(this).data(\"id\"));\n        });\n\n        $(document).on(\"click\", \".js-partial" +
"\", function () {\n            updateSOEE(\"");

EndContext("~/Views/SOEE/Index.cshtml", 9723, 122, true);

BeginContext("~/Views/SOEE/Index.cshtml", 9846, 43, false);

            
            #line 193 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                   Write(Url.Action("MarkPartiallyPaidAjax", "SOEE"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 9846, 43, false);

BeginContext("~/Views/SOEE/Index.cshtml", 9889, 119, true);

WriteLiteral("\", $(this).data(\"id\"));\n        });\n\n        $(document).on(\"click\", \".js-full\", " +
"function () {\n            updateSOEE(\"");

EndContext("~/Views/SOEE/Index.cshtml", 9889, 119, true);

BeginContext("~/Views/SOEE/Index.cshtml", 10009, 39, false);

            
            #line 197 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                   Write(Url.Action("MarkFullyPaidAjax", "SOEE"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 10009, 39, false);

BeginContext("~/Views/SOEE/Index.cshtml", 10048, 121, true);

WriteLiteral("\", $(this).data(\"id\"));\n        });\n\n        $(document).on(\"click\", \".js-reject\"" +
", function () {\n            updateSOEE(\"");

EndContext("~/Views/SOEE/Index.cshtml", 10048, 121, true);

BeginContext("~/Views/SOEE/Index.cshtml", 10170, 40, false);

            
            #line 201 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                   Write(Url.Action("RejectByClientAjax", "SOEE"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 10170, 40, false);

BeginContext("~/Views/SOEE/Index.cshtml", 10210, 128, true);

WriteLiteral("\", $(this).data(\"id\"));\n        });\n\n        $(document).on(\"click\", \".js-error-p" +
"ayment\", function () {\n            updateSOEE(\"");

EndContext("~/Views/SOEE/Index.cshtml", 10210, 128, true);

BeginContext("~/Views/SOEE/Index.cshtml", 10339, 40, false);

            
            #line 205 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                   Write(Url.Action("ErrorInPaymentAjax", "SOEE"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 10339, 40, false);

BeginContext("~/Views/SOEE/Index.cshtml", 10379, 120, true);

WriteLiteral("\", $(this).data(\"id\"));\n        });\n\n        $(document).on(\"click\", \".js-close\"," +
" function () {\n            updateSOEE(\"");

EndContext("~/Views/SOEE/Index.cshtml", 10379, 120, true);

BeginContext("~/Views/SOEE/Index.cshtml", 10500, 31, false);

            
            #line 209 "C:\projects\SOEEApp-main\SOEEApp\Views\SOEE\Index.cshtml"
                   Write(Url.Action("CloseAjax", "SOEE"));

            
            #line default
            #line hidden
EndContext("~/Views/SOEE/Index.cshtml", 10500, 31, false);

BeginContext("~/Views/SOEE/Index.cshtml", 10531, 50, true);

WriteLiteral("\", $(this).data(\"id\"));\n        });\n    </script>\n");

EndContext("~/Views/SOEE/Index.cshtml", 10531, 50, true);

});

        }
    }
}
